import { Model } from '@/lib/types';

const updatedAt = '2026-04-08T14:40:00+08:00';

export const models: Model[] = [
  {
    slug: 'gpt-5-4-pro',
    name: 'GPT-5.4 Pro',
    providerId: 'openai',
    officialUrl: 'https://openai.com/api/',
    description: {
      en: 'Top-tier generalist model with excellent reasoning depth, strong coding reliability, and mature agent tooling support.',
      'zh-TW': '頂級全能模型，具備出色的推理深度、穩定的程式能力，以及成熟的 agent 工具鏈支援。',
    },
    modalities: ['text', 'image', 'tools'],
    contextWindow: '400K',
    pricing: { input: '$12 / 1M tok', output: '$48 / 1M tok' },
    speedCategory: 'Balanced',
    overallScore: 93,
    scores: {
      capability: 97,
      useCaseFitness: 94,
      costEfficiency: 71,
      speed: 82,
      reliability: 94,
      agentReadiness: 97,
      ecosystem: 98,
    },
    bestUseCases: ['coding', 'research', 'agent-automation'],
    tags: ['flagship', 'coding', 'agents', 'multimodal'],
    strengths: [
      { en: 'Very strong long-horizon task execution', 'zh-TW': '長流程任務執行能力非常強' },
      { en: 'Deep ecosystem integration across tools and APIs', 'zh-TW': '工具與 API 生態整合成熟' },
    ],
    caveats: [
      { en: 'Premium pricing for heavy batch usage', 'zh-TW': '大量批次使用時成本偏高' },
      { en: 'Fast enough, but not the cheapest latency pick', 'zh-TW': '速度夠用，但不是最低延遲與最低成本選擇' },
    ],
    updatedAt,
  },
  {
    slug: 'gpt-5-mini',
    name: 'GPT-5 Mini',
    providerId: 'openai',
    officialUrl: 'https://openai.com/api/',
    description: {
      en: 'Lean, affordable OpenAI model tuned for responsive assistants, classification, and operational agent tasks.',
      'zh-TW': '輕量且價格友善的 OpenAI 模型，適合即時助理、分類與日常 agent 任務。',
    },
    modalities: ['text', 'image', 'tools'],
    contextWindow: '200K',
    pricing: { input: '$1.1 / 1M tok', output: '$4.4 / 1M tok' },
    speedCategory: 'Fast',
    overallScore: 87,
    scores: {
      capability: 85,
      useCaseFitness: 88,
      costEfficiency: 94,
      speed: 94,
      reliability: 88,
      agentReadiness: 91,
      ecosystem: 96,
    },
    bestUseCases: ['agent-automation', 'research'],
    tags: ['efficient', 'assistant', 'ops'],
    strengths: [
      { en: 'Excellent throughput-per-dollar', 'zh-TW': '單位成本產出效率很高' },
      { en: 'Strong tool-calling ergonomics', 'zh-TW': '工具呼叫體驗成熟穩定' },
    ],
    caveats: [
      { en: 'Less depth for frontier-grade reasoning', 'zh-TW': '面對最前沿推理任務時深度較不足' },
      { en: 'May need stronger prompt scaffolding for nuanced analysis', 'zh-TW': '做細緻分析時需要更好的提示框架' },
    ],
    updatedAt,
  },
  {
    slug: 'claude-3-7-sonnet',
    name: 'Claude 3.7 Sonnet',
    providerId: 'anthropic',
    officialUrl: 'https://www.anthropic.com/claude',
    description: {
      en: 'Highly trusted reasoning and coding model with exceptional writing quality and calm, consistent outputs.',
      'zh-TW': '高信任度的推理與程式模型，寫作品質優秀，輸出穩定且一致性高。',
    },
    modalities: ['text', 'image', 'tools'],
    contextWindow: '200K',
    pricing: { input: '$3 / 1M tok', output: '$15 / 1M tok' },
    speedCategory: 'Balanced',
    overallScore: 91,
    scores: {
      capability: 94,
      useCaseFitness: 92,
      costEfficiency: 82,
      speed: 84,
      reliability: 95,
      agentReadiness: 91,
      ecosystem: 90,
    },
    bestUseCases: ['coding', 'research'],
    tags: ['reasoning', 'coding', 'writing'],
    strengths: [
      { en: 'Excellent code edits and technical explanations', 'zh-TW': '程式修改與技術解說能力出色' },
      { en: 'Strong output consistency for editorial workflows', 'zh-TW': '在編輯與寫作流程中穩定度高' },
    ],
    caveats: [
      { en: 'Tool ecosystem is strong but narrower than the broadest platform stacks', 'zh-TW': '工具生態不錯，但仍略窄於最完整的平台型生態' },
      { en: 'Latency can rise on very long deliberative prompts', 'zh-TW': '超長推理提示下延遲可能上升' },
    ],
    updatedAt,
  },
  {
    slug: 'claude-3-5-haiku',
    name: 'Claude 3.5 Haiku',
    providerId: 'anthropic',
    officialUrl: 'https://www.anthropic.com/claude',
    description: {
      en: 'Fast and lightweight model ideal for summarization, routing, support tasks, and budget-sensitive assistants.',
      'zh-TW': '快速輕量模型，適合摘要、任務路由、客服與成本敏感型助理。',
    },
    modalities: ['text', 'image'],
    contextWindow: '200K',
    pricing: { input: '$0.8 / 1M tok', output: '$4 / 1M tok' },
    speedCategory: 'Fast',
    overallScore: 84,
    scores: {
      capability: 78,
      useCaseFitness: 85,
      costEfficiency: 92,
      speed: 96,
      reliability: 88,
      agentReadiness: 80,
      ecosystem: 85,
    },
    bestUseCases: ['research', 'agent-automation'],
    tags: ['fast', 'budget', 'summaries'],
    strengths: [
      { en: 'Responsive and economical for high-volume operations', 'zh-TW': '高量操作下反應快且成本低' },
      { en: 'Strong default tone quality for concise outputs', 'zh-TW': '簡潔輸出時語氣表現穩定' },
    ],
    caveats: [
      { en: 'Limited ceiling for complex multi-step planning', 'zh-TW': '複雜多步驟規劃能力上限有限' },
      { en: 'Less appealing for agent workflows that require richer tool state', 'zh-TW': '需要更複雜工具狀態的 agent 流程較不適合' },
    ],
    updatedAt,
  },
  {
    slug: 'gemini-2-5-pro',
    name: 'Gemini 2.5 Pro',
    providerId: 'google',
    officialUrl: 'https://ai.google.dev/gemini-api',
    description: {
      en: 'Powerful multimodal model with strong long-context analysis, research workflows, and broad document understanding.',
      'zh-TW': '強大的多模態模型，擅長長上下文分析、研究流程與複雜文件理解。',
    },
    modalities: ['text', 'image', 'audio', 'video', 'tools'],
    contextWindow: '1M',
    pricing: { input: '$3.5 / 1M tok', output: '$10.5 / 1M tok' },
    speedCategory: 'Balanced',
    overallScore: 90,
    scores: {
      capability: 95,
      useCaseFitness: 92,
      costEfficiency: 84,
      speed: 81,
      reliability: 89,
      agentReadiness: 88,
      ecosystem: 92,
    },
    bestUseCases: ['research', 'agent-automation'],
    tags: ['long-context', 'multimodal', 'research'],
    strengths: [
      { en: 'Outstanding large-document synthesis', 'zh-TW': '大型文件整合與歸納能力突出' },
      { en: 'One of the best multimodal coverage profiles', 'zh-TW': '多模態覆蓋面非常完整' },
    ],
    caveats: [
      { en: 'UX across endpoints can feel less uniform than the most polished competitors', 'zh-TW': '不同端點體驗的一致性略遜於最成熟對手' },
      { en: 'Not always the fastest interactive pick', 'zh-TW': '互動式回應未必是最快選擇' },
    ],
    updatedAt,
  },
  {
    slug: 'gemini-2-5-flash',
    name: 'Gemini 2.5 Flash',
    providerId: 'google',
    officialUrl: 'https://ai.google.dev/gemini-api',
    description: {
      en: 'Low-latency multimodal workhorse for assistant surfaces, routing layers, and lightweight agent execution.',
      'zh-TW': '低延遲多模態工作馬，適合助理介面、路由層與輕量 agent 執行。',
    },
    modalities: ['text', 'image', 'audio', 'video'],
    contextWindow: '1M',
    pricing: { input: '$0.7 / 1M tok', output: '$2.8 / 1M tok' },
    speedCategory: 'Fast',
    overallScore: 86,
    scores: {
      capability: 82,
      useCaseFitness: 86,
      costEfficiency: 95,
      speed: 97,
      reliability: 86,
      agentReadiness: 84,
      ecosystem: 90,
    },
    bestUseCases: ['agent-automation', 'research'],
    tags: ['multimodal', 'fast', 'assistant'],
    strengths: [
      { en: 'Excellent latency for multimodal interfaces', 'zh-TW': '多模態介面的延遲表現很優秀' },
      { en: 'Very compelling value for large-scale ingestion', 'zh-TW': '大規模資料吞吐時成本效益佳' },
    ],
    caveats: [
      { en: 'Reasoning depth trails premium frontier models', 'zh-TW': '推理深度仍落後旗艦級模型' },
      { en: 'May need a higher-tier fallback for sensitive outputs', 'zh-TW': '高敏感輸出情境可能需要更高階備援模型' },
    ],
    updatedAt,
  },
  {
    slug: 'grok-3-beta',
    name: 'Grok 3 Beta',
    providerId: 'xai',
    officialUrl: 'https://x.ai/',
    description: {
      en: 'Strong real-time orientation and increasingly capable reasoning model with distinctive web freshness advantages.',
      'zh-TW': '偏向即時資訊場景、推理能力持續增強，且具備新鮮網路資訊優勢的模型。',
    },
    modalities: ['text', 'image', 'tools'],
    contextWindow: '256K',
    pricing: { input: '$5 / 1M tok', output: '$15 / 1M tok' },
    speedCategory: 'Balanced',
    overallScore: 83,
    scores: {
      capability: 86,
      useCaseFitness: 84,
      costEfficiency: 74,
      speed: 86,
      reliability: 80,
      agentReadiness: 78,
      ecosystem: 79,
    },
    bestUseCases: ['research'],
    tags: ['web-aware', 'analysis', 'realtime'],
    strengths: [
      { en: 'Useful when freshness matters', 'zh-TW': '重視資訊新鮮度時很有價值' },
      { en: 'Confident long-form synthesis style', 'zh-TW': '長文整合輸出風格有辨識度' },
    ],
    caveats: [
      { en: 'Ecosystem and enterprise controls still maturing', 'zh-TW': '生態與企業級控制面仍在成熟中' },
      { en: 'Less proven for complex agent loops', 'zh-TW': '複雜 agent loop 的實戰驗證較少' },
    ],
    updatedAt,
  },
  {
    slug: 'deepseek-r1',
    name: 'DeepSeek R1',
    providerId: 'deepseek',
    officialUrl: 'https://www.deepseek.com/',
    description: {
      en: 'High-value reasoning model that punches above its price tier for technical problem solving and analytical depth.',
      'zh-TW': '高性價比推理模型，在技術解題與分析深度上常有超出價格帶的表現。',
    },
    modalities: ['text'],
    contextWindow: '128K',
    pricing: { input: '$0.55 / 1M tok', output: '$2.2 / 1M tok' },
    speedCategory: 'Deliberate',
    overallScore: 85,
    scores: {
      capability: 90,
      useCaseFitness: 86,
      costEfficiency: 97,
      speed: 67,
      reliability: 81,
      agentReadiness: 76,
      ecosystem: 73,
    },
    bestUseCases: ['coding', 'research'],
    tags: ['reasoning', 'value', 'math'],
    strengths: [
      { en: 'Very attractive for reasoning-heavy workloads on a budget', 'zh-TW': '預算有限時做重推理任務非常划算' },
      { en: 'Strong analytical style for math and code', 'zh-TW': '在數學與程式分析上表現強勢' },
    ],
    caveats: [
      { en: 'Latency and ecosystem maturity remain trade-offs', 'zh-TW': '延遲與生態成熟度仍是代價' },
      { en: 'Operational guarantees vary by deployment path', 'zh-TW': '不同部署路徑下的穩定性保證不一' },
    ],
    updatedAt,
  },
  {
    slug: 'llama-4-maverick',
    name: 'Llama 4 Maverick',
    providerId: 'meta',
    officialUrl: 'https://ai.meta.com/llama/',
    description: {
      en: 'Flexible open-weight option with broad community experimentation and strong customization potential.',
      'zh-TW': '彈性高的開放權重模型，社群實驗豐富，客製化潛力強。',
    },
    modalities: ['text', 'image'],
    contextWindow: '256K',
    pricing: { input: 'Self-host / variable', output: 'Self-host / variable' },
    speedCategory: 'Balanced',
    overallScore: 80,
    scores: {
      capability: 84,
      useCaseFitness: 82,
      costEfficiency: 88,
      speed: 79,
      reliability: 77,
      agentReadiness: 75,
      ecosystem: 89,
    },
    bestUseCases: ['agent-automation', 'research'],
    tags: ['open-weight', 'customizable', 'self-hosted'],
    strengths: [
      { en: 'Strong fit for teams that need control and self-hosting', 'zh-TW': '需要掌控權與自架的團隊會很適合' },
      { en: 'Community momentum creates many integration paths', 'zh-TW': '社群動能帶來豐富整合方式' },
    ],
    caveats: [
      { en: 'Production quality depends heavily on deployment discipline', 'zh-TW': '正式環境品質非常依賴部署水準' },
      { en: 'Benchmark strength does not always translate to polished UX', 'zh-TW': 'benchmark 成績不一定等於實際體驗成熟' },
    ],
    updatedAt,
  },
  {
    slug: 'qwen-3-max',
    name: 'Qwen 3 Max',
    providerId: 'alibaba-cloud',
    officialUrl: 'https://www.alibabacloud.com/product/model-studio',
    description: {
      en: 'Ambitious frontier contender with strong multilingual performance and good enterprise utility across Asian markets.',
      'zh-TW': '具競爭力的前沿模型，在多語言尤其亞洲市場企業場景中有不錯表現。',
    },
    modalities: ['text', 'image', 'tools'],
    contextWindow: '256K',
    pricing: { input: '$2.4 / 1M tok', output: '$9 / 1M tok' },
    speedCategory: 'Balanced',
    overallScore: 84,
    scores: {
      capability: 88,
      useCaseFitness: 85,
      costEfficiency: 86,
      speed: 82,
      reliability: 82,
      agentReadiness: 80,
      ecosystem: 81,
    },
    bestUseCases: ['research', 'agent-automation'],
    tags: ['multilingual', 'enterprise', 'asia'],
    strengths: [
      { en: 'Strong multilingual coverage and pragmatic enterprise fit', 'zh-TW': '多語能力強，企業落地實用度高' },
      { en: 'Balanced performance profile without extreme weaknesses', 'zh-TW': '整體表現均衡，沒有明顯短板' },
    ],
    caveats: [
      { en: 'Global ecosystem mindshare is still catching up', 'zh-TW': '全球生態心智仍在追趕中' },
      { en: 'Docs and examples can vary by region', 'zh-TW': '文件與案例完整度因地區而異' },
    ],
    updatedAt,
  },
  {
    slug: 'mistral-large-2',
    name: 'Mistral Large 2',
    providerId: 'mistral',
    officialUrl: 'https://mistral.ai/products/la-plateforme',
    description: {
      en: 'European flagship model with solid reasoning, concise style, and attractive deployment flexibility.',
      'zh-TW': '歐洲旗艦模型，具備紮實推理、精簡風格與靈活部署優勢。',
    },
    modalities: ['text', 'image'],
    contextWindow: '128K',
    pricing: { input: '$2 / 1M tok', output: '$6 / 1M tok' },
    speedCategory: 'Balanced',
    overallScore: 82,
    scores: {
      capability: 84,
      useCaseFitness: 83,
      costEfficiency: 87,
      speed: 84,
      reliability: 81,
      agentReadiness: 78,
      ecosystem: 78,
    },
    bestUseCases: ['research', 'coding'],
    tags: ['enterprise', 'concise', 'eu'],
    strengths: [
      { en: 'Clean enterprise-friendly posture and deployment options', 'zh-TW': '企業友善姿態與部署選項清楚' },
      { en: 'Good balance between cost and reasoning quality', 'zh-TW': '成本與推理品質之間取得不錯平衡' },
    ],
    caveats: [
      { en: 'Ecosystem is smaller than the hyperscaler leaders', 'zh-TW': '生態規模仍小於超大平台領先者' },
      { en: 'Less differentiated for multimodal-heavy product surfaces', 'zh-TW': '對多模態產品面來說差異化較少' },
    ],
    updatedAt,
  },
  {
    slug: 'command-a',
    name: 'Command A',
    providerId: 'cohere',
    officialUrl: 'https://cohere.com/',
    description: {
      en: 'Enterprise-oriented model with strong retrieval posture, business language handling, and dependable workflow integration.',
      'zh-TW': '偏企業導向的模型，適合檢索增強、商務語言處理與穩定工作流整合。',
    },
    modalities: ['text', 'tools'],
    contextWindow: '256K',
    pricing: { input: '$2 / 1M tok', output: '$8 / 1M tok' },
    speedCategory: 'Balanced',
    overallScore: 81,
    scores: {
      capability: 82,
      useCaseFitness: 84,
      costEfficiency: 83,
      speed: 82,
      reliability: 84,
      agentReadiness: 79,
      ecosystem: 77,
    },
    bestUseCases: ['research', 'agent-automation'],
    tags: ['enterprise', 'retrieval', 'workflow'],
    strengths: [
      { en: 'Strong fit for internal knowledge workflows', 'zh-TW': '很適合內部知識工作流' },
      { en: 'Dependable enterprise integration story', 'zh-TW': '企業整合敘事穩定可信' },
    ],
    caveats: [
      { en: 'Less mindshare in cutting-edge coding circles', 'zh-TW': '在最前沿 coding 圈中的心智較弱' },
      { en: 'Not the most exciting pick for multimodal experiences', 'zh-TW': '多模態體驗不是它的主打強項' },
    ],
    updatedAt,
  },
  {
    slug: 'perplexity-sonar-reasoning-pro',
    name: 'Sonar Reasoning Pro',
    providerId: 'perplexity',
    officialUrl: 'https://www.perplexity.ai/hub/blog/sonar',
    description: {
      en: 'Research-first model experience optimized for answer grounding, current web synthesis, and citation-friendly output.',
      'zh-TW': '偏研究導向的模型體驗，強調有根據的答案、即時網頁整合與引用友善輸出。',
    },
    modalities: ['text', 'web'],
    contextWindow: '128K',
    pricing: { input: '$2 / 1M tok', output: '$8 / 1M tok' },
    speedCategory: 'Balanced',
    overallScore: 83,
    scores: {
      capability: 85,
      useCaseFitness: 89,
      costEfficiency: 82,
      speed: 80,
      reliability: 84,
      agentReadiness: 74,
      ecosystem: 76,
    },
    bestUseCases: ['research'],
    tags: ['research', 'citations', 'web'],
    strengths: [
      { en: 'Great for research UX with source visibility', 'zh-TW': '研究型體驗下可見來源這點很有優勢' },
      { en: 'Useful for analyst workflows that need current context', 'zh-TW': '需要即時背景的分析流程相當適合' },
    ],
    caveats: [
      { en: 'Not a primary choice for tool-heavy coding agents', 'zh-TW': '不適合做工具密集的 coding agent 主力' },
      { en: 'Less control than fully orchestrated platform APIs', 'zh-TW': '相比完整平台 API，可控性較低' },
    ],
    updatedAt,
  },
];
