import { defineModel, manualReviewSource, officialSource } from './factories';

const VERIFIED_AT = '2026-04-09T08:00:00.000Z';
const EXPANDED_VERIFIED_AT = '2026-04-13T05:45:00.000Z';

const t = (en: string, zhTW: string) => ({ en, 'zh-TW': zhTW });

const editorialFields = ['bestFor', 'worksWith', 'strengths', 'caveats', 'overallScore', 'scores'];

function review(name: string) {
  return manualReviewSource(`${name} VerdictLens review`, VERIFIED_AT, editorialFields, 'Editorial shortlist guidance is intentionally separated from official provider facts.');
}

export const models = [
  defineModel({
    slug: 'gpt-5',
    name: 'GPT-5',
    providerId: 'openai',
    family: 'GPT-5',
    officialUrl: 'https://openai.com/',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-5',
    pricingUrl: 'https://openai.com/api/pricing/',
    description: t('OpenAI’s previous flagship reasoning model for coding, agentic tasks, and broad professional work.', 'OpenAI 先前的旗艦推理模型，適合 coding、agent 任務與廣泛專業工作。'),
    modalities: ['text', 'image'],
    modalityProfile: { input: ['text', 'image'], output: ['text', 'json'] },
    contextWindow: '400K tokens',
    maxOutputTokens: '128K tokens',
    pricing: {
      input: '$1.25 / 1M input tokens',
      output: '$10 / 1M output tokens',
      inputUsdPerMillion: '1.25',
      outputUsdPerMillion: '10',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: true, remoteMcp: true, codeExecution: true },
    overallScore: 92,
    scores: { capability: 94, useCaseFitness: 93, costEfficiency: 82, speed: 85, reliability: 92, agentReadiness: 94, ecosystem: 96 },
    bestUseCases: ['coding', 'agent-automation'],
    worksWith: ['Codex CLI', 'OpenAI Responses API', 'LangGraph', 'E2B'],
    tags: ['reasoning', 'coding', 'agentic'],
    strengths: [
      t('Strong coding and tool-use baseline with broad ecosystem support.', 'coding 與工具使用基線強，且生態支援廣。'),
      t('Large context and mature Responses API integration.', '上下文大，且 Responses API 整合成熟。'),
    ],
    caveats: [
      t('No longer OpenAI’s newest flagship tier.', '已不是 OpenAI 最新旗艦層級。'),
      t('Costs rise quickly on long, high-output workflows.', '長上下文與高輸出工作流成本會快速上升。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('OpenAI official', 'https://openai.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('GPT-5 model docs', 'https://platform.openai.com/docs/models/gpt-5', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile', 'contextWindow', 'maxOutputTokens', 'toolSupport']),
      officialSource('OpenAI API pricing', 'https://openai.com/api/pricing/', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('GPT-5'),
    ],
  }),
  defineModel({
    slug: 'gpt-5-mini',
    name: 'GPT-5 mini',
    providerId: 'openai',
    family: 'GPT-5',
    officialUrl: 'https://openai.com/',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-5-mini',
    pricingUrl: 'https://openai.com/api/pricing/',
    description: t('A lower-cost GPT-5 variant tuned for low-latency, high-volume workloads.', '較低成本的 GPT-5 變體，適合低延遲與高吞吐工作負載。'),
    modalities: ['text', 'image'],
    modalityProfile: { input: ['text', 'image'], output: ['text', 'json'] },
    contextWindow: '400K tokens',
    maxOutputTokens: '128K tokens',
    pricing: {
      input: '$0.25 / 1M input tokens',
      output: '$2 / 1M output tokens',
      inputUsdPerMillion: '0.25',
      outputUsdPerMillion: '2',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: true, remoteMcp: true, codeExecution: true },
    overallScore: 89,
    scores: { capability: 88, useCaseFitness: 90, costEfficiency: 91, speed: 92, reliability: 89, agentReadiness: 90, ecosystem: 95 },
    bestUseCases: ['coding', 'agent-automation'],
    worksWith: ['Codex CLI', 'OpenAI Responses API', 'LangChain', 'Browserbase'],
    tags: ['high-volume', 'coding', 'cost-aware'],
    strengths: [
      t('Good balance of price, latency, and tool-use support.', '價格、延遲與工具支援之間的平衡不錯。'),
      t('Useful default for production agent loops that do not need frontier reasoning every turn.', '很適合作為不需要每輪都用前沿推理的 production agent 預設。'),
    ],
    caveats: [
      t('Not the best choice for the hardest reasoning tasks.', '對最難的推理任務不是最佳選擇。'),
      t('Still more expensive than ultra-cheap routing tiers.', '仍比超低價 routing 層更貴。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('OpenAI official', 'https://openai.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('GPT-5 mini model docs', 'https://platform.openai.com/docs/models/gpt-5-mini', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile', 'contextWindow', 'maxOutputTokens', 'toolSupport']),
      officialSource('OpenAI API pricing', 'https://openai.com/api/pricing/', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('GPT-5 mini'),
    ],
  }),
  defineModel({
    slug: 'gpt-5-nano',
    name: 'GPT-5 nano',
    providerId: 'openai',
    family: 'GPT-5',
    officialUrl: 'https://openai.com/',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-5-nano',
    pricingUrl: 'https://openai.com/api/pricing/',
    description: t('The fastest and cheapest GPT-5 tier for summarization, classification, and simple automation.', '速度最快、成本最低的 GPT-5 層級，適合摘要、分類與簡單自動化。'),
    modalities: ['text', 'image'],
    modalityProfile: { input: ['text', 'image'], output: ['text', 'json'] },
    contextWindow: '400K tokens',
    maxOutputTokens: '128K tokens',
    pricing: {
      input: '$0.05 / 1M input tokens',
      output: '$0.40 / 1M output tokens',
      inputUsdPerMillion: '0.05',
      outputUsdPerMillion: '0.40',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: true, remoteMcp: true, codeExecution: true },
    overallScore: 85,
    scores: { capability: 80, useCaseFitness: 84, costEfficiency: 97, speed: 96, reliability: 86, agentReadiness: 84, ecosystem: 94 },
    bestUseCases: ['agent-automation', 'research'],
    worksWith: ['LangChain', 'Zapier AI Actions', 'n8n', 'OpenAI Responses API'],
    tags: ['cheap', 'summarization', 'classification'],
    strengths: [
      t('Very strong cost profile for routing, triage, and pre-processing.', '很適合拿來做 routing、分類與前處理。'),
      t('Maintains built-in tool support despite the low price tier.', '即使在低價位仍保留內建工具支援。'),
    ],
    caveats: [
      t('Capability ceiling is lower for nuanced coding or planning.', '在細緻 coding 或規劃任務上的能力上限較低。'),
      t('Best used as part of a routed stack rather than as the only model.', '更適合放在 routed stack 裡，而不是單獨承擔全部工作。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('OpenAI official', 'https://openai.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('GPT-5 nano model docs', 'https://platform.openai.com/docs/models/gpt-5-nano', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile', 'contextWindow', 'maxOutputTokens', 'toolSupport']),
      officialSource('OpenAI API pricing', 'https://openai.com/api/pricing/', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('GPT-5 nano'),
    ],
  }),
  defineModel({
    slug: 'gpt-realtime-mini',
    name: 'gpt-realtime-mini',
    providerId: 'openai',
    family: 'GPT Realtime',
    officialUrl: 'https://openai.com/',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-realtime-mini',
    pricingUrl: 'https://openai.com/api/pricing/',
    description: t('A cost-efficient realtime model for voice and streaming interactions over WebRTC, WebSocket, or SIP.', '面向語音與串流互動的高性價比 realtime 模型，可走 WebRTC、WebSocket 或 SIP。'),
    modalities: ['text', 'audio', 'image'],
    modalityProfile: { input: ['text', 'audio', 'image'], output: ['text', 'audio'] },
    contextWindow: '32K tokens',
    maxOutputTokens: '4,096 tokens',
    pricing: {
      input: '$0.60 / 1M text input tokens',
      output: '$2.40 / 1M text output tokens',
      inputUsdPerMillion: '0.60',
      outputUsdPerMillion: '2.40',
      notes: 'OpenAI lists separate audio pricing on the API pricing page.',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: false, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 84,
    scores: { capability: 79, useCaseFitness: 88, costEfficiency: 89, speed: 98, reliability: 84, agentReadiness: 87, ecosystem: 90 },
    bestUseCases: ['agent-automation'],
    worksWith: ['Voice agents', 'WebRTC apps', 'Telephony'],
    tags: ['realtime', 'voice', 'streaming'],
    strengths: [
      t('Low-latency audio and text interaction is the main strength.', '低延遲音訊與文字互動是最大優勢。'),
      t('Useful when UX speed matters more than deep long-form reasoning.', '當 UX 速度比長篇深度推理更重要時很有價值。'),
    ],
    caveats: [
      t('Smaller context and output limits than general frontier text models.', '上下文與輸出上限都小於通用前沿文字模型。'),
      t('Not the right default for research-heavy or long-document tasks.', '不適合作為研究型或長文件任務的預設模型。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('OpenAI official', 'https://openai.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('gpt-realtime-mini model docs', 'https://platform.openai.com/docs/models/gpt-realtime-mini', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile', 'contextWindow', 'maxOutputTokens']),
      officialSource('OpenAI API pricing', 'https://openai.com/api/pricing/', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('gpt-realtime-mini'),
    ],
  }),
  defineModel({
    slug: 'gpt-image-1-mini',
    name: 'gpt-image-1-mini',
    providerId: 'openai',
    family: 'GPT Image',
    officialUrl: 'https://openai.com/',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-image-1-mini',
    pricingUrl: 'https://openai.com/api/pricing/',
    description: t('OpenAI’s lower-cost image generation tier for high-volume image workflows.', 'OpenAI 較低成本的圖像生成層，適合高吞吐影像工作流。'),
    modalities: ['text', 'image'],
    modalityProfile: { input: ['text', 'image'], output: ['image'] },
    contextWindow: 'Model-page pricing only',
    pricing: {
      input: '$2 / 1M text input tokens or $2.50 / 1M image input tokens',
      output: '$8 / 1M image output tokens',
      inputUsdPerMillion: '2',
      outputUsdPerMillion: '8',
      notes: 'OpenAI also publishes per-image generation prices by size and quality.',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: false, structuredOutput: false, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 79,
    scores: { capability: 82, useCaseFitness: 84, costEfficiency: 85, speed: 80, reliability: 81, agentReadiness: 70, ecosystem: 88 },
    bestUseCases: ['research'],
    worksWith: ['Creative tooling', 'Marketing pipelines', 'Image editing flows'],
    tags: ['image-generation', 'creative', 'multimodal'],
    strengths: [
      t('Lower-cost image generation option from the same OpenAI stack.', '可在同一 OpenAI stack 中使用的低成本圖像生成選項。'),
      t('Useful when teams want simpler procurement and vendor consolidation.', '適合想簡化採購與供應商整合的團隊。'),
    ],
    caveats: [
      t('Not a general text model and should not be compared like one.', '不是通用文字模型，不該用同樣方式比較。'),
      t('Official docs emphasize pricing more than broader capability detail.', '官方頁面更偏重價格資訊，而不是更完整的能力說明。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('OpenAI official', 'https://openai.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('gpt-image-1-mini model docs', 'https://platform.openai.com/docs/models/gpt-image-1-mini', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile']),
      officialSource('OpenAI API pricing', 'https://openai.com/api/pricing/', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('gpt-image-1-mini'),
    ],
  }),
  defineModel({
    slug: 'claude-opus-4-6',
    name: 'Claude Opus 4.6',
    providerId: 'anthropic',
    family: 'Claude 4',
    officialUrl: 'https://www.anthropic.com/',
    docsUrl: 'https://docs.anthropic.com/en/docs/about-claude/models/overview',
    pricingUrl: 'https://www.anthropic.com/pricing#api',
    description: t('Anthropic’s highest-capability Claude tier for difficult reasoning, long-form synthesis, and premium agent work.', 'Anthropic 最高能力的 Claude 層級，適合高難度推理、長篇整合與高價值 agent 工作。'),
    modalities: ['text', 'image', 'file'],
    modalityProfile: { input: ['text', 'image', 'file'], output: ['text', 'json'] },
    contextWindow: '200K tokens',
    maxOutputTokens: '32K tokens',
    pricing: {
      input: '$15 / 1M input tokens',
      output: '$75 / 1M output tokens',
      inputUsdPerMillion: '15',
      outputUsdPerMillion: '75',
    },
    speedCategory: 'Deliberate',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: true, codeExecution: true },
    overallScore: 94,
    scores: { capability: 97, useCaseFitness: 94, costEfficiency: 71, speed: 76, reliability: 94, agentReadiness: 95, ecosystem: 92 },
    bestUseCases: ['coding', 'research', 'agent-automation'],
    worksWith: ['Claude Code', 'Anthropic API', 'LangGraph', 'MCP clients'],
    tags: ['frontier', 'reasoning', 'long-form'],
    strengths: [
      t('Top-tier reasoning and synthesis for hard tasks.', '在高難度任務上的推理與整合能力屬第一梯隊。'),
      t('Strong fit for premium research and coding workflows.', '很適合高價值研究與 coding 工作流。'),
    ],
    caveats: [
      t('Premium pricing makes cost control important.', '價格偏高，必須重視成本控制。'),
      t('Often better reserved for escalation rather than every request.', '更適合作為升級路由，而不是每個請求都直接使用。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Anthropic official', 'https://www.anthropic.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Claude models overview', 'https://docs.anthropic.com/en/docs/about-claude/models/overview', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'contextWindow', 'maxOutputTokens', 'toolSupport']),
      officialSource('Anthropic API pricing', 'https://www.anthropic.com/pricing#api', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('Claude Opus 4.6'),
    ],
  }),
  defineModel({
    slug: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    providerId: 'anthropic',
    family: 'Claude 4',
    officialUrl: 'https://www.anthropic.com/',
    docsUrl: 'https://docs.anthropic.com/en/docs/about-claude/models/overview',
    pricingUrl: 'https://www.anthropic.com/pricing#api',
    description: t('Anthropic’s balanced Claude tier for broad production use, coding, and agent orchestration.', 'Anthropic 較均衡的 Claude 層級，適合廣泛 production、coding 與 agent 編排。'),
    modalities: ['text', 'image', 'file'],
    modalityProfile: { input: ['text', 'image', 'file'], output: ['text', 'json'] },
    contextWindow: '200K tokens',
    maxOutputTokens: '64K tokens',
    pricing: {
      input: '$3 / 1M input tokens',
      output: '$15 / 1M output tokens',
      inputUsdPerMillion: '3',
      outputUsdPerMillion: '15',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: true, codeExecution: true },
    overallScore: 92,
    scores: { capability: 93, useCaseFitness: 95, costEfficiency: 85, speed: 87, reliability: 93, agentReadiness: 95, ecosystem: 92 },
    bestUseCases: ['coding', 'agent-automation'],
    worksWith: ['Claude Code', 'Anthropic API', 'LangChain', 'MCP clients'],
    tags: ['balanced', 'coding', 'agents'],
    strengths: [
      t('One of the strongest default choices for practical coding and agent work.', '是實務 coding 與 agent 工作很強的預設選擇之一。'),
      t('Better price-performance than the premium Opus tier for many teams.', '對多數團隊來說，價格效益通常比 Opus 更合理。'),
    ],
    caveats: [
      t('Still premium-priced versus budget routing tiers.', '與低價 routing 層相比仍偏貴。'),
      t('May not justify use on simple high-volume automation.', '在簡單高量自動化場景上未必划算。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Anthropic official', 'https://www.anthropic.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Claude models overview', 'https://docs.anthropic.com/en/docs/about-claude/models/overview', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'contextWindow', 'maxOutputTokens', 'toolSupport']),
      officialSource('Anthropic API pricing', 'https://www.anthropic.com/pricing#api', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('Claude Sonnet 4.6'),
    ],
  }),
  defineModel({
    slug: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    providerId: 'anthropic',
    family: 'Claude 4',
    officialUrl: 'https://www.anthropic.com/',
    docsUrl: 'https://docs.anthropic.com/en/docs/about-claude/models/overview',
    pricingUrl: 'https://www.anthropic.com/pricing#api',
    description: t('Anthropic’s faster lower-cost Claude tier for lightweight production tasks.', 'Anthropic 速度較快、成本較低的 Claude 層級，適合輕量 production 任務。'),
    modalities: ['text', 'image', 'file'],
    modalityProfile: { input: ['text', 'image', 'file'], output: ['text', 'json'] },
    contextWindow: '200K tokens',
    maxOutputTokens: '64K tokens',
    pricing: {
      input: '$1 / 1M input tokens',
      output: '$5 / 1M output tokens',
      inputUsdPerMillion: '1',
      outputUsdPerMillion: '5',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: true, codeExecution: true },
    overallScore: 87,
    scores: { capability: 84, useCaseFitness: 87, costEfficiency: 90, speed: 93, reliability: 89, agentReadiness: 87, ecosystem: 90 },
    bestUseCases: ['agent-automation', 'research'],
    worksWith: ['Anthropic API', 'automation workers', 'classification flows'],
    tags: ['fast', 'budget', 'classification'],
    strengths: [
      t('Useful for faster Claude-aligned production paths.', '適合需要 Claude 風格但更快的 production 路徑。'),
      t('Good step-down tier under Sonnet for routed stacks.', '在 routed stack 裡很適合作為 Sonnet 之下的降級層。'),
    ],
    caveats: [
      t('Not the best option for deep reasoning or hard coding.', '不是深度推理或高難度 coding 的最佳選擇。'),
      t('Many teams will still want Sonnet for their main interactive tier.', '很多團隊主互動層仍會偏向 Sonnet。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Anthropic official', 'https://www.anthropic.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Claude models overview', 'https://docs.anthropic.com/en/docs/about-claude/models/overview', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'contextWindow', 'maxOutputTokens', 'toolSupport']),
      officialSource('Anthropic API pricing', 'https://www.anthropic.com/pricing#api', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('Claude Haiku 4.5'),
    ],
  }),
  defineModel({
    slug: 'gemini-2-5-pro',
    name: 'Gemini 2.5 Pro',
    providerId: 'google',
    family: 'Gemini 2.5',
    officialUrl: 'https://ai.google.dev/',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/models/gemini-2.5-pro',
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    description: t('Google’s most advanced Gemini 2.5 model for complex reasoning and coding tasks.', 'Google 在 Gemini 2.5 系列中最先進的模型，適合複雜推理與 coding 任務。'),
    modalities: ['text', 'image', 'audio', 'video'],
    modalityProfile: { input: ['text', 'image', 'audio', 'video'], output: ['text', 'json'] },
    contextWindow: '1M tokens',
    pricing: {
      input: '$1.25 / 1M input tokens (≤200K prompts)',
      output: '$10 / 1M output tokens (≤200K prompts)',
      inputUsdPerMillion: '1.25',
      outputUsdPerMillion: '10',
      notes: 'Google lists higher rates for prompts above 200K tokens.',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: true, remoteMcp: false, codeExecution: false },
    overallScore: 91,
    scores: { capability: 94, useCaseFitness: 92, costEfficiency: 84, speed: 84, reliability: 89, agentReadiness: 90, ecosystem: 92 },
    bestUseCases: ['coding', 'research'],
    worksWith: ['Gemini API', 'Vertex AI', 'grounded search flows'],
    tags: ['multimodal', 'reasoning', 'long-context'],
    strengths: [
      t('Strong multimodal reasoning with very large context.', '多模態推理強，且上下文很大。'),
      t('Good fit for teams already using Google AI or Vertex AI paths.', '對已經在用 Google AI 或 Vertex AI 的團隊很順。'),
    ],
    caveats: [
      t('Google pricing becomes more complex on very long prompts and grounded calls.', '在超長 prompt 與 grounding 呼叫時，Google 定價會更複雜。'),
      t('Tooling conventions differ from OpenAI and Anthropic-centered stacks.', '工具介面習慣與 OpenAI / Anthropic 生態不完全一致。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Google AI for Developers', 'https://ai.google.dev/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Gemini 2.5 Pro model docs', 'https://ai.google.dev/gemini-api/docs/models/gemini-2.5-pro', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile', 'contextWindow']),
      officialSource('Gemini API pricing', 'https://ai.google.dev/gemini-api/docs/pricing', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl', 'toolSupport']),
      review('Gemini 2.5 Pro'),
    ],
  }),
  defineModel({
    slug: 'gemini-2-5-flash',
    name: 'Gemini 2.5 Flash',
    providerId: 'google',
    family: 'Gemini 2.5',
    officialUrl: 'https://ai.google.dev/',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash',
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    description: t('Google’s price-performance Gemini 2.5 tier for low-latency, high-volume reasoning work.', 'Google 偏重價格效能的 Gemini 2.5 層級，適合低延遲、高吞吐的推理工作。'),
    modalities: ['text', 'image', 'audio', 'video'],
    modalityProfile: { input: ['text', 'image', 'audio', 'video'], output: ['text', 'json'] },
    contextWindow: '1M tokens',
    pricing: {
      input: '$0.30 / 1M text-image-video input tokens',
      output: '$2.50 / 1M output tokens',
      inputUsdPerMillion: '0.30',
      outputUsdPerMillion: '2.50',
      notes: 'Google lists separate audio pricing and grounding fees.',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: true, remoteMcp: false, codeExecution: false },
    overallScore: 88,
    scores: { capability: 86, useCaseFitness: 89, costEfficiency: 91, speed: 92, reliability: 87, agentReadiness: 88, ecosystem: 91 },
    bestUseCases: ['agent-automation', 'research'],
    worksWith: ['Gemini API', 'Vertex AI', 'grounded search flows'],
    tags: ['fast', 'multimodal', 'price-performance'],
    strengths: [
      t('Attractive cost-performance profile for multimodal workloads.', '對多模態工作負載來說成本效能很有吸引力。'),
      t('Useful when teams want one vendor for search-grounded and multimodal flows.', '適合想用單一供應商處理 grounding 與多模態流程的團隊。'),
    ],
    caveats: [
      t('May need careful prompt and product tuning for complex agent patterns.', '在複雜 agent 模式下，仍需要較細的 prompt 與產品調校。'),
      t('Ecosystem examples are not as ubiquitous as OpenAI defaults.', '生態範例的普及度仍不如 OpenAI 預設路線。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Google AI for Developers', 'https://ai.google.dev/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Gemini 2.5 Flash model docs', 'https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile', 'contextWindow']),
      officialSource('Gemini API pricing', 'https://ai.google.dev/gemini-api/docs/pricing', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl', 'toolSupport']),
      review('Gemini 2.5 Flash'),
    ],
  }),
  defineModel({
    slug: 'gemini-2-5-flash-lite',
    name: 'Gemini 2.5 Flash-Lite',
    providerId: 'google',
    family: 'Gemini 2.5',
    officialUrl: 'https://ai.google.dev/',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash-lite',
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    description: t('Google’s cheapest Gemini 2.5 tier for high-frequency multimodal classification, extraction, and lightweight agent work.', 'Google 成本最低的 Gemini 2.5 層級，適合高頻多模態分類、擷取與輕量 agent 工作。'),
    modalities: ['text', 'image', 'audio', 'video', 'file'],
    modalityProfile: { input: ['text', 'image', 'audio', 'video', 'file'], output: ['text', 'json'] },
    contextWindow: '1,048,576 input tokens',
    maxOutputTokens: '65,536 tokens',
    pricing: {
      input: '$0.10 / 1M text-image-video input tokens',
      output: '$0.40 / 1M output tokens',
      inputUsdPerMillion: '0.10',
      outputUsdPerMillion: '0.40',
      notes: 'Google lists separate audio pricing and grounding fees on the Gemini pricing page.',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: true, remoteMcp: false, codeExecution: true },
    overallScore: 86,
    scores: { capability: 80, useCaseFitness: 88, costEfficiency: 97, speed: 96, reliability: 86, agentReadiness: 87, ecosystem: 91 },
    bestUseCases: ['agent-automation', 'research'],
    worksWith: ['Gemini API', 'Vertex AI', 'high-volume extraction flows'],
    tags: ['flash-lite', 'budget', 'multimodal'],
    strengths: [
      t('Very strong cost profile for large-scale classification and extraction pipelines.', '很適合大規模分類與擷取流程，成本輪廓非常漂亮。'),
      t('Keeps Gemini’s multimodal inputs and structured outputs at a lower price tier.', '在較低價位仍保留 Gemini 的多模態輸入與 structured outputs。'),
    ],
    caveats: [
      t('Not the right pick for harder frontier reasoning.', '對較難的前沿推理不是最佳選擇。'),
      t('Google’s pricing surface still includes separate audio and grounding fees.', 'Google 的定價面仍包含獨立的音訊與 grounding 費用。'),
    ],
    updatedAt: EXPANDED_VERIFIED_AT,
    sourceRefs: [
      officialSource('Google AI for Developers', 'https://ai.google.dev/', 'official-site', EXPANDED_VERIFIED_AT, ['officialUrl']),
      officialSource('Gemini 2.5 Flash-Lite model docs', 'https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash-lite', 'official-docs', EXPANDED_VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile', 'contextWindow', 'maxOutputTokens', 'toolSupport']),
      officialSource('Gemini API pricing', 'https://ai.google.dev/gemini-api/docs/pricing', 'pricing-page', EXPANDED_VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('Gemini 2.5 Flash-Lite'),
    ],
  }),
  defineModel({
    slug: 'grok-4-20',
    name: 'Grok 4.20',
    providerId: 'xai',
    family: 'Grok 4',
    officialUrl: 'https://x.ai/',
    docsUrl: 'https://docs.x.ai/developers/models',
    pricingUrl: 'https://docs.x.ai/developers/models',
    description: t('xAI’s flagship Grok reasoning tier with a very large context window and native tool-oriented positioning.', 'xAI 的旗艦 Grok 推理層，具備超大上下文與偏工具導向的官方定位。'),
    modalities: ['text', 'image'],
    modalityProfile: { input: ['text', 'image'], output: ['text', 'json'] },
    contextWindow: '2M tokens',
    pricing: {
      input: '$2 / 1M input tokens ($0.20 cached)',
      output: '$6 / 1M output tokens',
      inputUsdPerMillion: '2',
      outputUsdPerMillion: '6',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: true, remoteMcp: true, codeExecution: true },
    overallScore: 90,
    scores: { capability: 93, useCaseFitness: 90, costEfficiency: 82, speed: 86, reliability: 86, agentReadiness: 92, ecosystem: 84 },
    bestUseCases: ['research', 'agent-automation'],
    worksWith: ['xAI API', 'server-side search tools', 'MCP-capable agent stacks'],
    tags: ['reasoning', 'long-context', 'tool-use'],
    strengths: [
      t('Big context window and official support for tool-centric workflows are the main draw.', '超大上下文與官方工具導向工作流支援，是主要賣點。'),
      t('Useful for teams wanting frontier-style reasoning outside the usual OpenAI/Anthropic duopoly.', '對想跳脫 OpenAI / Anthropic 雙雄、又需要前沿推理的團隊很有吸引力。'),
    ],
    caveats: [
      t('xAI’s ecosystem depth is still thinner than the most mature platforms.', 'xAI 的生態厚度仍比最成熟的平台薄。'),
      t('Official pricing is bundled with xAI-native server-side tools, so cost modeling needs care.', '官方定價與 xAI 內建 server-side tools 關聯較深，估算成本時要更小心。'),
    ],
    updatedAt: EXPANDED_VERIFIED_AT,
    sourceRefs: [
      officialSource('xAI official', 'https://x.ai/', 'official-site', EXPANDED_VERIFIED_AT, ['officialUrl']),
      officialSource('xAI models and pricing', 'https://docs.x.ai/developers/models', 'official-docs', EXPANDED_VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile', 'contextWindow', 'toolSupport', 'pricing', 'pricingUrl']),
      review('Grok 4.20'),
    ],
  }),
  defineModel({
    slug: 'grok-4-1-fast',
    name: 'Grok 4.1 Fast',
    providerId: 'xai',
    family: 'Grok 4.1',
    officialUrl: 'https://x.ai/',
    docsUrl: 'https://docs.x.ai/developers/models',
    pricingUrl: 'https://docs.x.ai/developers/models',
    description: t('xAI’s lower-cost Grok 4.1 fast tier for cheaper reasoning-oriented production traffic.', 'xAI 較低成本的 Grok 4.1 fast 層，適合更便宜的推理導向 production 流量。'),
    modalities: ['text', 'image'],
    modalityProfile: { input: ['text', 'image'], output: ['text', 'json'] },
    contextWindow: '2M tokens',
    pricing: {
      input: '$0.20 / 1M input tokens ($0.05 cached)',
      output: '$0.50 / 1M output tokens',
      inputUsdPerMillion: '0.20',
      outputUsdPerMillion: '0.50',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: true, remoteMcp: true, codeExecution: true },
    overallScore: 87,
    scores: { capability: 84, useCaseFitness: 88, costEfficiency: 94, speed: 94, reliability: 85, agentReadiness: 89, ecosystem: 84 },
    bestUseCases: ['agent-automation', 'research'],
    worksWith: ['xAI API', 'cost-aware reasoning flows', 'tool-first assistants'],
    tags: ['fast', 'budget-reasoning', 'tool-use'],
    strengths: [
      t('Much cheaper Grok-family entry point while keeping the same large context footprint.', '用更低價格進入 Grok 家族，且保留同樣的大上下文規模。'),
      t('Useful for teams that want xAI coverage without paying flagship rates on every request.', '適合想納入 xAI，但不想每次都付旗艦價格的團隊。'),
    ],
    caveats: [
      t('Lower ceiling than the flagship Grok 4.20 tier on hardest tasks.', '在最難任務上的能力上限低於旗艦 Grok 4.20。'),
      t('xAI platform conventions are still less standardized than older API ecosystems.', 'xAI 平台慣例仍不如較老牌 API 生態那麼標準化。'),
    ],
    updatedAt: EXPANDED_VERIFIED_AT,
    sourceRefs: [
      officialSource('xAI official', 'https://x.ai/', 'official-site', EXPANDED_VERIFIED_AT, ['officialUrl']),
      officialSource('xAI models and pricing', 'https://docs.x.ai/developers/models', 'official-docs', EXPANDED_VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile', 'contextWindow', 'toolSupport', 'pricing', 'pricingUrl']),
      review('Grok 4.1 Fast'),
    ],
  }),
  defineModel({
    slug: 'qwen3-max',
    name: 'Qwen3-Max',
    providerId: 'alibaba-cloud',
    family: 'Qwen3',
    officialUrl: 'https://www.alibabacloud.com/product/model-studio',
    docsUrl: 'https://www.alibabacloud.com/help/en/model-studio/models',
    pricingUrl: 'https://www.alibabacloud.com/help/en/model-studio/model-pricing',
    description: t('Alibaba Cloud’s flagship Qwen3 tier for the hardest text-generation and agent-style tasks.', '阿里雲的旗艦 Qwen3 層級，面向高難度文字生成與 agent 式任務。'),
    modalities: ['text'],
    modalityProfile: { input: ['text'], output: ['text', 'json'] },
    contextWindow: '262,144 tokens',
    pricing: {
      input: '$1.20 / 1M input tokens (≤32K prompts)',
      output: '$6 / 1M output tokens (≤32K prompts)',
      inputUsdPerMillion: '1.20',
      outputUsdPerMillion: '6',
      notes: 'Alibaba Cloud publishes tiered pricing above 32K input tokens, up to a 252K-token request band.',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: true, remoteMcp: false, codeExecution: true },
    overallScore: 88,
    scores: { capability: 91, useCaseFitness: 89, costEfficiency: 83, speed: 82, reliability: 86, agentReadiness: 89, ecosystem: 80 },
    bestUseCases: ['coding', 'agent-automation'],
    worksWith: ['Alibaba Cloud Model Studio', 'Qwen agent flows', 'search-enabled reasoning'],
    tags: ['flagship', 'reasoning', 'qwen'],
    strengths: [
      t('Good flagship coverage for the commercial Qwen family, which was previously missing from live catalog.', '補上原本 live catalog 缺的商業 Qwen 旗艦覆蓋。'),
      t('Official docs explicitly position it for complex tasks and search-agent workflows.', '官方文件明確把它定位在複雜任務與 search-agent 工作流。'),
    ],
    caveats: [
      t('Pricing is tiered by prompt length, so simple headline comparisons can hide cost jumps.', '定價會隨 prompt 長度分層，單看 headline 價格可能忽略成本跳升。'),
      t('Global ecosystem gravity is still smaller than the biggest US API vendors.', '全球生態引力仍小於最大型的美系 API 供應商。'),
    ],
    updatedAt: EXPANDED_VERIFIED_AT,
    sourceRefs: [
      officialSource('Alibaba Cloud Model Studio', 'https://www.alibabacloud.com/product/model-studio', 'official-site', EXPANDED_VERIFIED_AT, ['officialUrl']),
      officialSource('Alibaba Cloud supported models overview', 'https://www.alibabacloud.com/help/en/model-studio/models', 'official-docs', EXPANDED_VERIFIED_AT, ['summary', 'description', 'contextWindow', 'toolSupport']),
      officialSource('Alibaba Cloud model pricing', 'https://www.alibabacloud.com/help/en/model-studio/model-pricing', 'pricing-page', EXPANDED_VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('Qwen3-Max'),
    ],
  }),
  defineModel({
    slug: 'qwen3-5-plus',
    name: 'Qwen3.5-Plus',
    providerId: 'alibaba-cloud',
    family: 'Qwen3.5',
    officialUrl: 'https://www.alibabacloud.com/product/model-studio',
    docsUrl: 'https://www.alibabacloud.com/help/en/model-studio/models',
    pricingUrl: 'https://www.alibabacloud.com/help/en/model-studio/model-pricing',
    description: t('Alibaba Cloud’s balanced Qwen3.5 tier that adds text, image, and video inputs at a much lower price than flagship Qwen3-Max.', '阿里雲較均衡的 Qwen3.5 層級，支援文字、圖片與影片輸入，價格明顯低於旗艦 Qwen3-Max。'),
    modalities: ['text', 'image', 'video'],
    modalityProfile: { input: ['text', 'image', 'video'], output: ['text', 'json'] },
    contextWindow: '1M tokens',
    pricing: {
      input: '$0.40 / 1M input tokens (≤256K prompts)',
      output: '$2.40 / 1M output tokens (≤256K prompts)',
      inputUsdPerMillion: '0.40',
      outputUsdPerMillion: '2.40',
      notes: 'Alibaba Cloud lists a higher tier above 256K input tokens.',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 87,
    scores: { capability: 86, useCaseFitness: 89, costEfficiency: 91, speed: 90, reliability: 85, agentReadiness: 86, ecosystem: 80 },
    bestUseCases: ['research', 'agent-automation'],
    worksWith: ['Alibaba Cloud Model Studio', 'multimodal Qwen apps', 'cost-aware assistant tiers'],
    tags: ['multimodal', 'balanced', 'qwen'],
    strengths: [
      t('Covers the practical middle of the commercial Qwen family with multimodal support.', '補上商業 Qwen 家族中最實用的中段多模態層。'),
      t('Strong price/performance story relative to the flagship model.', '相較旗艦層有不錯的價格效能故事。'),
    ],
    caveats: [
      t('Official docs are less familiar to many English-first buyers than US vendor docs.', '對很多以英文市場為主的買家來說，官方文件熟悉度較低。'),
      t('Some capability details are presented across multiple Alibaba docs rather than one compact page.', '部分能力資訊分散在多份阿里文件中，不像某些供應商集中在單頁。'),
    ],
    updatedAt: EXPANDED_VERIFIED_AT,
    sourceRefs: [
      officialSource('Alibaba Cloud Model Studio', 'https://www.alibabacloud.com/product/model-studio', 'official-site', EXPANDED_VERIFIED_AT, ['officialUrl']),
      officialSource('Alibaba Cloud supported models overview', 'https://www.alibabacloud.com/help/en/model-studio/models', 'official-docs', EXPANDED_VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile', 'contextWindow']),
      officialSource('Alibaba Cloud model pricing', 'https://www.alibabacloud.com/help/en/model-studio/model-pricing', 'pricing-page', EXPANDED_VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('Qwen3.5-Plus'),
    ],
  }),
  defineModel({
    slug: 'qwen3-vl-plus',
    name: 'Qwen3-VL-Plus',
    providerId: 'alibaba-cloud',
    family: 'Qwen3-VL',
    officialUrl: 'https://www.alibabacloud.com/product/model-studio',
    docsUrl: 'https://www.alibabacloud.com/help/en/model-studio/models',
    pricingUrl: 'https://www.alibabacloud.com/help/en/model-studio/model-pricing',
    description: t('Alibaba Cloud’s higher-end Qwen3 vision-language tier for multimodal understanding with thinking and non-thinking modes.', '阿里雲較高階的 Qwen3 視覺語言層，支援 thinking / non-thinking 模式的多模態理解。'),
    modalities: ['text', 'image'],
    modalityProfile: { input: ['text', 'image'], output: ['text', 'json'] },
    contextWindow: '262,144 tokens',
    maxOutputTokens: '32,768 tokens',
    pricing: {
      input: '$0.20 / 1M input tokens (≤32K prompts)',
      output: '$1.60 / 1M output tokens (≤32K prompts)',
      inputUsdPerMillion: '0.20',
      outputUsdPerMillion: '1.60',
      notes: 'Alibaba Cloud lists higher price bands above 32K input tokens.',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 85,
    scores: { capability: 86, useCaseFitness: 88, costEfficiency: 90, speed: 84, reliability: 84, agentReadiness: 84, ecosystem: 79 },
    bestUseCases: ['research', 'agent-automation'],
    worksWith: ['Alibaba Cloud Model Studio', 'multimodal document flows', 'vision-heavy assistants'],
    tags: ['vision-language', 'multimodal', 'qwen'],
    strengths: [
      t('Adds a clean commercial Qwen vision-language representative to the live set.', '讓 live set 補上一個清楚的商業 Qwen 視覺語言代表。'),
      t('Official docs publish both context window and tiered multimodal pricing.', '官方文件有公開上下文視窗與分層多模態定價。'),
    ],
    caveats: [
      t('Vision pricing is tiered, so simple cost labels still need nuance.', '視覺模型定價同樣分層，簡化標籤仍需要補充說明。'),
      t('Less ecosystem mindshare than Google or OpenAI multimodal defaults.', '生態心智份額仍低於 Google 或 OpenAI 的多模態預設。'),
    ],
    updatedAt: EXPANDED_VERIFIED_AT,
    sourceRefs: [
      officialSource('Alibaba Cloud Model Studio', 'https://www.alibabacloud.com/product/model-studio', 'official-site', EXPANDED_VERIFIED_AT, ['officialUrl']),
      officialSource('Alibaba Cloud supported models overview', 'https://www.alibabacloud.com/help/en/model-studio/models', 'official-docs', EXPANDED_VERIFIED_AT, ['summary', 'description', 'modalities', 'modalityProfile', 'contextWindow', 'maxOutputTokens']),
      officialSource('Alibaba Cloud model pricing', 'https://www.alibabacloud.com/help/en/model-studio/model-pricing', 'pricing-page', EXPANDED_VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('Qwen3-VL-Plus'),
    ],
  }),
  defineModel({
    slug: 'deepseek-chat-v3-2',
    name: 'deepseek-chat (DeepSeek-V3.2)',
    providerId: 'deepseek',
    family: 'DeepSeek-V3.2',
    officialUrl: 'https://www.deepseek.com/',
    docsUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
    pricingUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
    description: t('DeepSeek’s non-thinking API SKU mapped to the DeepSeek-V3.2 model version.', 'DeepSeek 的非 thinking API SKU，對應 DeepSeek-V3.2 模型版本。'),
    modalities: ['text'],
    modalityProfile: { input: ['text'], output: ['text', 'json'] },
    contextWindow: '128K tokens',
    maxOutputTokens: '8K tokens max',
    pricing: {
      input: '$0.28 / 1M input tokens (cache miss)',
      output: '$0.42 / 1M output tokens',
      inputUsdPerMillion: '0.28',
      outputUsdPerMillion: '0.42',
      notes: 'DeepSeek also lists lower cache-hit pricing.',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 86,
    scores: { capability: 84, useCaseFitness: 86, costEfficiency: 96, speed: 92, reliability: 82, agentReadiness: 84, ecosystem: 80 },
    bestUseCases: ['coding', 'agent-automation'],
    worksWith: ['DeepSeek API', 'routing layers', 'budget coding flows'],
    tags: ['budget', 'coding', 'api-sku'],
    strengths: [
      t('Very aggressive API pricing for practical text workloads.', '在實務文字工作負載上有非常激進的 API 定價。'),
      t('Useful as a cheaper mainline or fallback model in routed stacks.', '適合作為 routed stack 裡較便宜的主線或 fallback。'),
    ],
    caveats: [
      t('API SKU naming differs from the broader model-family branding.', 'API SKU 命名和外部模型家族品牌名稱不完全一致。'),
      t('Some enterprises will still prefer vendors with broader compliance posture.', '部分企業仍可能偏好合規姿態更完整的供應商。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('DeepSeek official', 'https://www.deepseek.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('DeepSeek models and pricing', 'https://api-docs.deepseek.com/quick_start/pricing', 'official-docs', VERIFIED_AT, ['summary', 'description', 'contextWindow', 'maxOutputTokens', 'toolSupport', 'pricing', 'pricingUrl']),
      review('deepseek-chat (DeepSeek-V3.2)'),
    ],
  }),
  defineModel({
    slug: 'deepseek-reasoner-v3-2',
    name: 'deepseek-reasoner (DeepSeek-V3.2)',
    providerId: 'deepseek',
    family: 'DeepSeek-V3.2',
    officialUrl: 'https://www.deepseek.com/',
    docsUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
    pricingUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
    description: t('DeepSeek’s thinking API SKU mapped to the DeepSeek-V3.2 model version.', 'DeepSeek 的 thinking API SKU，對應 DeepSeek-V3.2 模型版本。'),
    modalities: ['text'],
    modalityProfile: { input: ['text'], output: ['text', 'json'] },
    contextWindow: '128K tokens',
    maxOutputTokens: '64K tokens max',
    pricing: {
      input: '$0.28 / 1M input tokens (cache miss)',
      output: '$0.42 / 1M output tokens',
      inputUsdPerMillion: '0.28',
      outputUsdPerMillion: '0.42',
      notes: 'DeepSeek lists the same published token rates with a larger reasoning-oriented output budget.',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 87,
    scores: { capability: 87, useCaseFitness: 86, costEfficiency: 95, speed: 84, reliability: 82, agentReadiness: 85, ecosystem: 80 },
    bestUseCases: ['coding', 'research'],
    worksWith: ['DeepSeek API', 'longer reasoning flows', 'budget research stacks'],
    tags: ['reasoning', 'budget', 'api-sku'],
    strengths: [
      t('Keeps DeepSeek’s price profile while exposing a reasoning-oriented API tier.', '在維持 DeepSeek 價格優勢的同時，提供偏推理導向的 API 層。'),
      t('Appealing for teams that need cheaper deep-thinking capacity.', '對需要更便宜深度思考能力的團隊很有吸引力。'),
    ],
    caveats: [
      t('Vendor and ecosystem maturity still trail the largest hyperscalers.', '供應商與生態成熟度仍落後於最大型雲端供應商。'),
      t('Operational posture should be reviewed carefully for enterprise adoption.', '若要企業導入，仍應仔細檢查營運與合規姿態。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('DeepSeek official', 'https://www.deepseek.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('DeepSeek models and pricing', 'https://api-docs.deepseek.com/quick_start/pricing', 'official-docs', VERIFIED_AT, ['summary', 'description', 'contextWindow', 'maxOutputTokens', 'toolSupport', 'pricing', 'pricingUrl']),
      review('deepseek-reasoner (DeepSeek-V3.2)'),
    ],
  }),
  defineModel({
    slug: 'command-a',
    name: 'Command A',
    providerId: 'cohere',
    family: 'Command',
    officialUrl: 'https://cohere.com/',
    docsUrl: 'https://docs.cohere.com/docs/command-a',
    pricingUrl: 'https://docs.cohere.com/docs/command-a',
    description: t('Cohere’s performant enterprise model for tool use, RAG, agents, and multilingual workflows.', 'Cohere 面向企業的高性能模型，適合工具使用、RAG、agent 與多語工作流。'),
    modalities: ['text'],
    modalityProfile: { input: ['text'], output: ['text', 'json'] },
    contextWindow: '256K tokens',
    pricing: {
      input: '$2.50 / 1M input tokens',
      output: '$10 / 1M output tokens',
      inputUsdPerMillion: '2.50',
      outputUsdPerMillion: '10',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 88,
    scores: { capability: 89, useCaseFitness: 90, costEfficiency: 84, speed: 84, reliability: 88, agentReadiness: 90, ecosystem: 85 },
    bestUseCases: ['agent-automation', 'research'],
    worksWith: ['Cohere API', 'RAG pipelines', 'enterprise search'],
    tags: ['enterprise', 'rag', 'multilingual'],
    strengths: [
      t('Strong enterprise-facing positioning around RAG and tool use.', '在企業 RAG 與工具使用上定位清楚。'),
      t('Long context helps with knowledge-heavy workflows.', '長上下文對知識密集型工作流有幫助。'),
    ],
    caveats: [
      t('Ecosystem mindshare is smaller than OpenAI or Anthropic.', '生態心智份額小於 OpenAI 與 Anthropic。'),
      t('Some teams may prefer more standardized agent examples elsewhere.', '部分團隊可能更偏好其他生態較標準化的 agent 範例。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Cohere official', 'https://cohere.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Command A docs', 'https://docs.cohere.com/docs/command-a', 'official-docs', VERIFIED_AT, ['summary', 'description', 'contextWindow', 'toolSupport', 'pricing', 'pricingUrl']),
      review('Command A'),
    ],
  }),
  defineModel({
    slug: 'command-a-reasoning',
    name: 'Command A Reasoning',
    providerId: 'cohere',
    family: 'Command',
    officialUrl: 'https://cohere.com/',
    docsUrl: 'https://docs.cohere.com/docs/command-a-reasoning',
    pricingUrl: 'https://docs.cohere.com/docs/command-a-reasoning',
    description: t('Cohere’s reasoning-oriented Command tier for complex agentic enterprise workflows.', 'Cohere 偏 reasoning 的 Command 層，適合複雜 agent 企業工作流。'),
    modalities: ['text'],
    modalityProfile: { input: ['text'], output: ['text', 'json'] },
    contextWindow: '256K tokens',
    pricing: {
      input: 'Free while rate limits apply',
      output: 'Free while rate limits apply',
      notes: 'Official docs state Command A Reasoning is free for trial and production keys until rate limits are reached.',
    },
    speedCategory: 'Deliberate',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 86,
    scores: { capability: 90, useCaseFitness: 87, costEfficiency: 89, speed: 76, reliability: 84, agentReadiness: 89, ecosystem: 84 },
    bestUseCases: ['agent-automation', 'research'],
    worksWith: ['Cohere API', 'enterprise agents', 'tool-use workflows'],
    tags: ['reasoning', 'enterprise', 'agents'],
    strengths: [
      t('Reasoning-focused variant with strong enterprise task framing.', '推理導向的變體，且企業任務定位明確。'),
      t('The official free-access positioning lowers experimentation risk.', '官方提供的免費使用定位，降低了試驗成本。'),
    ],
    caveats: [
      t('Published pricing posture is unusual and may change.', '官方目前的定價姿態較特殊，後續可能變動。'),
      t('Teams should verify production access expectations before committing.', '在正式投入前，仍應先確認 production 存取條件。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Cohere official', 'https://cohere.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Command A Reasoning docs', 'https://docs.cohere.com/docs/command-a-reasoning', 'official-docs', VERIFIED_AT, ['summary', 'description', 'contextWindow', 'toolSupport', 'pricing', 'pricingUrl']),
      review('Command A Reasoning'),
    ],
  }),
  defineModel({
    slug: 'command-r7b',
    name: 'Command R7B',
    providerId: 'cohere',
    family: 'Command',
    officialUrl: 'https://cohere.com/',
    docsUrl: 'https://docs.cohere.com/docs/command-r7b',
    pricingUrl: 'https://docs.cohere.com/docs/command-r7b',
    description: t('Cohere’s smallest and fastest R-family enterprise model.', 'Cohere R 系列中最小、最快的企業模型。'),
    modalities: ['text'],
    modalityProfile: { input: ['text'], output: ['text', 'json'] },
    contextWindow: '128K tokens',
    pricing: {
      input: '$0.0375 / 1M input tokens',
      output: '$0.15 / 1M output tokens',
      inputUsdPerMillion: '0.0375',
      outputUsdPerMillion: '0.15',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 83,
    scores: { capability: 78, useCaseFitness: 82, costEfficiency: 97, speed: 95, reliability: 84, agentReadiness: 81, ecosystem: 83 },
    bestUseCases: ['agent-automation'],
    worksWith: ['Cohere API', 'classification', 'budget enterprise assistants'],
    tags: ['small-model', 'budget', 'fast'],
    strengths: [
      t('Very compelling price and latency profile.', '價格與延遲表現都很有吸引力。'),
      t('Good choice for enterprise assistants that do not need frontier depth.', '對不需要前沿深度的企業助理來說是好選擇。'),
    ],
    caveats: [
      t('Capability ceiling is lower than larger premium models.', '能力上限低於更大的高階模型。'),
      t('Best used where efficiency matters more than nuance.', '更適合效率優先、而不是細膩理解優先的場景。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Cohere official', 'https://cohere.com/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Command R7B docs', 'https://docs.cohere.com/docs/command-r7b', 'official-docs', VERIFIED_AT, ['summary', 'description', 'pricing', 'pricingUrl']),
      review('Command R7B'),
    ],
  }),
  defineModel({
    slug: 'sonar',
    name: 'Sonar',
    providerId: 'perplexity',
    family: 'Sonar',
    officialUrl: 'https://www.perplexity.ai/',
    docsUrl: 'https://docs.perplexity.ai/docs/sonar/models/sonar',
    pricingUrl: 'https://docs.perplexity.ai/docs/getting-started/pricing',
    description: t('Perplexity’s lightweight search model for quick grounded answers with real-time web search.', 'Perplexity 輕量級搜尋模型，適合快速且有即時網頁依據的回答。'),
    modalities: ['text', 'search'],
    contextWindow: 'Search-context dependent',
    pricing: {
      input: '$1 / 1M input tokens',
      output: '$1 / 1M output tokens',
      inputUsdPerMillion: '1',
      outputUsdPerMillion: '1',
      notes: 'Perplexity also charges request fees by search context size.',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: false, structuredOutput: false, webSearch: true, remoteMcp: false, codeExecution: false },
    overallScore: 85,
    scores: { capability: 80, useCaseFitness: 90, costEfficiency: 91, speed: 94, reliability: 86, agentReadiness: 78, ecosystem: 84 },
    bestUseCases: ['research'],
    worksWith: ['Search-backed answers', 'news monitoring', 'web-grounded assistants'],
    tags: ['search', 'grounded', 'web'],
    strengths: [
      t('Fast grounded answers are the core product strength.', '快速且有根據的回答是核心優勢。'),
      t('Good for teams that care more about answer freshness than raw frontier reasoning.', '適合更重視資訊新鮮度，而非純前沿推理的團隊。'),
    ],
    caveats: [
      t('This is a search-native product tier, not a general-purpose long-context flagship.', '這是 search-native 產品層，不是通用長上下文旗艦模型。'),
      t('Request-fee economics should be reviewed alongside token prices.', '除了 token 價格，也要一併檢查 request fee。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Perplexity official', 'https://www.perplexity.ai/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Sonar model docs', 'https://docs.perplexity.ai/docs/sonar/models/sonar', 'official-docs', VERIFIED_AT, ['summary', 'description', 'toolSupport']),
      officialSource('Perplexity pricing', 'https://docs.perplexity.ai/docs/getting-started/pricing', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('Sonar'),
    ],
  }),
  defineModel({
    slug: 'sonar-pro',
    name: 'Sonar Pro',
    providerId: 'perplexity',
    family: 'Sonar',
    officialUrl: 'https://www.perplexity.ai/',
    docsUrl: 'https://docs.perplexity.ai/docs/sonar/models/sonar-pro',
    pricingUrl: 'https://docs.perplexity.ai/docs/getting-started/pricing',
    description: t('Perplexity’s advanced search model with deeper content understanding and enhanced search accuracy.', 'Perplexity 進階搜尋模型，提供更深內容理解與更高搜尋準確度。'),
    modalities: ['text', 'search'],
    contextWindow: 'Search-context dependent',
    pricing: {
      input: '$3 / 1M input tokens',
      output: '$15 / 1M output tokens',
      inputUsdPerMillion: '3',
      outputUsdPerMillion: '15',
      notes: 'Request fees vary by search context size and Pro Search mode.',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: false, structuredOutput: false, webSearch: true, remoteMcp: false, codeExecution: false },
    overallScore: 87,
    scores: { capability: 86, useCaseFitness: 92, costEfficiency: 78, speed: 86, reliability: 88, agentReadiness: 80, ecosystem: 84 },
    bestUseCases: ['research'],
    worksWith: ['research copilots', 'search-grounded Q&A', 'news workflows'],
    tags: ['search', 'research', 'grounded'],
    strengths: [
      t('Better fit for more complex search-heavy questions than base Sonar.', '比基礎 Sonar 更適合複雜的搜尋導向問題。'),
      t('Good middle tier for research stacks that need freshness and depth.', '對需要兼顧資訊新鮮度與深度的 research stack 來說很適中。'),
    ],
    caveats: [
      t('Pricing jumps meaningfully over base Sonar.', '價格相較基礎 Sonar 有明顯提升。'),
      t('Still a search-native product rather than a broad general foundation model.', '本質上仍是 search-native 產品，而不是廣義基礎模型。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Perplexity official', 'https://www.perplexity.ai/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Sonar Pro model docs', 'https://docs.perplexity.ai/docs/sonar/models/sonar-pro', 'official-docs', VERIFIED_AT, ['summary', 'description', 'toolSupport']),
      officialSource('Perplexity pricing', 'https://docs.perplexity.ai/docs/getting-started/pricing', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('Sonar Pro'),
    ],
  }),
  defineModel({
    slug: 'sonar-reasoning-pro',
    name: 'Sonar Reasoning Pro',
    providerId: 'perplexity',
    family: 'Sonar',
    officialUrl: 'https://www.perplexity.ai/',
    docsUrl: 'https://docs.perplexity.ai/docs/sonar/models/sonar-reasoning-pro',
    pricingUrl: 'https://docs.perplexity.ai/docs/getting-started/pricing',
    description: t('Perplexity’s reasoning-enhanced search model for harder grounded questions.', 'Perplexity 強化 reasoning 的搜尋模型，適合較難且需要 grounding 的問題。'),
    modalities: ['text', 'search'],
    contextWindow: 'Search-context dependent',
    pricing: {
      input: '$2 / 1M input tokens',
      output: '$8 / 1M output tokens',
      inputUsdPerMillion: '2',
      outputUsdPerMillion: '8',
      notes: 'Request fees vary by search context size.',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: false, structuredOutput: false, webSearch: true, remoteMcp: false, codeExecution: false },
    overallScore: 88,
    scores: { capability: 88, useCaseFitness: 92, costEfficiency: 83, speed: 82, reliability: 88, agentReadiness: 80, ecosystem: 84 },
    bestUseCases: ['research'],
    worksWith: ['deeper search workflows', 'analysis assistants', 'research copilots'],
    tags: ['reasoning', 'search', 'analysis'],
    strengths: [
      t('Better fit when grounded research also needs explicit reasoning.', '當 grounded research 同時需要更明確推理時會更有優勢。'),
      t('Price sits below Sonar Pro on token costs.', 'token 成本低於 Sonar Pro。'),
    ],
    caveats: [
      t('Still inherits search-context pricing complexity.', '仍然承接 search-context 的定價複雜性。'),
      t('Not positioned as a universal coding or automation default.', '不是通用 coding 或 automation 的預設選項。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Perplexity official', 'https://www.perplexity.ai/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Sonar Reasoning Pro model docs', 'https://docs.perplexity.ai/docs/sonar/models/sonar-reasoning-pro', 'official-docs', VERIFIED_AT, ['summary', 'description', 'toolSupport']),
      officialSource('Perplexity pricing', 'https://docs.perplexity.ai/docs/getting-started/pricing', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('Sonar Reasoning Pro'),
    ],
  }),
  defineModel({
    slug: 'sonar-deep-research',
    name: 'Sonar Deep Research',
    providerId: 'perplexity',
    family: 'Sonar',
    officialUrl: 'https://www.perplexity.ai/',
    docsUrl: 'https://docs.perplexity.ai/docs/sonar/models/sonar-deep-research',
    pricingUrl: 'https://docs.perplexity.ai/docs/getting-started/pricing',
    description: t('Perplexity’s deepest research tier with citation and search-query pricing components.', 'Perplexity 最深度的研究層，包含 citation 與 search-query 定價元件。'),
    modalities: ['text', 'search'],
    contextWindow: 'Search-context dependent',
    pricing: {
      input: '$2 / 1M input tokens',
      output: '$8 / 1M output tokens',
      inputUsdPerMillion: '2',
      outputUsdPerMillion: '8',
      notes: 'Perplexity also charges citation tokens, reasoning tokens, and search-query fees.',
    },
    speedCategory: 'Deliberate',
    toolSupport: { functionCalling: false, structuredOutput: false, webSearch: true, remoteMcp: false, codeExecution: false },
    overallScore: 86,
    scores: { capability: 89, useCaseFitness: 94, costEfficiency: 73, speed: 70, reliability: 87, agentReadiness: 81, ecosystem: 84 },
    bestUseCases: ['research'],
    worksWith: ['deep research workflows', 'citation-heavy reports', 'analyst assistants'],
    tags: ['deep-research', 'citations', 'search'],
    strengths: [
      t('Built specifically for deeper research and citation-heavy output.', '就是為更深入研究與 citation 密集輸出而設計。'),
      t('Makes source-backed reporting more explicit than generic chat models.', '比一般聊天模型更明確地支援來源導向報告。'),
    ],
    caveats: [
      t('The pricing model has multiple moving parts and needs careful review.', '定價模型有多個元件，必須仔細檢查。'),
      t('Latency and cost profile are less suitable for lightweight interactive use.', '延遲與成本輪廓不太適合輕量互動場景。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Perplexity official', 'https://www.perplexity.ai/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Sonar Deep Research docs', 'https://docs.perplexity.ai/docs/sonar/models/sonar-deep-research', 'official-docs', VERIFIED_AT, ['summary', 'description', 'toolSupport']),
      officialSource('Perplexity pricing', 'https://docs.perplexity.ai/docs/getting-started/pricing', 'pricing-page', VERIFIED_AT, ['pricing', 'pricingUrl']),
      review('Sonar Deep Research'),
    ],
  }),
  defineModel({
    slug: 'mistral-large-3',
    name: 'Mistral Large 3',
    providerId: 'mistral',
    family: 'Mistral Large',
    officialUrl: 'https://mistral.ai/',
    docsUrl: 'https://docs.mistral.ai/models/mistral-large-3-25-12',
    pricingUrl: 'https://docs.mistral.ai/models/mistral-large-3-25-12',
    description: t('Mistral’s open-weight multimodal flagship with a Mixture-of-Experts architecture.', 'Mistral 的 open-weight 多模態旗艦模型，採用 Mixture-of-Experts 架構。'),
    modalities: ['text', 'image'],
    modalityProfile: { input: ['text', 'image'], output: ['text', 'json'] },
    contextWindow: '256K tokens',
    pricing: {
      input: '$0.50 / 1M input tokens',
      output: '$1.50 / 1M output tokens',
      inputUsdPerMillion: '0.50',
      outputUsdPerMillion: '1.50',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 89,
    scores: { capability: 90, useCaseFitness: 89, costEfficiency: 91, speed: 83, reliability: 86, agentReadiness: 88, ecosystem: 84 },
    bestUseCases: ['coding', 'research'],
    worksWith: ['Mistral API', 'self-hosted evaluation', 'document workflows'],
    tags: ['open-weights', 'multimodal', 'moe'],
    strengths: [
      t('Open-weight positioning makes it strategically interesting for some teams.', 'open-weight 定位對部分團隊很有策略吸引力。'),
      t('Price-performance looks strong relative to many premium closed models.', '相對不少高價封閉模型，價格效能很不錯。'),
    ],
    caveats: [
      t('Tooling ecosystem is still smaller than the biggest US vendors.', '工具生態仍小於最大的美系供應商。'),
      t('Teams should validate downstream hosting and maintenance assumptions.', '若要落地，仍應確認後續 hosting 與維運假設。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Mistral official', 'https://mistral.ai/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Mistral Large 3 docs', 'https://docs.mistral.ai/models/mistral-large-3-25-12', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'contextWindow', 'pricing', 'pricingUrl', 'toolSupport']),
      review('Mistral Large 3'),
    ],
  }),
  defineModel({
    slug: 'mistral-medium-3',
    name: 'Mistral Medium 3',
    providerId: 'mistral',
    family: 'Mistral Medium',
    officialUrl: 'https://mistral.ai/',
    docsUrl: 'https://docs.mistral.ai/models/mistral-medium-3-25-05',
    pricingUrl: 'https://docs.mistral.ai/models/mistral-medium-3-25-05',
    description: t('Mistral’s mid-tier enterprise model with strong function calling and agent-oriented features.', 'Mistral 中階企業模型，具備不錯的 function calling 與 agent 導向功能。'),
    modalities: ['text', 'image'],
    modalityProfile: { input: ['text', 'image'], output: ['text', 'json'] },
    contextWindow: '128K tokens',
    pricing: {
      input: '$0.40 / 1M input tokens',
      output: '$2 / 1M output tokens',
      inputUsdPerMillion: '0.40',
      outputUsdPerMillion: '2',
    },
    speedCategory: 'Balanced',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 86,
    scores: { capability: 86, useCaseFitness: 86, costEfficiency: 90, speed: 84, reliability: 84, agentReadiness: 87, ecosystem: 83 },
    bestUseCases: ['coding', 'agent-automation'],
    worksWith: ['Mistral API', 'agent toolchains', 'document Q&A'],
    tags: ['mid-tier', 'agents', 'function-calling'],
    strengths: [
      t('Looks like a practical middle tier for cost-aware teams.', '看起來很像成本敏感團隊可用的實務中階層。'),
      t('Official docs expose agent and structured-output features clearly.', '官方文件對 agent 與 structured output 功能描述清楚。'),
    ],
    caveats: [
      t('Less ecosystem gravity than the biggest model platforms.', '生態引力仍低於最大模型平台。'),
      t('Teams should test model behavior carefully on their own evals.', '仍應在自家 eval 上仔細測試模型行為。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Mistral official', 'https://mistral.ai/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Mistral Medium 3 docs', 'https://docs.mistral.ai/models/mistral-medium-3-25-05', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'contextWindow', 'pricing', 'pricingUrl', 'toolSupport']),
      review('Mistral Medium 3'),
    ],
  }),
  defineModel({
    slug: 'mistral-small-3-2',
    name: 'Mistral Small 3.2',
    providerId: 'mistral',
    family: 'Mistral Small',
    officialUrl: 'https://mistral.ai/',
    docsUrl: 'https://docs.mistral.ai/models/mistral-small-3-2-25-06',
    pricingUrl: 'https://docs.mistral.ai/models/mistral-small-3-2-25-06',
    description: t('Mistral’s lower-cost small model for efficient production use.', 'Mistral 較低成本的小模型，適合高效率 production 使用。'),
    modalities: ['text', 'image'],
    modalityProfile: { input: ['text', 'image'], output: ['text', 'json'] },
    contextWindow: '128K tokens',
    pricing: {
      input: '$0.10 / 1M input tokens',
      output: '$0.30 / 1M output tokens',
      inputUsdPerMillion: '0.10',
      outputUsdPerMillion: '0.30',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 82,
    scores: { capability: 77, useCaseFitness: 81, costEfficiency: 96, speed: 93, reliability: 82, agentReadiness: 80, ecosystem: 82 },
    bestUseCases: ['agent-automation'],
    worksWith: ['Mistral API', 'classification', 'routing layers'],
    tags: ['small-model', 'budget', 'efficient'],
    strengths: [
      t('Strong efficiency tier inside the Mistral stack.', '在 Mistral stack 裡是很強的效率層。'),
      t('Good candidate for routing, extraction, and lighter assistants.', '適合 routing、擷取與較輕量助理。'),
    ],
    caveats: [
      t('Limited headroom for advanced reasoning.', '進階推理的能力空間有限。'),
      t('Best used with escalation paths to larger models.', '最好搭配升級到更大模型的路徑。'),
    ],
    updatedAt: VERIFIED_AT,
    sourceRefs: [
      officialSource('Mistral official', 'https://mistral.ai/', 'official-site', VERIFIED_AT, ['officialUrl']),
      officialSource('Mistral Small 3.2 docs', 'https://docs.mistral.ai/models/mistral-small-3-2-25-06', 'official-docs', VERIFIED_AT, ['summary', 'description', 'modalities', 'contextWindow', 'pricing', 'pricingUrl', 'toolSupport']),
      review('Mistral Small 3.2'),
    ],
  }),
  defineModel({
    slug: 'codestral-25-08',
    name: 'Codestral 25.08',
    providerId: 'mistral',
    family: 'Codestral',
    officialUrl: 'https://mistral.ai/',
    docsUrl: 'https://docs.mistral.ai/models/codestral-25-08',
    pricingUrl: 'https://docs.mistral.ai/models/codestral-25-08',
    description: t('Mistral’s specialist coding model for low-latency code generation and fill-in-the-middle workflows.', 'Mistral 專門面向 coding 的模型，適合低延遲程式生成與 fill-in-the-middle 工作流。'),
    modalities: ['text'],
    modalityProfile: { input: ['text'], output: ['text', 'json'] },
    contextWindow: '128K tokens',
    pricing: {
      input: '$0.30 / 1M input tokens',
      output: '$0.90 / 1M output tokens',
      inputUsdPerMillion: '0.30',
      outputUsdPerMillion: '0.90',
    },
    speedCategory: 'Fast',
    toolSupport: { functionCalling: true, structuredOutput: true, webSearch: false, remoteMcp: false, codeExecution: false },
    overallScore: 87,
    scores: { capability: 88, useCaseFitness: 92, costEfficiency: 90, speed: 93, reliability: 84, agentReadiness: 89, ecosystem: 82 },
    bestUseCases: ['coding', 'agent-automation'],
    worksWith: ['Mistral API', 'code completion', 'FIM editors'],
    tags: ['coding', 'fill-in-the-middle', 'low-latency'],
    strengths: [
      t('Adds a purpose-built coding specialist instead of only general Mistral models.', '不只放通用 Mistral 模型，也補上一個專門的 coding specialist。'),
      t('Official docs clearly call out low-latency code generation and FIM workflows.', '官方文件明確標出低延遲 code generation 與 FIM 工作流。'),
    ],
    caveats: [
      t('This is a narrower coding-focused model, not the best all-purpose research tier.', '它是較窄的 coding 導向模型，不是最佳的通用研究層。'),
      t('Teams still need their own evals for repo-specific coding behavior.', '團隊仍要用自家 eval 驗證在特定 codebase 的表現。'),
    ],
    updatedAt: EXPANDED_VERIFIED_AT,
    sourceRefs: [
      officialSource('Mistral official', 'https://mistral.ai/', 'official-site', EXPANDED_VERIFIED_AT, ['officialUrl']),
      officialSource('Codestral 25.08 docs', 'https://docs.mistral.ai/models/codestral-25-08', 'official-docs', EXPANDED_VERIFIED_AT, ['summary', 'description', 'contextWindow', 'pricing', 'pricingUrl', 'toolSupport']),
      review('Codestral 25.08'),
    ],
  }),
];
