import { defineSkill, manualReviewSource, officialSource } from './factories';

const VERIFIED_AT = '2026-04-09T08:00:00.000Z';
const EXTERNAL_VALIDATION_AT = '2026-04-10T01:45:00.000Z';

const t = (en: string, zhTW: string) => ({ en, 'zh-TW': zhTW });

const editorialFields = ['bestFor', 'worksWith', 'capabilities', 'permissionProfile', 'overallScore'];

function review(name: string, verifiedAt = VERIFIED_AT) {
  return manualReviewSource(`${name} VerdictLens review`, verifiedAt, editorialFields, 'Editorial shortlist guidance is intentionally separated from official product facts.');
}

function skillSources(name: string, input: {
  officialUrl?: string;
  docsUrl?: string;
  repoUrl?: string;
  registryUrl?: string;
  coreFields?: string[];
}, verifiedAt = VERIFIED_AT) {
  return [
    ...(input.docsUrl ? [officialSource(`${name} docs`, input.docsUrl, 'official-docs', verifiedAt, input.coreFields ?? ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'])] : []),
    ...(input.repoUrl ? [officialSource(`${name} repo`, input.repoUrl, 'github', verifiedAt, ['repoUrl'])] : []),
    ...(input.registryUrl ? [officialSource(`${name} registry`, input.registryUrl, 'official-registry', verifiedAt, ['registryUrl'])] : []),
    ...(input.officialUrl ? [officialSource(`${name} official`, input.officialUrl, 'official-site', verifiedAt, ['officialUrl'])] : []),
    review(name, verifiedAt),
  ];
}

export const skills = [
  defineSkill({
    slug: 'codex-cli',
    name: 'Codex CLI',
    providerId: 'openai',
    categoryId: 'coding-devtools',
    subCategory: 'CLI coding agent',
    skillType: 'coding',
    officialUrl: 'https://openai.com/',
    docsUrl: 'https://developers.openai.com/codex/cli/',
    repoUrl: 'https://github.com/openai/codex',
    preferredSourceUrl: 'https://developers.openai.com/codex/cli/',
    officialSourceLabel: 'OpenAI docs',
    description: t('OpenAI’s terminal-first coding agent for editing code, running commands, and agentic development loops.', 'OpenAI 的終端優先 coding agent，可編輯程式、執行指令並進行 agent 式開發迴圈。'),
    supportedProviderIds: ['openai'],
    installDifficulty: 'Easy',
    utilityScore: 93,
    compatibilityScore: 84,
    reliabilityScore: 90,
    docsScore: 90,
    adoptionScore: 88,
    safetyMaintenanceScore: 83,
    overallScore: 90,
    bestUseCases: ['coding'],
    deployment: 'local',
    installMethod: 'npm',
    supportedHosts: ['CLI', 'local workstation'],
    capabilities: ['code editing', 'terminal execution', 'repo-aware workflows', 'patch generation'],
    auth: { type: 'api-key', notes: 'OpenAI account / API auth.' },
    permissionProfile: { level: 'high', notes: 'Can read and modify local repositories and run commands.' },
    worksWith: ['GPT-5', 'GPT-5 mini', 'GitHub'],
    tags: ['coding', 'cli', 'agent'],
    strengths: [t('Tight CLI loop for code-centric work.', '很適合 code-centric 工作的 CLI 迴圈。'), t('Natural fit for repo-based engineering tasks.', '很適合 repo 型工程任務。')],
    caveats: [t('High local permissions need operator discipline.', '本地權限高，需要操作紀律。'), t('Mostly optimized for developer workflows.', '主要仍偏向開發者工作流。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Codex CLI', {
      officialUrl: 'https://openai.com/',
      docsUrl: 'https://developers.openai.com/codex/cli/',
      repoUrl: 'https://github.com/openai/codex',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'claude-code',
    name: 'Claude Code',
    providerId: 'anthropic',
    categoryId: 'coding-devtools',
    subCategory: 'CLI coding agent',
    skillType: 'coding',
    officialUrl: 'https://www.anthropic.com/',
    docsUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
    preferredSourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
    officialSourceLabel: 'Anthropic docs',
    description: t('Anthropic’s terminal coding agent for repository work, refactors, debugging, and code generation.', 'Anthropic 的終端 coding agent，適合 repo 工作、重構、debug 與程式生成。'),
    supportedProviderIds: ['anthropic'],
    installDifficulty: 'Easy',
    utilityScore: 92,
    compatibilityScore: 82,
    reliabilityScore: 90,
    docsScore: 91,
    adoptionScore: 89,
    safetyMaintenanceScore: 82,
    overallScore: 89,
    bestUseCases: ['coding'],
    deployment: 'local',
    installMethod: 'npm',
    supportedHosts: ['CLI', 'local workstation'],
    capabilities: ['repo-aware coding', 'debugging', 'refactors', 'terminal workflows'],
    auth: { type: 'api-key', notes: 'Anthropic account / API auth.' },
    permissionProfile: { level: 'high', notes: 'Can inspect and modify code and run commands locally.' },
    worksWith: ['Claude Sonnet 4.6', 'Claude Opus 4.6', 'GitHub'],
    tags: ['coding', 'cli', 'anthropic'],
    strengths: [t('Strong fit for code review and refactor-heavy sessions.', '很適合 code review 與重構密集工作。'), t('Part of Anthropic’s broader MCP-friendly ecosystem.', '屬於 Anthropic 更大的 MCP 友善生態。')],
    caveats: [t('Local command execution still needs careful controls.', '本地指令執行仍需要審慎控管。'), t('Mostly centered on Anthropic-native workflows.', '主要仍以 Anthropic 原生工作流為中心。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Claude Code', {
      officialUrl: 'https://www.anthropic.com/',
      docsUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'langgraph',
    name: 'LangGraph',
    providerId: 'any',
    categoryId: 'agent-frameworks',
    subCategory: 'Graph orchestration',
    skillType: 'workflow',
    officialUrl: 'https://www.langchain.com/langgraph',
    docsUrl: 'https://langchain-ai.github.io/langgraph/',
    repoUrl: 'https://github.com/langchain-ai/langgraph',
    preferredSourceUrl: 'https://langchain-ai.github.io/langgraph/',
    officialSourceLabel: 'LangGraph docs',
    description: t('A stateful graph orchestration framework for long-running agents and controllable multi-step workflows.', '用於長時間運行 agents 與可控多步驟流程的有狀態 graph 編排框架。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'deepseek', 'mistral', 'cohere', 'perplexity', 'local'],
    installDifficulty: 'Moderate',
    utilityScore: 92,
    compatibilityScore: 94,
    reliabilityScore: 88,
    docsScore: 88,
    adoptionScore: 89,
    safetyMaintenanceScore: 85,
    overallScore: 90,
    bestUseCases: ['agent-automation', 'coding'],
    deployment: 'hybrid',
    installMethod: 'pip',
    supportedHosts: ['Python apps', 'APIs', 'workers'],
    capabilities: ['stateful orchestration', 'agent graphs', 'human-in-the-loop', 'durable execution'],
    auth: { type: 'none' },
    permissionProfile: { level: 'medium', notes: 'Framework-level; actual risk depends on attached tools.' },
    worksWith: ['OpenAI', 'Anthropic', 'Google', 'MCP servers'],
    tags: ['framework', 'graphs', 'agents'],
    strengths: [t('Excellent for explicit, inspectable multi-step flows.', '很適合需要明確、可檢查的多步驟流程。'), t('Works well when teams want control rather than magic.', '適合想要控制權而不是黑盒魔法的團隊。')],
    caveats: [t('Adds orchestration complexity.', '會引入編排複雜度。'), t('Overkill for simple single-call apps.', '對單次呼叫型 app 可能太重。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('LangGraph', {
      officialUrl: 'https://www.langchain.com/langgraph',
      docsUrl: 'https://langchain-ai.github.io/langgraph/',
      repoUrl: 'https://github.com/langchain-ai/langgraph',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'supportedProviderIds'],
    }),
  }),
  defineSkill({
    slug: 'langchain',
    name: 'LangChain',
    providerId: 'any',
    categoryId: 'agent-frameworks',
    subCategory: 'LLM app framework',
    skillType: 'workflow',
    officialUrl: 'https://www.langchain.com/',
    docsUrl: 'https://docs.langchain.com/',
    repoUrl: 'https://github.com/langchain-ai/langchain',
    preferredSourceUrl: 'https://docs.langchain.com/',
    officialSourceLabel: 'LangChain docs',
    description: t('A broad framework for building LLM apps, retrieval pipelines, and agent workflows across providers.', '用來打造 LLM app、檢索管線與跨供應商 agent workflow 的廣泛框架。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'deepseek', 'mistral', 'cohere', 'perplexity', 'local'],
    installDifficulty: 'Moderate',
    utilityScore: 90,
    compatibilityScore: 95,
    reliabilityScore: 86,
    docsScore: 86,
    adoptionScore: 92,
    safetyMaintenanceScore: 83,
    overallScore: 89,
    bestUseCases: ['agent-automation', 'coding', 'research'],
    deployment: 'hybrid',
    installMethod: 'pip',
    supportedHosts: ['Python apps', 'JavaScript apps', 'APIs'],
    capabilities: ['provider abstraction', 'retrieval pipelines', 'tool integration', 'agent flows'],
    auth: { type: 'none' },
    permissionProfile: { level: 'medium', notes: 'Risk depends on the tools and providers connected.' },
    worksWith: ['LangGraph', 'OpenAI', 'Anthropic', 'Weaviate'],
    tags: ['framework', 'retrieval', 'agents'],
    strengths: [t('Very broad ecosystem coverage.', '生態覆蓋非常廣。'), t('Good for teams that need provider abstraction.', '對需要供應商抽象層的團隊很有用。')],
    caveats: [t('The breadth can feel heavy for smaller apps.', '對小型 app 來說，廣度有時會顯得過重。'), t('Abstractions can obscure provider-specific strengths.', '抽象層有時會遮蔽供應商原生優勢。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('LangChain', {
      officialUrl: 'https://www.langchain.com/',
      docsUrl: 'https://docs.langchain.com/',
      repoUrl: 'https://github.com/langchain-ai/langchain',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'supportedProviderIds'],
    }),
  }),
  defineSkill({
    slug: 'openai-agents-sdk',
    name: 'OpenAI Agents SDK',
    providerId: 'openai',
    categoryId: 'agent-frameworks',
    subCategory: 'Provider-native agent SDK',
    skillType: 'api',
    officialUrl: 'https://openai.com/',
    docsUrl: 'https://openai.github.io/openai-agents-python/',
    repoUrl: 'https://github.com/openai/openai-agents-python',
    preferredSourceUrl: 'https://openai.github.io/openai-agents-python/',
    officialSourceLabel: 'OpenAI Agents docs',
    description: t('OpenAI’s provider-native SDK for building agents with tools, handoffs, guardrails, and tracing.', 'OpenAI 原生的 agent SDK，可建立含工具、handoff、guardrail 與 tracing 的 agents。'),
    supportedProviderIds: ['openai'],
    installDifficulty: 'Moderate',
    utilityScore: 89,
    compatibilityScore: 76,
    reliabilityScore: 88,
    docsScore: 88,
    adoptionScore: 82,
    safetyMaintenanceScore: 85,
    overallScore: 86,
    bestUseCases: ['agent-automation', 'coding'],
    deployment: 'hybrid',
    installMethod: 'pip',
    supportedHosts: ['Python apps', 'workers', 'APIs'],
    capabilities: ['tool calling', 'handoffs', 'guardrails', 'tracing'],
    auth: { type: 'api-key', notes: 'OpenAI API auth.' },
    permissionProfile: { level: 'medium', notes: 'SDK-level risk depends on attached tools and code execution choices.' },
    worksWith: ['OpenAI models', 'OpenAI Responses API', 'MCP'],
    tags: ['sdk', 'agents', 'provider-native'],
    strengths: [t('Very aligned with OpenAI-native agent features.', '和 OpenAI 原生 agent 功能高度對齊。'), t('Good choice when deep OpenAI integration matters more than neutrality.', '當深度整合 OpenAI 比中立性更重要時很適合。')],
    caveats: [t('Less provider-neutral than LangGraph or LangChain.', '不像 LangGraph / LangChain 那麼中立。'), t('Best for teams already comfortable with OpenAI’s stack.', '最適合已熟悉 OpenAI stack 的團隊。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('OpenAI Agents SDK', {
      officialUrl: 'https://openai.com/',
      docsUrl: 'https://openai.github.io/openai-agents-python/',
      repoUrl: 'https://github.com/openai/openai-agents-python',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'n8n',
    name: 'n8n',
    providerId: 'any',
    categoryId: 'workflow-automation',
    subCategory: 'No-code automation',
    skillType: 'workflow',
    officialUrl: 'https://n8n.io/',
    docsUrl: 'https://docs.n8n.io/',
    repoUrl: 'https://github.com/n8n-io/n8n',
    preferredSourceUrl: 'https://docs.n8n.io/',
    officialSourceLabel: 'n8n docs',
    description: t('A workflow automation platform for triggers, integrations, and multi-step AI operations.', '可做觸發器、整合與多步驟 AI 營運流程的工作流自動化平台。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'deepseek', 'mistral', 'cohere', 'perplexity', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 90,
    compatibilityScore: 92,
    reliabilityScore: 87,
    docsScore: 87,
    adoptionScore: 90,
    safetyMaintenanceScore: 84,
    overallScore: 89,
    bestUseCases: ['agent-automation'],
    deployment: 'hybrid',
    installMethod: 'manual',
    supportedHosts: ['self-hosted', 'cloud'],
    capabilities: ['trigger-based workflows', 'integrations', 'approval steps', 'AI automation'],
    auth: { type: 'oauth', notes: 'Depends on connected services and provider keys.' },
    permissionProfile: { level: 'medium', notes: 'Workflow nodes can reach many external systems.' },
    worksWith: ['Zapier AI Actions', 'OpenAI', 'Anthropic', 'Google Workspace'],
    tags: ['automation', 'workflow', 'integrations'],
    strengths: [t('Practical for operational AI workflows that need triggers and approvals.', '很適合需要觸發與審批的營運型 AI 工作流。'), t('Flexible enough for mixed human-and-AI processes.', '對人機混合流程相當靈活。')],
    caveats: [t('Governance matters once workflows touch many systems.', '當 workflow 接到很多系統後，治理會變重要。'), t('Can become spaghetti without workflow discipline.', '若缺少流程紀律，容易長成 spaghetti。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('n8n', {
      officialUrl: 'https://n8n.io/',
      docsUrl: 'https://docs.n8n.io/',
      repoUrl: 'https://github.com/n8n-io/n8n',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'pipedream',
    name: 'Pipedream',
    providerId: 'any',
    categoryId: 'workflow-automation',
    subCategory: 'API workflow automation',
    skillType: 'workflow',
    officialUrl: 'https://pipedream.com/',
    docsUrl: 'https://pipedream.com/docs/',
    preferredSourceUrl: 'https://pipedream.com/docs/',
    officialSourceLabel: 'Pipedream docs',
    description: t('An integration and automation platform for event-driven workflows, APIs, and AI actions.', '用於事件驅動 workflow、API 與 AI actions 的整合自動化平台。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 85,
    compatibilityScore: 88,
    reliabilityScore: 86,
    docsScore: 86,
    adoptionScore: 84,
    safetyMaintenanceScore: 83,
    overallScore: 85,
    bestUseCases: ['agent-automation'],
    deployment: 'hosted',
    installMethod: 'hosted',
    supportedHosts: ['cloud'],
    capabilities: ['event triggers', 'API orchestration', 'webhooks', 'automation components'],
    auth: { type: 'oauth', notes: 'Depends on connected services.' },
    permissionProfile: { level: 'medium', notes: 'Hosted automation layer with access to connected services.' },
    worksWith: ['OpenAI', 'Slack', 'GitHub', 'Google Workspace'],
    tags: ['automation', 'apis', 'hosted'],
    strengths: [t('Fast path for API-heavy workflows.', '很適合快速組裝 API 密集型流程。'), t('Good fit for hosted event-driven automations.', '很適合託管型事件驅動自動化。')],
    caveats: [t('Hosted workflow centralization can raise governance questions.', '流程集中到 hosted 層後，治理問題會變得重要。'), t('Less ideal for teams wanting maximum local control.', '不太適合要求高度本地控制的團隊。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Pipedream', {
      officialUrl: 'https://pipedream.com/',
      docsUrl: 'https://pipedream.com/docs/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'playwright',
    name: 'Playwright',
    providerId: 'any',
    categoryId: 'browser-web',
    subCategory: 'Browser automation',
    skillType: 'browser',
    officialUrl: 'https://playwright.dev/',
    docsUrl: 'https://playwright.dev/docs/intro',
    repoUrl: 'https://github.com/microsoft/playwright',
    preferredSourceUrl: 'https://playwright.dev/docs/intro',
    officialSourceLabel: 'Playwright docs',
    description: t('A modern browser automation framework used for reliable UI scripting, testing, and web interactions.', '現代化瀏覽器自動化框架，適合穩定的 UI 腳本、測試與網頁互動。'),
    supportedProviderIds: ['any'],
    installDifficulty: 'Moderate',
    utilityScore: 89,
    compatibilityScore: 87,
    reliabilityScore: 92,
    docsScore: 90,
    adoptionScore: 93,
    safetyMaintenanceScore: 84,
    overallScore: 89,
    bestUseCases: ['coding', 'agent-automation', 'research'],
    deployment: 'hybrid',
    installMethod: 'npm',
    supportedHosts: ['Node.js', 'Python', 'CI'],
    capabilities: ['browser control', 'scraping', 'testing', 'page automation'],
    auth: { type: 'none' },
    permissionProfile: { level: 'medium', notes: 'Browser automation can access authenticated sessions and web content.' },
    worksWith: ['Browserbase', 'LangGraph', 'web agents'],
    tags: ['browser', 'automation', 'testing'],
    strengths: [t('Very dependable browser automation baseline.', '瀏覽器自動化基線非常可靠。'), t('Widely understood and well documented.', '普及度高、文件也成熟。')],
    caveats: [t('Running browsers at scale still adds operational overhead.', '大規模跑瀏覽器仍然有營運成本。'), t('Not a hosted browser service on its own.', '本身不是 hosted browser 服務。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Playwright', {
      officialUrl: 'https://playwright.dev/',
      docsUrl: 'https://playwright.dev/docs/intro',
      repoUrl: 'https://github.com/microsoft/playwright',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts'],
    }),
  }),
  defineSkill({
    slug: 'browserbase',
    name: 'Browserbase',
    providerId: 'any',
    categoryId: 'browser-web',
    subCategory: 'Hosted browser infrastructure',
    skillType: 'browser',
    officialUrl: 'https://www.browserbase.com/',
    docsUrl: 'https://docs.browserbase.com/',
    preferredSourceUrl: 'https://docs.browserbase.com/',
    officialSourceLabel: 'Browserbase docs',
    description: t('Hosted browser infrastructure for running browser automation and web agents in the cloud.', '託管式瀏覽器基礎設施，可在雲端執行瀏覽器自動化與 web agents。'),
    supportedProviderIds: ['any'],
    installDifficulty: 'Easy',
    utilityScore: 87,
    compatibilityScore: 84,
    reliabilityScore: 88,
    docsScore: 86,
    adoptionScore: 82,
    safetyMaintenanceScore: 84,
    overallScore: 85,
    bestUseCases: ['agent-automation', 'research'],
    deployment: 'hosted',
    installMethod: 'npm',
    supportedHosts: ['cloud', 'Node.js'],
    capabilities: ['hosted browsers', 'session replay', 'browser agents', 'remote execution'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'medium', notes: 'Hosted browser sessions can access external websites and credentials.' },
    worksWith: ['Playwright', 'web agents', 'automation workflows'],
    tags: ['browser', 'hosted', 'infra'],
    strengths: [t('Removes a lot of browser ops pain.', '能移除不少瀏覽器維運痛點。'), t('Useful for teams moving browser automation into production.', '很適合把瀏覽器自動化推進 production 的團隊。')],
    caveats: [t('Adds a vendor dependency for browser runtime.', '會增加瀏覽器 runtime 的供應商依賴。'), t('Sensitive workflows still need session and secret hygiene.', '敏感流程仍要注意 session 與 secret 管理。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Browserbase', {
      officialUrl: 'https://www.browserbase.com/',
      docsUrl: 'https://docs.browserbase.com/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'firecrawl',
    name: 'Firecrawl',
    providerId: 'any',
    categoryId: 'research-retrieval',
    subCategory: 'Web crawling and extraction',
    skillType: 'extraction',
    officialUrl: 'https://www.firecrawl.dev/',
    docsUrl: 'https://docs.firecrawl.dev/',
    repoUrl: 'https://github.com/mendableai/firecrawl',
    preferredSourceUrl: 'https://docs.firecrawl.dev/',
    officialSourceLabel: 'Firecrawl docs',
    description: t('A web crawling and extraction layer designed to turn sites into clean content for AI pipelines.', '專為 AI pipeline 把網站轉成乾淨內容的 web crawling 與 extraction 層。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 89,
    compatibilityScore: 88,
    reliabilityScore: 84,
    docsScore: 85,
    adoptionScore: 86,
    safetyMaintenanceScore: 80,
    overallScore: 86,
    bestUseCases: ['research', 'agent-automation'],
    deployment: 'hybrid',
    installMethod: 'npm',
    supportedHosts: ['cloud', 'Node.js', 'Python'],
    capabilities: ['crawling', 'markdown extraction', 'scraping APIs', 'site ingestion'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'medium', notes: 'Interacts with third-party websites and external content.' },
    worksWith: ['LangChain', 'LangGraph', 'vector stores'],
    tags: ['crawl', 'extract', 'rag'],
    strengths: [t('Great fit for content ingestion and RAG prep.', '很適合內容擷取與 RAG 前處理。'), t('Canonical crawling API helps reduce custom scraper work.', '統一的 crawling API 可以減少客製 scraper 工作。')],
    caveats: [t('Website variability always creates some extraction edge cases.', '網站差異永遠會帶來一些擷取 edge case。'), t('Still needs legal and rate-limit awareness.', '仍要注意法務與 rate limit。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Firecrawl', {
      officialUrl: 'https://www.firecrawl.dev/',
      docsUrl: 'https://docs.firecrawl.dev/',
      repoUrl: 'https://github.com/mendableai/firecrawl',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'tavily',
    name: 'Tavily',
    providerId: 'any',
    categoryId: 'research-retrieval',
    subCategory: 'Search API',
    skillType: 'search',
    officialUrl: 'https://tavily.com/',
    docsUrl: 'https://docs.tavily.com/',
    preferredSourceUrl: 'https://docs.tavily.com/',
    officialSourceLabel: 'Tavily docs',
    description: t('A search API built for LLMs and agents that need live web results and research context.', '為 LLM 與 agents 設計的搜尋 API，可提供即時網頁結果與研究上下文。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 87,
    compatibilityScore: 89,
    reliabilityScore: 84,
    docsScore: 86,
    adoptionScore: 84,
    safetyMaintenanceScore: 81,
    overallScore: 85,
    bestUseCases: ['research', 'agent-automation'],
    deployment: 'hosted',
    installMethod: 'api',
    supportedHosts: ['cloud', 'Python', 'JavaScript'],
    capabilities: ['web search', 'LLM-friendly results', 'research context', 'SERP access'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'low' },
    worksWith: ['LangChain', 'LangGraph', 'research agents'],
    tags: ['search', 'research', 'api'],
    strengths: [t('Simple way to add live web context to agents.', '能很簡單地替 agent 加上即時網頁上下文。'), t('Designed for LLM consumption rather than raw search UI.', '設計重點是給 LLM 消費，而不是傳統搜尋 UI。')],
    caveats: [t('Search quality still depends on query strategy.', '搜尋品質仍取決於 query 策略。'), t('Not a full crawling or browser stack.', '不是完整 crawling 或 browser stack。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Tavily', {
      officialUrl: 'https://tavily.com/',
      docsUrl: 'https://docs.tavily.com/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'exa',
    name: 'Exa',
    providerId: 'any',
    categoryId: 'research-retrieval',
    subCategory: 'Web search and data API',
    skillType: 'search',
    officialUrl: 'https://exa.ai/',
    docsUrl: 'https://docs.exa.ai/',
    preferredSourceUrl: 'https://docs.exa.ai/',
    officialSourceLabel: 'Exa docs',
    description: t('A search and web data API for retrieval, company research, and agent discovery tasks.', '用於檢索、公司研究與 agent 發現任務的搜尋與 web data API。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 86,
    compatibilityScore: 88,
    reliabilityScore: 84,
    docsScore: 85,
    adoptionScore: 82,
    safetyMaintenanceScore: 81,
    overallScore: 84,
    bestUseCases: ['research'],
    deployment: 'hosted',
    installMethod: 'api',
    supportedHosts: ['cloud', 'Python', 'JavaScript'],
    capabilities: ['search API', 'web data retrieval', 'entity research', 'content discovery'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'low' },
    worksWith: ['research agents', 'LangChain', 'CRM enrichment'],
    tags: ['search', 'data', 'research'],
    strengths: [t('Strong fit for structured research and company discovery.', '很適合結構化研究與公司探索。'), t('Useful when search needs to feed downstream systems, not just chat.', '當搜尋結果要餵給下游系統，而不只是聊天時會很好用。')],
    caveats: [t('Narrower than full browser automation.', '範圍比完整瀏覽器自動化更窄。'), t('Teams still need their own ranking and evaluation logic.', '團隊仍需自建排序與評估邏輯。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Exa', {
      officialUrl: 'https://exa.ai/',
      docsUrl: 'https://docs.exa.ai/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'serpapi',
    name: 'SerpApi',
    providerId: 'any',
    categoryId: 'research-retrieval',
    subCategory: 'SERP API',
    skillType: 'search',
    officialUrl: 'https://serpapi.com/',
    docsUrl: 'https://serpapi.com/search-api',
    preferredSourceUrl: 'https://serpapi.com/search-api',
    officialSourceLabel: 'SerpApi docs',
    description: t('An API layer for search engine result pages across major engines and verticals.', '可取得主要搜尋引擎與垂直場景結果頁的 API 層。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 82,
    compatibilityScore: 88,
    reliabilityScore: 86,
    docsScore: 84,
    adoptionScore: 86,
    safetyMaintenanceScore: 82,
    overallScore: 83,
    bestUseCases: ['research'],
    deployment: 'hosted',
    installMethod: 'api',
    supportedHosts: ['cloud', 'Python', 'JavaScript'],
    capabilities: ['SERP APIs', 'shopping results', 'maps results', 'news results'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'low' },
    worksWith: ['research agents', 'market intelligence', 'SEO tooling'],
    tags: ['search', 'serp', 'api'],
    strengths: [t('Wide search-engine coverage.', '搜尋引擎覆蓋面廣。'), t('Useful for structured data collection from SERPs.', '適合從 SERP 收集結構化資料。')],
    caveats: [t('Less opinionated for LLM-native workflows than some newer APIs.', '對 LLM-native workflow 的意見性較弱。'), t('Often needs extra post-processing before model use.', '模型使用前常需要額外後處理。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('SerpApi', {
      officialUrl: 'https://serpapi.com/',
      docsUrl: 'https://serpapi.com/search-api',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'openai-whisper',
    name: 'OpenAI Whisper',
    providerId: 'openai',
    categoryId: 'data-extraction',
    subCategory: 'Speech transcription',
    skillType: 'extraction',
    officialUrl: 'https://github.com/openai/whisper',
    docsUrl: 'https://github.com/openai/whisper',
    repoUrl: 'https://github.com/openai/whisper',
    preferredSourceUrl: 'https://github.com/openai/whisper',
    officialSourceLabel: 'OpenAI repo',
    description: t('OpenAI’s open-source speech recognition model and CLI for local transcription.', 'OpenAI 開源的語音辨識模型與 CLI，可做本地轉錄。'),
    supportedProviderIds: ['local'],
    installDifficulty: 'Moderate',
    utilityScore: 85,
    compatibilityScore: 75,
    reliabilityScore: 86,
    docsScore: 82,
    adoptionScore: 92,
    safetyMaintenanceScore: 85,
    overallScore: 84,
    bestUseCases: ['research'],
    deployment: 'local',
    installMethod: 'pip',
    supportedHosts: ['macOS', 'Linux', 'Windows'],
    capabilities: ['speech-to-text', 'local transcription', 'multilingual recognition'],
    auth: { type: 'none' },
    permissionProfile: { level: 'low' },
    worksWith: ['media pipelines', 'meeting transcription', 'podcast ingestion'],
    tags: ['audio', 'transcription', 'local'],
    strengths: [t('Local transcription avoids sending audio to an API.', '本地轉錄不必把音訊送到 API。'), t('Still one of the best-known open transcription baselines.', '仍是最知名的開源轉錄基線之一。')],
    caveats: [t('Local performance depends heavily on available hardware.', '本地效能很依賴硬體。'), t('Not a full managed speech platform.', '不是完整託管語音平台。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('OpenAI Whisper', {
      officialUrl: 'https://github.com/openai/whisper',
      docsUrl: 'https://github.com/openai/whisper',
      repoUrl: 'https://github.com/openai/whisper',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts'],
    }),
  }),
  defineSkill({
    slug: '1password-cli',
    name: '1Password CLI',
    providerId: 'any',
    categoryId: 'security-secrets',
    subCategory: 'Secrets management',
    skillType: 'security',
    officialUrl: 'https://1password.com/',
    docsUrl: 'https://developer.1password.com/docs/cli/',
    preferredSourceUrl: 'https://developer.1password.com/docs/cli/',
    officialSourceLabel: '1Password docs',
    description: t('A secrets-management CLI for injecting, reading, and operating on credentials in workflows.', '可在工作流中注入、讀取與操作憑證的 secrets-management CLI。'),
    supportedProviderIds: ['any'],
    installDifficulty: 'Easy',
    utilityScore: 88,
    compatibilityScore: 86,
    reliabilityScore: 91,
    docsScore: 89,
    adoptionScore: 87,
    safetyMaintenanceScore: 94,
    overallScore: 89,
    bestUseCases: ['coding', 'agent-automation'],
    deployment: 'local',
    installMethod: 'manual',
    supportedHosts: ['CLI', 'macOS', 'Linux', 'Windows'],
    capabilities: ['secret injection', 'vault access', 'credential automation', 'service-account support'],
    auth: { type: 'local-config', notes: 'Requires 1Password account/session.' },
    permissionProfile: { level: 'high', notes: 'Touches sensitive credentials and secret material.' },
    worksWith: ['CI/CD', 'local dev', 'agent workflows'],
    tags: ['secrets', 'security', 'cli'],
    strengths: [t('Strong fit for practical secret hygiene.', '非常適合實務上的 secret hygiene。'), t('Good bridge between developer workflows and safer credential handling.', '能把開發者工作流和更安全的憑證管理接起來。')],
    caveats: [t('Secrets tooling deserves extra operational review.', 'secret 工具本來就值得額外審查。'), t('Account setup and session handling add onboarding steps.', '帳號設定與 session 管理會增加上手步驟。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('1Password CLI', {
      officialUrl: 'https://1password.com/',
      docsUrl: 'https://developer.1password.com/docs/cli/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'weaviate',
    name: 'Weaviate',
    providerId: 'any',
    categoryId: 'memory-knowledge',
    subCategory: 'Vector database',
    skillType: 'memory',
    officialUrl: 'https://weaviate.io/',
    docsUrl: 'https://docs.weaviate.io/',
    repoUrl: 'https://github.com/weaviate/weaviate',
    preferredSourceUrl: 'https://docs.weaviate.io/',
    officialSourceLabel: 'Weaviate docs',
    description: t('A vector database and knowledge layer for retrieval, semantic search, and memory-heavy AI systems.', '用於檢索、語義搜尋與記憶密集 AI 系統的向量資料庫與知識層。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'local', 'any'],
    installDifficulty: 'Advanced',
    utilityScore: 87,
    compatibilityScore: 88,
    reliabilityScore: 86,
    docsScore: 85,
    adoptionScore: 86,
    safetyMaintenanceScore: 83,
    overallScore: 85,
    bestUseCases: ['research', 'agent-automation'],
    deployment: 'hybrid',
    installMethod: 'manual',
    supportedHosts: ['self-hosted', 'cloud', 'Kubernetes'],
    capabilities: ['vector search', 'knowledge storage', 'retrieval', 'hybrid search'],
    auth: { type: 'api-key', notes: 'Varies by deployment mode.' },
    permissionProfile: { level: 'medium', notes: 'Stores knowledge and embeddings that may be sensitive.' },
    worksWith: ['LangChain', 'LangGraph', 'Firecrawl'],
    tags: ['vector-db', 'memory', 'retrieval'],
    strengths: [t('Good fit for structured knowledge layers.', '很適合作為結構化知識層。'), t('Supports more serious retrieval architectures than a quick demo stack.', '比起 demo stack，更能支撐正式的檢索架構。')],
    caveats: [t('Database operations add maintenance burden.', '資料庫維運會增加負擔。'), t('Not necessary for every small assistant.', '不是每個小型助理都需要。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Weaviate', {
      officialUrl: 'https://weaviate.io/',
      docsUrl: 'https://docs.weaviate.io/',
      repoUrl: 'https://github.com/weaviate/weaviate',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'mem0',
    name: 'Mem0',
    providerId: 'any',
    categoryId: 'memory-knowledge',
    subCategory: 'Memory layer',
    skillType: 'memory',
    officialUrl: 'https://mem0.ai/',
    docsUrl: 'https://docs.mem0.ai/',
    repoUrl: 'https://github.com/mem0ai/mem0',
    preferredSourceUrl: 'https://docs.mem0.ai/',
    officialSourceLabel: 'Mem0 docs',
    description: t('A memory layer for capturing, storing, and retrieving useful user or agent context over time.', '用來長期捕捉、儲存與取回使用者或 agent 上下文的記憶層。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 84,
    compatibilityScore: 86,
    reliabilityScore: 82,
    docsScore: 83,
    adoptionScore: 80,
    safetyMaintenanceScore: 79,
    overallScore: 82,
    bestUseCases: ['agent-automation'],
    deployment: 'hybrid',
    installMethod: 'pip',
    supportedHosts: ['Python', 'JavaScript', 'cloud'],
    capabilities: ['memory capture', 'context retrieval', 'user profiling', 'agent memory'],
    auth: { type: 'api-key', notes: 'Depends on deployment and storage backend.' },
    permissionProfile: { level: 'medium', notes: 'Memory systems can accumulate sensitive long-lived context.' },
    worksWith: ['LangGraph', 'LangChain', 'agent assistants'],
    tags: ['memory', 'context', 'agents'],
    strengths: [t('Explicit memory layer helps move beyond stateless chat.', '明確的記憶層有助於走出 stateless chat。'), t('Useful for personalization and continuity.', '對個人化與連續性很有幫助。')],
    caveats: [t('Memory quality and privacy policy matter as much as tooling.', '記憶品質與隱私政策和工具本身一樣重要。'), t('Poor memory hygiene can become a trust problem quickly.', '記憶 hygiene 不好，很快就會變成信任問題。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Mem0', {
      officialUrl: 'https://mem0.ai/',
      docsUrl: 'https://docs.mem0.ai/',
      repoUrl: 'https://github.com/mem0ai/mem0',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'github-mcp-server',
    name: 'GitHub MCP Server',
    providerId: 'any',
    categoryId: 'coding-devtools',
    subCategory: 'GitHub integration',
    skillType: 'mcp',
    officialUrl: 'https://github.com/github/github-mcp-server',
    docsUrl: 'https://github.com/github/github-mcp-server',
    repoUrl: 'https://github.com/github/github-mcp-server',
    preferredSourceUrl: 'https://github.com/github/github-mcp-server',
    officialSourceLabel: 'GitHub repo',
    description: t('An official GitHub MCP server for repository, issue, PR, and code-context operations.', '官方 GitHub MCP server，可處理 repository、issue、PR 與程式碼上下文操作。'),
    supportedProviderIds: ['openai', 'anthropic', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 87,
    compatibilityScore: 84,
    reliabilityScore: 85,
    docsScore: 82,
    adoptionScore: 81,
    safetyMaintenanceScore: 80,
    overallScore: 84,
    bestUseCases: ['coding', 'agent-automation'],
    deployment: 'hybrid',
    installMethod: 'npm',
    supportedHosts: ['MCP clients', 'CLI agents'],
    capabilities: ['repo access', 'issues', 'PRs', 'code context'],
    auth: { type: 'oauth', notes: 'GitHub auth / token scope required.' },
    permissionProfile: { level: 'high', notes: 'Can access and potentially modify repository data depending on granted scopes.' },
    worksWith: ['Claude Code', 'Codex CLI', 'MCP clients'],
    tags: ['mcp', 'github', 'coding'],
    strengths: [t('Very relevant for coding agents working inside GitHub workflows.', '對 GitHub 工作流中的 coding agent 非常 relevant。'), t('Official source helps reduce ambiguity about the canonical server.', '官方來源降低了 canonical server 的模糊性。')],
    caveats: [t('Permissions should be scoped tightly.', '權限應盡量縮小。'), t('Still depends on the MCP host’s maturity and UX.', '仍取決於 MCP host 本身的成熟度與 UX。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('GitHub MCP Server', {
      officialUrl: 'https://github.com/github/github-mcp-server',
      docsUrl: 'https://github.com/github/github-mcp-server',
      repoUrl: 'https://github.com/github/github-mcp-server',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'supabase-mcp-server',
    name: 'Supabase MCP Server',
    providerId: 'any',
    categoryId: 'memory-knowledge',
    subCategory: 'Database integration',
    skillType: 'mcp',
    officialUrl: 'https://supabase.com/',
    docsUrl: 'https://supabase.com/docs/guides/getting-started/mcp',
    preferredSourceUrl: 'https://supabase.com/docs/guides/getting-started/mcp',
    officialSourceLabel: 'Supabase docs',
    description: t('Supabase’s MCP integration layer for connecting agents to database-backed product context.', 'Supabase 的 MCP 整合層，可讓 agents 連到資料庫驅動的產品上下文。'),
    supportedProviderIds: ['openai', 'anthropic', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 84,
    compatibilityScore: 82,
    reliabilityScore: 84,
    docsScore: 83,
    adoptionScore: 78,
    safetyMaintenanceScore: 80,
    overallScore: 82,
    bestUseCases: ['agent-automation', 'coding'],
    deployment: 'hybrid',
    installMethod: 'manual',
    supportedHosts: ['MCP clients', 'Supabase projects'],
    capabilities: ['database access', 'product context', 'tool connectivity', 'MCP integration'],
    auth: { type: 'api-key', notes: 'Supabase project credentials and MCP host setup required.' },
    permissionProfile: { level: 'high', notes: 'Database-connected tools need careful read/write scoping.' },
    worksWith: ['Supabase', 'MCP clients', 'coding agents'],
    tags: ['mcp', 'database', 'supabase'],
    strengths: [t('Useful where product context lives in Supabase.', '當產品上下文本來就在 Supabase 裡時很有價值。'), t('Helps bridge application data into agent workflows.', '能把應用資料橋接進 agent workflow。')],
    caveats: [t('Database permissions need especially careful review.', '資料庫權限尤其需要小心審查。'), t('More relevant for Supabase-centered stacks than general teams.', '對以 Supabase 為中心的 stack 才特別 relevant。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Supabase MCP Server', {
      officialUrl: 'https://supabase.com/',
      docsUrl: 'https://supabase.com/docs/guides/getting-started/mcp',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'mcp-toolbox',
    name: 'Gen AI Toolbox for Databases',
    providerId: 'google',
    categoryId: 'agent-frameworks',
    subCategory: 'Database tool layer',
    skillType: 'mcp',
    officialUrl: 'https://github.com/googleapis/genai-toolbox',
    docsUrl: 'https://github.com/googleapis/genai-toolbox',
    repoUrl: 'https://github.com/googleapis/genai-toolbox',
    preferredSourceUrl: 'https://github.com/googleapis/genai-toolbox',
    officialSourceLabel: 'Google repo',
    description: t('Google’s open-source toolbox for exposing database tools to GenAI systems and MCP-capable clients.', 'Google 開源的 toolbox，可把資料庫工具暴露給 GenAI 系統與支援 MCP 的 client。'),
    supportedProviderIds: ['google', 'openai', 'anthropic', 'any'],
    installDifficulty: 'Advanced',
    utilityScore: 84,
    compatibilityScore: 82,
    reliabilityScore: 82,
    docsScore: 80,
    adoptionScore: 76,
    safetyMaintenanceScore: 79,
    overallScore: 81,
    bestUseCases: ['agent-automation', 'coding'],
    deployment: 'hybrid',
    installMethod: 'manual',
    supportedHosts: ['MCP clients', 'containerized deployments'],
    capabilities: ['database tools', 'tool serving', 'MCP compatibility', 'data access abstraction'],
    auth: { type: 'custom', notes: 'Depends on database and deployment configuration.' },
    permissionProfile: { level: 'high', notes: 'Database tool exposure needs explicit read/write policy control.' },
    worksWith: ['MCP clients', 'databases', 'Google AI workflows'],
    tags: ['mcp', 'databases', 'tooling'],
    strengths: [t('Interesting bridge between databases and agent tools.', '在資料庫與 agent 工具之間提供有趣的橋接層。'), t('Official Google stewardship helps signal canonical direction.', '由 Google 維護，有助於傳達 canonical direction。')],
    caveats: [t('Operational complexity is non-trivial.', '營運複雜度不低。'), t('Needs strong governance before exposing production data.', '在暴露正式資料前需要嚴格治理。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Gen AI Toolbox for Databases', {
      officialUrl: 'https://github.com/googleapis/genai-toolbox',
      docsUrl: 'https://github.com/googleapis/genai-toolbox',
      repoUrl: 'https://github.com/googleapis/genai-toolbox',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'e2b-sandbox',
    name: 'E2B Sandbox',
    providerId: 'any',
    categoryId: 'execution-sandboxes',
    subCategory: 'Hosted execution',
    skillType: 'connector',
    officialUrl: 'https://e2b.dev/',
    docsUrl: 'https://e2b.dev/docs',
    preferredSourceUrl: 'https://e2b.dev/docs',
    officialSourceLabel: 'E2B docs',
    description: t('A hosted execution sandbox for giving agents safer code-running environments.', '給 agents 使用、較安全的託管程式執行沙盒。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 86,
    compatibilityScore: 84,
    reliabilityScore: 85,
    docsScore: 84,
    adoptionScore: 80,
    safetyMaintenanceScore: 87,
    overallScore: 84,
    bestUseCases: ['coding', 'agent-automation'],
    deployment: 'hosted',
    installMethod: 'npm',
    supportedHosts: ['cloud', 'Python', 'JavaScript'],
    capabilities: ['sandboxed execution', 'ephemeral environments', 'code running', 'tool isolation'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'medium', notes: 'Safer than local execution but still needs scope controls.' },
    worksWith: ['LangGraph', 'OpenAI Agents SDK', 'coding agents'],
    tags: ['sandbox', 'execution', 'agents'],
    strengths: [t('Helpful when local execution is too risky.', '當本地執行風險太高時很有幫助。'), t('Makes code-running agents more production-friendly.', '讓可執行程式的 agents 更接近 production。')],
    caveats: [t('Adds hosted execution cost and dependency.', '會增加 hosted execution 成本與依賴。'), t('Still requires policy boundaries for what agents may run.', '仍需要對 agent 可執行內容設邊界。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('E2B Sandbox', {
      officialUrl: 'https://e2b.dev/',
      docsUrl: 'https://e2b.dev/docs',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'zapier-ai-actions',
    name: 'Zapier AI Actions',
    providerId: 'any',
    categoryId: 'workflow-automation',
    subCategory: 'Hosted actions layer',
    skillType: 'connector',
    officialUrl: 'https://zapier.com/',
    docsUrl: 'https://actions.zapier.com/docs/platform/gpt/',
    preferredSourceUrl: 'https://actions.zapier.com/docs/platform/gpt/',
    officialSourceLabel: 'Zapier docs',
    description: t('Zapier’s action layer for letting AI systems trigger business tools and SaaS workflows.', '讓 AI 系統觸發商務工具與 SaaS workflow 的 Zapier action 層。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 84,
    compatibilityScore: 87,
    reliabilityScore: 86,
    docsScore: 83,
    adoptionScore: 89,
    safetyMaintenanceScore: 81,
    overallScore: 84,
    bestUseCases: ['agent-automation'],
    deployment: 'hosted',
    installMethod: 'hosted',
    supportedHosts: ['cloud'],
    capabilities: ['app actions', 'SaaS automation', 'business workflow triggers', 'tool access'],
    auth: { type: 'oauth', notes: 'Depends on connected apps.' },
    permissionProfile: { level: 'medium', notes: 'Can act across many connected business apps.' },
    worksWith: ['ChatGPT actions', 'business SaaS', 'workflow automation'],
    tags: ['automation', 'actions', 'saas'],
    strengths: [t('Huge app ecosystem makes it very practical.', '龐大 app 生態讓它很實用。'), t('Useful bridge from AI assistants into business systems.', '能把 AI 助理順利接進商務系統。')],
    caveats: [t('Action sprawl can become hard to govern.', 'action 過多時不容易治理。'), t('Hosted middleware may not fit every security posture.', '託管中介層未必符合所有安全姿態。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Zapier AI Actions', {
      officialUrl: 'https://zapier.com/',
      docsUrl: 'https://actions.zapier.com/docs/platform/gpt/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),

  defineSkill({
    slug: 'notion-mcp-server',
    name: 'Notion MCP',
    providerId: 'any',
    categoryId: 'memory-knowledge',
    subCategory: 'Workspace knowledge access',
    skillType: 'mcp',
    officialUrl: 'https://www.notion.com/',
    docsUrl: 'https://developers.notion.com/docs/mcp',
    repoUrl: 'https://github.com/makenotion/notion-mcp-server',
    preferredSourceUrl: 'https://developers.notion.com/docs/mcp',
    officialSourceLabel: 'Notion docs',
    description: t('Notion’s official MCP integration for exposing workspace search, pages, comments, and structured data sources to AI clients.', 'Notion 官方的 MCP 整合，可把 workspace 搜尋、頁面、留言與結構化資料來源暴露給 AI client。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 88,
    compatibilityScore: 86,
    reliabilityScore: 86,
    docsScore: 88,
    adoptionScore: 85,
    safetyMaintenanceScore: 78,
    overallScore: 86,
    bestUseCases: ['research', 'agent-automation'],
    deployment: 'hybrid',
    installMethod: 'manual',
    supportedHosts: ['MCP clients', 'Claude Desktop', 'Cursor'],
    capabilities: ['workspace search', 'page editing', 'comments', 'database/data source access'],
    auth: { type: 'oauth', notes: 'Remote Notion MCP supports OAuth; self-hosted mode can require API tokens.' },
    permissionProfile: { level: 'high', notes: 'Workspace read/write access should be scoped carefully, especially for page edits and comments.' },
    worksWith: ['Claude Desktop', 'Cursor', 'Notion workspaces'],
    tags: ['mcp', 'notion', 'knowledge'],
    strengths: [t('Official Notion stewardship makes the integration direction clear.', '由 Notion 官方維護，整合方向更清楚。'), t('High-value bridge for teams whose operating context already lives in Notion.', '對上下文本來就在 Notion 的團隊特別有價值。')],
    caveats: [t('Read/write workspace permissions need careful governance.', 'workspace 的讀寫權限需要嚴格治理。'), t('The open-source local server is no longer the primary support path versus Notion’s remote MCP.', '相較於 Notion 的 remote MCP，開源本地 server 已不是主要支援路徑。')],
    updatedAt: EXTERNAL_VALIDATION_AT,
    sourceRefs: skillSources('Notion MCP', {
      officialUrl: 'https://www.notion.com/',
      docsUrl: 'https://developers.notion.com/docs/mcp',
      repoUrl: 'https://github.com/makenotion/notion-mcp-server',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }, EXTERNAL_VALIDATION_AT),
  }),
  defineSkill({
    slug: 'playwright-mcp',
    name: 'Playwright MCP',
    providerId: 'any',
    categoryId: 'browser-web',
    subCategory: 'Browser automation via MCP',
    skillType: 'browser',
    officialUrl: 'https://playwright.dev/',
    docsUrl: 'https://playwright.dev/docs/getting-started-mcp',
    repoUrl: 'https://github.com/microsoft/playwright-mcp',
    preferredSourceUrl: 'https://playwright.dev/docs/getting-started-mcp',
    officialSourceLabel: 'Playwright docs',
    description: t('Microsoft’s Playwright MCP server for structured browser automation, navigation, and testing-friendly web interaction.', 'Microsoft 的 Playwright MCP server，可做結構化瀏覽器自動化、導航與偏測試友善的網頁互動。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 89,
    compatibilityScore: 88,
    reliabilityScore: 87,
    docsScore: 88,
    adoptionScore: 86,
    safetyMaintenanceScore: 80,
    overallScore: 87,
    bestUseCases: ['coding', 'agent-automation'],
    deployment: 'local',
    installMethod: 'npm',
    supportedHosts: ['VS Code', 'Cursor', 'Claude Desktop', 'MCP clients'],
    capabilities: ['browser automation', 'accessibility-tree navigation', 'page interaction', 'test recording'],
    auth: { type: 'none' },
    permissionProfile: { level: 'high', notes: 'Browser automation can click, submit forms, and affect external systems if not sandboxed.' },
    worksWith: ['Playwright', 'Claude Desktop', 'Cursor'],
    tags: ['browser', 'mcp', 'playwright'],
    strengths: [t('Structured accessibility snapshots are more agent-friendly than screenshot-heavy approaches.', '結構化 accessibility snapshot 比起大量螢幕截圖更 agent-friendly。'), t('Official Playwright docs and repo make setup and usage easier to verify.', '有官方 Playwright 文件與 repo，安裝與用途都比較容易驗證。')],
    caveats: [t('Real browser control still carries obvious side-effect risk.', '真實瀏覽器控制仍然有明顯副作用風險。'), t('More useful for interactive web tasks than simple static scraping.', '比較適合互動式網頁任務，不是單純靜態爬取。')],
    updatedAt: EXTERNAL_VALIDATION_AT,
    sourceRefs: skillSources('Playwright MCP', {
      officialUrl: 'https://playwright.dev/',
      docsUrl: 'https://playwright.dev/docs/getting-started-mcp',
      repoUrl: 'https://github.com/microsoft/playwright-mcp',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'permissionProfile'],
    }, EXTERNAL_VALIDATION_AT),
  }),
  defineSkill({
    slug: 'docker-mcp-gateway',
    name: 'Docker MCP Gateway',
    providerId: 'any',
    categoryId: 'execution-sandboxes',
    subCategory: 'Containerized MCP gateway',
    skillType: 'connector',
    officialUrl: 'https://www.docker.com/',
    docsUrl: 'https://docs.docker.com/guides/lab-mcp-gateway/',
    repoUrl: 'https://github.com/docker/mcp-gateway',
    preferredSourceUrl: 'https://docs.docker.com/guides/lab-mcp-gateway/',
    officialSourceLabel: 'Docker docs',
    description: t('Docker’s gateway for running and brokering MCP servers in containerized, easier-to-govern environments.', 'Docker 的 gateway，可在容器化且較容易治理的環境中執行並代理 MCP servers。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 87,
    compatibilityScore: 84,
    reliabilityScore: 86,
    docsScore: 85,
    adoptionScore: 84,
    safetyMaintenanceScore: 85,
    overallScore: 85,
    bestUseCases: ['agent-automation', 'coding'],
    deployment: 'local',
    installMethod: 'manual',
    supportedHosts: ['Docker Desktop', 'containerized deployments', 'MCP clients'],
    capabilities: ['containerized server lifecycle', 'gateway endpoint', 'server brokering', 'credential centralization'],
    auth: { type: 'custom', notes: 'Auth depends on connected MCP servers and Docker host configuration.' },
    permissionProfile: { level: 'high', notes: 'Safer than ad hoc local servers, but Docker socket and connected server permissions still matter.' },
    worksWith: ['Docker Desktop', 'MCP clients', 'containerized MCP servers'],
    tags: ['docker', 'mcp', 'gateway'],
    strengths: [t('Gives teams one place to route and contain multiple MCP servers.', '讓團隊可以用單一入口路由並管控多個 MCP server。'), t('Container isolation is a meaningful quality signal for production-minded setups.', '對偏 production 的團隊來說，容器隔離是有意義的品質信號。')],
    caveats: [t('Still operationally heavier than a single local MCP server.', '相較單一在地 MCP server，營運上仍然更重。'), t('Security depends on how carefully Docker host access is constrained.', '安全性仍取決於 Docker host 權限是否被妥善限制。')],
    updatedAt: EXTERNAL_VALIDATION_AT,
    sourceRefs: skillSources('Docker MCP Gateway', {
      officialUrl: 'https://www.docker.com/',
      docsUrl: 'https://docs.docker.com/guides/lab-mcp-gateway/',
      repoUrl: 'https://github.com/docker/mcp-gateway',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }, EXTERNAL_VALIDATION_AT),
  }),
  defineSkill({
    slug: 'tavily-mcp',
    name: 'Tavily MCP',
    providerId: 'any',
    categoryId: 'research-retrieval',
    subCategory: 'Real-time web search via MCP',
    skillType: 'search',
    officialUrl: 'https://tavily.com/',
    docsUrl: 'https://docs.tavily.com/documentation/mcp',
    repoUrl: 'https://github.com/tavily-ai/tavily-mcp',
    preferredSourceUrl: 'https://docs.tavily.com/documentation/mcp',
    officialSourceLabel: 'Tavily docs',
    description: t('Tavily’s production-focused MCP server for web search, extraction, crawl, and map operations inside agent workflows.', 'Tavily 偏 production 的 MCP server，可在 agent workflow 內做網頁搜尋、抽取、crawl 與 map。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 89,
    compatibilityScore: 87,
    reliabilityScore: 85,
    docsScore: 87,
    adoptionScore: 84,
    safetyMaintenanceScore: 80,
    overallScore: 86,
    bestUseCases: ['research', 'agent-automation'],
    deployment: 'local',
    installMethod: 'npm',
    supportedHosts: ['Cursor', 'Claude Desktop', 'MCP clients'],
    capabilities: ['web search', 'content extraction', 'crawl', 'site mapping'],
    auth: { type: 'api-key', notes: 'Requires Tavily API access.' },
    permissionProfile: { level: 'medium', notes: 'Mostly network-bound retrieval risk, but external content quality still needs verification.' },
    worksWith: ['Cursor', 'Claude Desktop', 'research agents'],
    tags: ['search', 'mcp', 'tavily'],
    strengths: [t('Clear search-and-extract focus makes it easier to reason about than generic tool bundles.', '聚焦搜尋與抽取，比泛用工具包更容易理解與評估。'), t('Official Tavily docs expose concrete client compatibility and package signals.', '官方 Tavily 文件有明確 client 相容性與套件信號。')],
    caveats: [t('External web content remains noisy, regardless of the MCP wrapper.', '即使包成 MCP，外部網頁內容本身仍然有雜訊。'), t('Requires API spend and good prompting discipline to stay efficient.', '需要 API 成本與好的 prompting 紀律才能保持效率。')],
    updatedAt: EXTERNAL_VALIDATION_AT,
    sourceRefs: skillSources('Tavily MCP', {
      officialUrl: 'https://tavily.com/',
      docsUrl: 'https://docs.tavily.com/documentation/mcp',
      repoUrl: 'https://github.com/tavily-ai/tavily-mcp',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }, EXTERNAL_VALIDATION_AT),
  }),
  defineSkill({
    slug: 'grafana-mcp',
    name: 'Grafana MCP',
    providerId: 'any',
    categoryId: 'research-retrieval',
    subCategory: 'Observability retrieval and control',
    skillType: 'mcp',
    officialUrl: 'https://grafana.com/',
    docsUrl: 'https://grafana.com/developers/plugin-tools/how-to-guides/app-plugins/use-llms-and-mcp',
    repoUrl: 'https://github.com/grafana/mcp-grafana',
    preferredSourceUrl: 'https://github.com/grafana/mcp-grafana',
    officialSourceLabel: 'Grafana repo',
    description: t('Grafana’s MCP server for querying dashboards, metrics, and incident context from Grafana instances.', 'Grafana 的 MCP server，可從 Grafana instance 查詢 dashboards、metrics 與 incident context。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 84,
    compatibilityScore: 82,
    reliabilityScore: 84,
    docsScore: 80,
    adoptionScore: 79,
    safetyMaintenanceScore: 78,
    overallScore: 82,
    bestUseCases: ['research', 'agent-automation'],
    deployment: 'hybrid',
    installMethod: 'pip',
    supportedHosts: ['Grafana Cloud', 'Grafana OSS', 'MCP clients'],
    capabilities: ['dashboard search', 'dashboard summaries', 'metric access', 'incident context'],
    auth: { type: 'api-key', notes: 'Requires Grafana URL plus service account or compatible token.' },
    permissionProfile: { level: 'high', notes: 'Observability systems often expose sensitive operational data and should stay tightly scoped.' },
    worksWith: ['Grafana Cloud', 'Prometheus-backed dashboards', 'Claude Desktop'],
    tags: ['grafana', 'mcp', 'observability'],
    strengths: [t('Useful for teams that want AI access to real operational context instead of screenshots or summaries.', '對想讓 AI 直接讀取真實營運上下文的團隊很有幫助。'), t('Official Grafana repo plus developer guidance made the integration legible enough to promote.', '官方 Grafana repo 加上官方開發者指引，讓這項整合清楚到足以 promotion。')],
    caveats: [t('Less broadly applicable than general-purpose search or browser tools.', '不像通用搜尋或瀏覽器工具那麼泛用。'), t('Access to dashboards and incidents can expose sensitive production details.', 'dashboard 與 incident 存取可能暴露敏感的 production 細節。')],
    updatedAt: EXTERNAL_VALIDATION_AT,
    sourceRefs: skillSources('Grafana MCP', {
      officialUrl: 'https://grafana.com/',
      docsUrl: 'https://grafana.com/developers/plugin-tools/how-to-guides/app-plugins/use-llms-and-mcp',
      repoUrl: 'https://github.com/grafana/mcp-grafana',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }, EXTERNAL_VALIDATION_AT),
  }),
  defineSkill({
    slug: 'xcodebuildmcp',
    name: 'XcodeBuildMCP',
    providerId: 'any',
    categoryId: 'coding-devtools',
    subCategory: 'Apple platform build tooling',
    skillType: 'coding',
    officialUrl: 'https://github.com/getsentry/XcodeBuildMCP',
    docsUrl: 'https://github.com/getsentry/XcodeBuildMCP',
    repoUrl: 'https://github.com/getsentry/XcodeBuildMCP',
    preferredSourceUrl: 'https://github.com/getsentry/XcodeBuildMCP',
    officialSourceLabel: 'GitHub repo',
    description: t('Sentry’s XcodeBuildMCP gives coding agents build, simulator, testing, and inspection tools for iOS/macOS projects.', 'Sentry 的 XcodeBuildMCP 讓 coding agents 可取得 iOS/macOS 專案的 build、simulator、測試與檢查工具。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 83,
    compatibilityScore: 80,
    reliabilityScore: 83,
    docsScore: 82,
    adoptionScore: 77,
    safetyMaintenanceScore: 77,
    overallScore: 81,
    bestUseCases: ['coding'],
    deployment: 'local',
    installMethod: 'npm',
    supportedHosts: ['Claude Code', 'Cursor', 'Apple developer workstations'],
    capabilities: ['xcode builds', 'simulator control', 'UI testing', 'log capture'],
    auth: { type: 'none' },
    permissionProfile: { level: 'high', notes: 'Direct control over local build tooling, simulators, and project files requires strong operator boundaries.' },
    worksWith: ['Claude Code', 'Cursor', 'iOS/macOS repositories'],
    tags: ['xcode', 'apple', 'coding'],
    strengths: [t('Very concrete capability set for Apple-platform coding agents.', '對 Apple 平台 coding agents 來說，能力邊界非常具體。'), t('Maintainer-controlled repo and install instructions are explicit enough for live cataloging.', 'maintainer 控制的 repo 與安裝說明夠清楚，適合進 live catalog。')],
    caveats: [t('Niche compared with broader coding tools.', '比起更廣泛的 coding 工具，它偏 niche。'), t('Only relevant if your team actually ships iOS or macOS software.', '只有團隊真的在做 iOS 或 macOS 軟體時才會 relevant。')],
    updatedAt: EXTERNAL_VALIDATION_AT,
    sourceRefs: skillSources('XcodeBuildMCP', {
      officialUrl: 'https://github.com/getsentry/XcodeBuildMCP',
      docsUrl: 'https://github.com/getsentry/XcodeBuildMCP',
      repoUrl: 'https://github.com/getsentry/XcodeBuildMCP',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'permissionProfile'],
    }, EXTERNAL_VALIDATION_AT),
  }),
  defineSkill({
    slug: 'terraform-mcp-server',
    name: 'Terraform MCP Server',
    providerId: 'any',
    categoryId: 'coding-devtools',
    subCategory: 'Infrastructure-as-code context',
    skillType: 'coding',
    officialUrl: 'https://www.hashicorp.com/',
    docsUrl: 'https://developer.hashicorp.com/terraform/mcp-server',
    repoUrl: 'https://github.com/hashicorp/terraform-mcp-server',
    preferredSourceUrl: 'https://developer.hashicorp.com/terraform/mcp-server',
    officialSourceLabel: 'HashiCorp docs',
    description: t('HashiCorp’s Terraform MCP server gives agents current registry docs, modules, policies, and workspace context for IaC work.', 'HashiCorp 的 Terraform MCP server 可讓 agents 取得最新 registry 文件、modules、policies 與 workspace context，以支援 IaC 工作。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Advanced',
    utilityScore: 87,
    compatibilityScore: 84,
    reliabilityScore: 84,
    docsScore: 88,
    adoptionScore: 82,
    safetyMaintenanceScore: 79,
    overallScore: 84,
    bestUseCases: ['coding', 'agent-automation'],
    deployment: 'hybrid',
    installMethod: 'manual',
    supportedHosts: ['MCP clients', 'Terraform teams', 'local workstation'],
    capabilities: ['registry documentation access', 'module lookup', 'policy lookup', 'workspace operations'],
    auth: { type: 'custom', notes: 'Can involve Terraform Registry, HCP Terraform, Terraform Enterprise, and local credentials.' },
    permissionProfile: { level: 'high', notes: 'Workspace and infrastructure operations can have direct production impact if write scopes are enabled.' },
    worksWith: ['Terraform Registry', 'HCP Terraform', 'MCP clients'],
    tags: ['terraform', 'iac', 'mcp'],
    strengths: [t('Strong official-docs signal and very clear IaC-specific utility.', '官方文件信號強，而且 IaC 用途非常清楚。'), t('Helps reduce stale Terraform knowledge by pulling current registry context.', '能透過最新 registry context 降低 Terraform 知識過時問題。')],
    caveats: [t('Still beta and not something to wire into production blindly.', '仍是 beta，不適合不加思考就接進 production。'), t('High-impact permissions make write access especially sensitive.', '高影響權限讓寫入能力特別敏感。')],
    updatedAt: EXTERNAL_VALIDATION_AT,
    sourceRefs: skillSources('Terraform MCP Server', {
      officialUrl: 'https://www.hashicorp.com/',
      docsUrl: 'https://developer.hashicorp.com/terraform/mcp-server',
      repoUrl: 'https://github.com/hashicorp/terraform-mcp-server',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }, EXTERNAL_VALIDATION_AT),
  }),
  defineSkill({
    slug: 'elevenlabs-mcp',
    name: 'ElevenLabs MCP',
    providerId: 'any',
    categoryId: 'data-extraction',
    subCategory: 'Voice and audio tooling',
    skillType: 'extraction',
    officialUrl: 'https://elevenlabs.io/',
    docsUrl: 'https://elevenlabs.io/blog/introducing-elevenlabs-mcp',
    repoUrl: 'https://github.com/elevenlabs/elevenlabs-mcp',
    preferredSourceUrl: 'https://github.com/elevenlabs/elevenlabs-mcp',
    officialSourceLabel: 'ElevenLabs repo',
    description: t('ElevenLabs’ official MCP server exposes text-to-speech, voice cloning, transcription, and audio-generation tools to MCP clients.', 'ElevenLabs 官方 MCP server，可把文字轉語音、聲音複製、轉錄與音訊生成工具暴露給 MCP clients。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 84,
    compatibilityScore: 82,
    reliabilityScore: 84,
    docsScore: 83,
    adoptionScore: 82,
    safetyMaintenanceScore: 78,
    overallScore: 82,
    bestUseCases: ['research', 'agent-automation'],
    deployment: 'local',
    installMethod: 'pip',
    supportedHosts: ['Claude Desktop', 'Cursor', 'OpenAI Agents', 'MCP clients'],
    capabilities: ['text to speech', 'voice cloning', 'speech transcription', 'audio generation'],
    auth: { type: 'api-key', notes: 'Requires ElevenLabs API access and usage credits.' },
    permissionProfile: { level: 'medium', notes: 'Mostly API-bound, but generated or cloned voices still raise brand and consent considerations.' },
    worksWith: ['Claude Desktop', 'Cursor', 'OpenAI Agents'],
    tags: ['audio', 'voice', 'mcp'],
    strengths: [t('Official maintainer signal is strong and the capability surface is easy to understand.', '官方維護信號強，而且能力面容易理解。'), t('Useful when teams want speech or transcription inside general MCP-based agent workflows.', '當團隊想把語音或轉錄放進一般 MCP workflow 時很有用。')],
    caveats: [t('Usage credits and API cost matter quickly for audio-heavy workflows.', '音訊密集 workflow 很快就會受到 credits 與 API 成本影響。'), t('Voice cloning features need stronger policy review than ordinary text tools.', '聲音複製功能比一般文字工具更需要嚴格政策審查。')],
    updatedAt: EXTERNAL_VALIDATION_AT,
    sourceRefs: skillSources('ElevenLabs MCP', {
      officialUrl: 'https://elevenlabs.io/',
      docsUrl: 'https://elevenlabs.io/blog/introducing-elevenlabs-mcp',
      repoUrl: 'https://github.com/elevenlabs/elevenlabs-mcp',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }, EXTERNAL_VALIDATION_AT),
  }),
  defineSkill({
    slug: 'vercel-skills',
    name: 'Vercel Skills',
    providerId: 'any',
    categoryId: 'coding-devtools',
    subCategory: 'Agent skill installer and discovery CLI',
    skillType: 'coding',
    officialUrl: 'https://vercel.com/',
    docsUrl: 'https://vercel.com/docs/agent-resources/skills',
    repoUrl: 'https://github.com/vercel-labs/skills',
    preferredSourceUrl: 'https://vercel.com/docs/agent-resources/skills',
    officialSourceLabel: 'Vercel docs',
    description: t('Vercel’s open skills CLI for discovering, installing, and managing reusable agent skills across multiple coding agents.', 'Vercel 的 open skills CLI，可在多種 coding agents 之間探索、安裝與管理可重用的 agent skills。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 87,
    compatibilityScore: 88,
    reliabilityScore: 84,
    docsScore: 88,
    adoptionScore: 86,
    safetyMaintenanceScore: 79,
    overallScore: 86,
    bestUseCases: ['coding', 'agent-automation'],
    deployment: 'local',
    installMethod: 'npm',
    supportedHosts: ['Claude Code', 'GitHub Copilot', 'Cursor', 'Cline'],
    capabilities: ['skill discovery', 'skill installation', 'multi-agent compatibility', 'repo-based skill management'],
    auth: { type: 'none' },
    permissionProfile: { level: 'medium', notes: 'It installs skill packages into agent directories, so source trust still matters.' },
    worksWith: ['skills.sh', 'Claude Code', 'GitHub Copilot', 'Cursor'],
    tags: ['skills', 'cli', 'agentskills'],
    strengths: [t('This is one of the clearest bridges from the emerging agent-skills ecosystem into practical day-to-day use.', '這是新興 agent-skills 生態進入日常實用場景最清楚的橋樑之一。'), t('Official Vercel docs explicitly document compatibility across many coding agents.', 'Vercel 官方文件明確說明了對多種 coding agent 的相容性。')],
    caveats: [t('The CLI is only as good as the quality of the skills you install through it.', 'CLI 的價值仍取決於你透過它安裝的 skill 品質。'), t('Discovery momentum is strong, but the broader skill ecosystem is still maturing quickly.', 'discovery 動能很強，但更廣泛的 skill 生態仍在快速演化。')],
    updatedAt: EXTERNAL_VALIDATION_AT,
    sourceRefs: skillSources('Vercel Skills', {
      officialUrl: 'https://vercel.com/',
      docsUrl: 'https://vercel.com/docs/agent-resources/skills',
      repoUrl: 'https://github.com/vercel-labs/skills',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'permissionProfile'],
    }, EXTERNAL_VALIDATION_AT),
  }),
  defineSkill({
    slug: 'discord-mcp',
    name: 'Discord MCP',
    providerId: 'any',
    categoryId: 'workflow-automation',
    subCategory: 'Discord automation server',
    skillType: 'mcp',
    repoUrl: 'https://github.com/SaseQ/discord-mcp',
    preferredSourceUrl: 'https://github.com/SaseQ/discord-mcp',
    officialSourceLabel: 'GitHub repo',
    description: t('A focused MCP server for reading Discord state, sending messages, managing channels, and handling server-level automation tasks.', '一個聚焦的 Discord MCP server，可讀取伺服器狀態、傳送訊息、管理頻道，並處理伺服器層級的自動化任務。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 82,
    compatibilityScore: 85,
    reliabilityScore: 77,
    docsScore: 80,
    adoptionScore: 75,
    safetyMaintenanceScore: 67,
    overallScore: 79,
    bestUseCases: ['agent-automation'],
    deployment: 'local',
    installMethod: 'manual',
    supportedHosts: ['OpenClaw', 'Claude Code', 'Codex CLI', 'Cursor', 'Claude Desktop'],
    capabilities: ['discord messaging', 'channel management', 'role and member actions', 'server introspection'],
    auth: { type: 'local-config', notes: 'Requires a Discord bot token and MCP client/server configuration.' },
    permissionProfile: { level: 'high', notes: 'This server can read and modify Discord server state, so bot scopes and target guilds need tight control.' },
    worksWith: ['OpenClaw', 'Claude Code', 'Codex CLI', 'Discord bot API'],
    tags: ['mcp', 'discord', 'automation'],
    strengths: [t('Capability boundary is concrete: it is an MCP layer for Discord operations, not a vague “community agent” bundle.', '能力邊界很具體：它就是 Discord 操作的 MCP 層，不是模糊的「社群 agent」大禮包。'), t('Maintainer repo documents OpenClaw, Claude Code, Codex, Cursor, and Claude Desktop setup paths directly.', 'maintainer repo 直接文件化了 OpenClaw、Claude Code、Codex、Cursor 與 Claude Desktop 的接法。')],
    caveats: [t('High-permission Discord automations deserve especially careful token scoping and bot-role review.', '高權限的 Discord 自動化尤其需要審慎控管 token scope 與 bot role。'), t('Community-maintained MCP servers can change quickly, so live claims should stay narrow and operational rather than promotional.', '社群維護的 MCP server 變動可能很快，因此 live 描述應維持狹窄、偏操作面，而不是宣傳式表述。')],
    updatedAt: EXTERNAL_VALIDATION_AT,
    sourceRefs: [
      officialSource('Discord MCP repo', 'https://github.com/SaseQ/discord-mcp', 'github', EXTERNAL_VALIDATION_AT, ['repoUrl', 'summary', 'description', 'installMethod', 'supportedHosts', 'auth', 'permissionProfile']),
      manualReviewSource('Discord MCP VerdictLens review', EXTERNAL_VALIDATION_AT, editorialFields, 'Validated against the maintainer repo plus independent MCP discovery listings such as mcpindex, LobeHub MCP, and Glama; live entry keeps claims narrow to the documented Discord server automation surface.'),
    ],
  }),
  defineSkill({
    slug: 'x-research-skill',
    name: 'X Research Skill',
    providerId: 'any',
    categoryId: 'research-retrieval',
    subCategory: 'Social research workflow',
    skillType: 'search',
    repoUrl: 'https://github.com/rohunvora/x-research-skill',
    preferredSourceUrl: 'https://github.com/rohunvora/x-research-skill',
    officialSourceLabel: 'GitHub repo',
    description: t('A focused AgentSkills-style workflow for searching X/Twitter, following threads, monitoring accounts, and producing sourced briefings.', '一個聚焦的 AgentSkills 風格 workflow，可搜尋 X/Twitter、追蹤 threads、監看帳號並產出有來源的 briefings。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 79,
    compatibilityScore: 82,
    reliabilityScore: 76,
    docsScore: 80,
    adoptionScore: 74,
    safetyMaintenanceScore: 72,
    overallScore: 78,
    bestUseCases: ['research'],
    deployment: 'local',
    installMethod: 'github',
    supportedHosts: ['Claude Code', 'OpenClaw', 'AgentSkills-compatible agents'],
    capabilities: ['X search', 'thread following', 'watchlists', 'sourced briefings'],
    auth: { type: 'api-key', notes: 'Requires X API bearer token or equivalent configured credentials.' },
    permissionProfile: { level: 'medium', notes: 'Mostly retrieval-oriented, but it still reaches an external social feed and can incur API spend.' },
    worksWith: ['Claude Code', 'OpenClaw', 'X API'],
    tags: ['research', 'x', 'agentskills'],
    strengths: [t('Narrow scope makes it more legible than generic “do research” repos.', '範圍夠窄，比泛泛的「做研究」repo 更容易理解。'), t('It showed both maintainer repo clarity and independent discovery listings, which is exactly the kind of staged item worth promoting.', '它同時有清楚的 maintainer repo 與獨立 discovery listing，正是值得 promotion 的 staged item。')],
    caveats: [t('Depends on X API access, pricing, and the quality of a noisy social feed.', '依賴 X API 權限、定價，以及本身就很吵雜的社群資料流。'), t('Use it as a research signal, not a truth oracle.', '應把它當成 research signal，而不是 truth oracle。')],
    updatedAt: EXTERNAL_VALIDATION_AT,
    sourceRefs: [
      officialSource('X Research Skill repo', 'https://github.com/rohunvora/x-research-skill', 'github', EXTERNAL_VALIDATION_AT, ['repoUrl', 'summary', 'description', 'installMethod', 'supportedHosts', 'auth']),
      manualReviewSource('X Research Skill VerdictLens review', EXTERNAL_VALIDATION_AT, editorialFields, 'Validated against the maintainer repo plus independent AgentSkills discovery listings; live entry keeps claims narrow and workflow-scoped.'),
    ],
  }),
];
