import { defineSkill, manualReviewSource, officialSource } from './factories';

const VERIFIED_AT = '2026-04-09T08:00:00.000Z';

const t = (en: string, zhTW: string) => ({ en, 'zh-TW': zhTW });

const editorialFields = ['bestFor', 'worksWith', 'capabilities', 'permissionProfile', 'overallScore'];

function review(name: string) {
  return manualReviewSource(`${name} VerdictLens review`, VERIFIED_AT, editorialFields, 'Editorial shortlist guidance is intentionally separated from official product facts.');
}

function skillSources(name: string, input: {
  officialUrl?: string;
  docsUrl?: string;
  repoUrl?: string;
  registryUrl?: string;
  coreFields?: string[];
}) {
  return [
    ...(input.docsUrl ? [officialSource(`${name} docs`, input.docsUrl, 'official-docs', VERIFIED_AT, input.coreFields ?? ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'])] : []),
    ...(input.repoUrl ? [officialSource(`${name} repo`, input.repoUrl, 'github', VERIFIED_AT, ['repoUrl'])] : []),
    ...(input.registryUrl ? [officialSource(`${name} registry`, input.registryUrl, 'official-registry', VERIFIED_AT, ['registryUrl'])] : []),
    ...(input.officialUrl ? [officialSource(`${name} official`, input.officialUrl, 'official-site', VERIFIED_AT, ['officialUrl'])] : []),
    review(name),
  ];
}

export const skills = [
  defineSkill({
    slug: 'codex-cli',
    name: 'Codex CLI',
    providerId: 'openai',
    categoryId: 'coding-devtools',
    subCategory: 'CLI coding agent',
    skillType: 'coding',
    officialUrl: 'https://openai.com/',
    docsUrl: 'https://developers.openai.com/codex/cli/',
    repoUrl: 'https://github.com/openai/codex',
    preferredSourceUrl: 'https://developers.openai.com/codex/cli/',
    officialSourceLabel: 'OpenAI docs',
    description: t('OpenAI’s terminal-first coding agent for editing code, running commands, and agentic development loops.', 'OpenAI 的終端優先 coding agent，可編輯程式、執行指令並進行 agent 式開發迴圈。'),
    supportedProviderIds: ['openai'],
    installDifficulty: 'Easy',
    utilityScore: 93,
    compatibilityScore: 84,
    reliabilityScore: 90,
    docsScore: 90,
    adoptionScore: 88,
    safetyMaintenanceScore: 83,
    overallScore: 90,
    bestUseCases: ['coding'],
    deployment: 'local',
    installMethod: 'npm',
    supportedHosts: ['CLI', 'local workstation'],
    capabilities: ['code editing', 'terminal execution', 'repo-aware workflows', 'patch generation'],
    auth: { type: 'api-key', notes: 'OpenAI account / API auth.' },
    permissionProfile: { level: 'high', notes: 'Can read and modify local repositories and run commands.' },
    worksWith: ['GPT-5', 'GPT-5 mini', 'GitHub'],
    tags: ['coding', 'cli', 'agent'],
    strengths: [t('Tight CLI loop for code-centric work.', '很適合 code-centric 工作的 CLI 迴圈。'), t('Natural fit for repo-based engineering tasks.', '很適合 repo 型工程任務。')],
    caveats: [t('High local permissions need operator discipline.', '本地權限高，需要操作紀律。'), t('Mostly optimized for developer workflows.', '主要仍偏向開發者工作流。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Codex CLI', {
      officialUrl: 'https://openai.com/',
      docsUrl: 'https://developers.openai.com/codex/cli/',
      repoUrl: 'https://github.com/openai/codex',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'claude-code',
    name: 'Claude Code',
    providerId: 'anthropic',
    categoryId: 'coding-devtools',
    subCategory: 'CLI coding agent',
    skillType: 'coding',
    officialUrl: 'https://www.anthropic.com/',
    docsUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
    preferredSourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
    officialSourceLabel: 'Anthropic docs',
    description: t('Anthropic’s terminal coding agent for repository work, refactors, debugging, and code generation.', 'Anthropic 的終端 coding agent，適合 repo 工作、重構、debug 與程式生成。'),
    supportedProviderIds: ['anthropic'],
    installDifficulty: 'Easy',
    utilityScore: 92,
    compatibilityScore: 82,
    reliabilityScore: 90,
    docsScore: 91,
    adoptionScore: 89,
    safetyMaintenanceScore: 82,
    overallScore: 89,
    bestUseCases: ['coding'],
    deployment: 'local',
    installMethod: 'npm',
    supportedHosts: ['CLI', 'local workstation'],
    capabilities: ['repo-aware coding', 'debugging', 'refactors', 'terminal workflows'],
    auth: { type: 'api-key', notes: 'Anthropic account / API auth.' },
    permissionProfile: { level: 'high', notes: 'Can inspect and modify code and run commands locally.' },
    worksWith: ['Claude Sonnet 4.6', 'Claude Opus 4.6', 'GitHub'],
    tags: ['coding', 'cli', 'anthropic'],
    strengths: [t('Strong fit for code review and refactor-heavy sessions.', '很適合 code review 與重構密集工作。'), t('Part of Anthropic’s broader MCP-friendly ecosystem.', '屬於 Anthropic 更大的 MCP 友善生態。')],
    caveats: [t('Local command execution still needs careful controls.', '本地指令執行仍需要審慎控管。'), t('Mostly centered on Anthropic-native workflows.', '主要仍以 Anthropic 原生工作流為中心。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Claude Code', {
      officialUrl: 'https://www.anthropic.com/',
      docsUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'langgraph',
    name: 'LangGraph',
    providerId: 'any',
    categoryId: 'agent-frameworks',
    subCategory: 'Graph orchestration',
    skillType: 'workflow',
    officialUrl: 'https://www.langchain.com/langgraph',
    docsUrl: 'https://langchain-ai.github.io/langgraph/',
    repoUrl: 'https://github.com/langchain-ai/langgraph',
    preferredSourceUrl: 'https://langchain-ai.github.io/langgraph/',
    officialSourceLabel: 'LangGraph docs',
    description: t('A stateful graph orchestration framework for long-running agents and controllable multi-step workflows.', '用於長時間運行 agents 與可控多步驟流程的有狀態 graph 編排框架。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'deepseek', 'mistral', 'cohere', 'perplexity', 'local'],
    installDifficulty: 'Moderate',
    utilityScore: 92,
    compatibilityScore: 94,
    reliabilityScore: 88,
    docsScore: 88,
    adoptionScore: 89,
    safetyMaintenanceScore: 85,
    overallScore: 90,
    bestUseCases: ['agent-automation', 'coding'],
    deployment: 'hybrid',
    installMethod: 'pip',
    supportedHosts: ['Python apps', 'APIs', 'workers'],
    capabilities: ['stateful orchestration', 'agent graphs', 'human-in-the-loop', 'durable execution'],
    auth: { type: 'none' },
    permissionProfile: { level: 'medium', notes: 'Framework-level; actual risk depends on attached tools.' },
    worksWith: ['OpenAI', 'Anthropic', 'Google', 'MCP servers'],
    tags: ['framework', 'graphs', 'agents'],
    strengths: [t('Excellent for explicit, inspectable multi-step flows.', '很適合需要明確、可檢查的多步驟流程。'), t('Works well when teams want control rather than magic.', '適合想要控制權而不是黑盒魔法的團隊。')],
    caveats: [t('Adds orchestration complexity.', '會引入編排複雜度。'), t('Overkill for simple single-call apps.', '對單次呼叫型 app 可能太重。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('LangGraph', {
      officialUrl: 'https://www.langchain.com/langgraph',
      docsUrl: 'https://langchain-ai.github.io/langgraph/',
      repoUrl: 'https://github.com/langchain-ai/langgraph',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'supportedProviderIds'],
    }),
  }),
  defineSkill({
    slug: 'langchain',
    name: 'LangChain',
    providerId: 'any',
    categoryId: 'agent-frameworks',
    subCategory: 'LLM app framework',
    skillType: 'workflow',
    officialUrl: 'https://www.langchain.com/',
    docsUrl: 'https://docs.langchain.com/',
    repoUrl: 'https://github.com/langchain-ai/langchain',
    preferredSourceUrl: 'https://docs.langchain.com/',
    officialSourceLabel: 'LangChain docs',
    description: t('A broad framework for building LLM apps, retrieval pipelines, and agent workflows across providers.', '用來打造 LLM app、檢索管線與跨供應商 agent workflow 的廣泛框架。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'deepseek', 'mistral', 'cohere', 'perplexity', 'local'],
    installDifficulty: 'Moderate',
    utilityScore: 90,
    compatibilityScore: 95,
    reliabilityScore: 86,
    docsScore: 86,
    adoptionScore: 92,
    safetyMaintenanceScore: 83,
    overallScore: 89,
    bestUseCases: ['agent-automation', 'coding', 'research'],
    deployment: 'hybrid',
    installMethod: 'pip',
    supportedHosts: ['Python apps', 'JavaScript apps', 'APIs'],
    capabilities: ['provider abstraction', 'retrieval pipelines', 'tool integration', 'agent flows'],
    auth: { type: 'none' },
    permissionProfile: { level: 'medium', notes: 'Risk depends on the tools and providers connected.' },
    worksWith: ['LangGraph', 'OpenAI', 'Anthropic', 'Weaviate'],
    tags: ['framework', 'retrieval', 'agents'],
    strengths: [t('Very broad ecosystem coverage.', '生態覆蓋非常廣。'), t('Good for teams that need provider abstraction.', '對需要供應商抽象層的團隊很有用。')],
    caveats: [t('The breadth can feel heavy for smaller apps.', '對小型 app 來說，廣度有時會顯得過重。'), t('Abstractions can obscure provider-specific strengths.', '抽象層有時會遮蔽供應商原生優勢。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('LangChain', {
      officialUrl: 'https://www.langchain.com/',
      docsUrl: 'https://docs.langchain.com/',
      repoUrl: 'https://github.com/langchain-ai/langchain',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'supportedProviderIds'],
    }),
  }),
  defineSkill({
    slug: 'openai-agents-sdk',
    name: 'OpenAI Agents SDK',
    providerId: 'openai',
    categoryId: 'agent-frameworks',
    subCategory: 'Provider-native agent SDK',
    skillType: 'api',
    officialUrl: 'https://openai.com/',
    docsUrl: 'https://openai.github.io/openai-agents-python/',
    repoUrl: 'https://github.com/openai/openai-agents-python',
    preferredSourceUrl: 'https://openai.github.io/openai-agents-python/',
    officialSourceLabel: 'OpenAI Agents docs',
    description: t('OpenAI’s provider-native SDK for building agents with tools, handoffs, guardrails, and tracing.', 'OpenAI 原生的 agent SDK，可建立含工具、handoff、guardrail 與 tracing 的 agents。'),
    supportedProviderIds: ['openai'],
    installDifficulty: 'Moderate',
    utilityScore: 89,
    compatibilityScore: 76,
    reliabilityScore: 88,
    docsScore: 88,
    adoptionScore: 82,
    safetyMaintenanceScore: 85,
    overallScore: 86,
    bestUseCases: ['agent-automation', 'coding'],
    deployment: 'hybrid',
    installMethod: 'pip',
    supportedHosts: ['Python apps', 'workers', 'APIs'],
    capabilities: ['tool calling', 'handoffs', 'guardrails', 'tracing'],
    auth: { type: 'api-key', notes: 'OpenAI API auth.' },
    permissionProfile: { level: 'medium', notes: 'SDK-level risk depends on attached tools and code execution choices.' },
    worksWith: ['OpenAI models', 'OpenAI Responses API', 'MCP'],
    tags: ['sdk', 'agents', 'provider-native'],
    strengths: [t('Very aligned with OpenAI-native agent features.', '和 OpenAI 原生 agent 功能高度對齊。'), t('Good choice when deep OpenAI integration matters more than neutrality.', '當深度整合 OpenAI 比中立性更重要時很適合。')],
    caveats: [t('Less provider-neutral than LangGraph or LangChain.', '不像 LangGraph / LangChain 那麼中立。'), t('Best for teams already comfortable with OpenAI’s stack.', '最適合已熟悉 OpenAI stack 的團隊。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('OpenAI Agents SDK', {
      officialUrl: 'https://openai.com/',
      docsUrl: 'https://openai.github.io/openai-agents-python/',
      repoUrl: 'https://github.com/openai/openai-agents-python',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'n8n',
    name: 'n8n',
    providerId: 'any',
    categoryId: 'workflow-automation',
    subCategory: 'No-code automation',
    skillType: 'workflow',
    officialUrl: 'https://n8n.io/',
    docsUrl: 'https://docs.n8n.io/',
    repoUrl: 'https://github.com/n8n-io/n8n',
    preferredSourceUrl: 'https://docs.n8n.io/',
    officialSourceLabel: 'n8n docs',
    description: t('A workflow automation platform for triggers, integrations, and multi-step AI operations.', '可做觸發器、整合與多步驟 AI 營運流程的工作流自動化平台。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'deepseek', 'mistral', 'cohere', 'perplexity', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 90,
    compatibilityScore: 92,
    reliabilityScore: 87,
    docsScore: 87,
    adoptionScore: 90,
    safetyMaintenanceScore: 84,
    overallScore: 89,
    bestUseCases: ['agent-automation'],
    deployment: 'hybrid',
    installMethod: 'manual',
    supportedHosts: ['self-hosted', 'cloud'],
    capabilities: ['trigger-based workflows', 'integrations', 'approval steps', 'AI automation'],
    auth: { type: 'oauth', notes: 'Depends on connected services and provider keys.' },
    permissionProfile: { level: 'medium', notes: 'Workflow nodes can reach many external systems.' },
    worksWith: ['Zapier AI Actions', 'OpenAI', 'Anthropic', 'Google Workspace'],
    tags: ['automation', 'workflow', 'integrations'],
    strengths: [t('Practical for operational AI workflows that need triggers and approvals.', '很適合需要觸發與審批的營運型 AI 工作流。'), t('Flexible enough for mixed human-and-AI processes.', '對人機混合流程相當靈活。')],
    caveats: [t('Governance matters once workflows touch many systems.', '當 workflow 接到很多系統後，治理會變重要。'), t('Can become spaghetti without workflow discipline.', '若缺少流程紀律，容易長成 spaghetti。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('n8n', {
      officialUrl: 'https://n8n.io/',
      docsUrl: 'https://docs.n8n.io/',
      repoUrl: 'https://github.com/n8n-io/n8n',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'pipedream',
    name: 'Pipedream',
    providerId: 'any',
    categoryId: 'workflow-automation',
    subCategory: 'API workflow automation',
    skillType: 'workflow',
    officialUrl: 'https://pipedream.com/',
    docsUrl: 'https://pipedream.com/docs/',
    preferredSourceUrl: 'https://pipedream.com/docs/',
    officialSourceLabel: 'Pipedream docs',
    description: t('An integration and automation platform for event-driven workflows, APIs, and AI actions.', '用於事件驅動 workflow、API 與 AI actions 的整合自動化平台。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 85,
    compatibilityScore: 88,
    reliabilityScore: 86,
    docsScore: 86,
    adoptionScore: 84,
    safetyMaintenanceScore: 83,
    overallScore: 85,
    bestUseCases: ['agent-automation'],
    deployment: 'hosted',
    installMethod: 'hosted',
    supportedHosts: ['cloud'],
    capabilities: ['event triggers', 'API orchestration', 'webhooks', 'automation components'],
    auth: { type: 'oauth', notes: 'Depends on connected services.' },
    permissionProfile: { level: 'medium', notes: 'Hosted automation layer with access to connected services.' },
    worksWith: ['OpenAI', 'Slack', 'GitHub', 'Google Workspace'],
    tags: ['automation', 'apis', 'hosted'],
    strengths: [t('Fast path for API-heavy workflows.', '很適合快速組裝 API 密集型流程。'), t('Good fit for hosted event-driven automations.', '很適合託管型事件驅動自動化。')],
    caveats: [t('Hosted workflow centralization can raise governance questions.', '流程集中到 hosted 層後，治理問題會變得重要。'), t('Less ideal for teams wanting maximum local control.', '不太適合要求高度本地控制的團隊。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Pipedream', {
      officialUrl: 'https://pipedream.com/',
      docsUrl: 'https://pipedream.com/docs/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'playwright',
    name: 'Playwright',
    providerId: 'any',
    categoryId: 'browser-web',
    subCategory: 'Browser automation',
    skillType: 'browser',
    officialUrl: 'https://playwright.dev/',
    docsUrl: 'https://playwright.dev/docs/intro',
    repoUrl: 'https://github.com/microsoft/playwright',
    preferredSourceUrl: 'https://playwright.dev/docs/intro',
    officialSourceLabel: 'Playwright docs',
    description: t('A modern browser automation framework used for reliable UI scripting, testing, and web interactions.', '現代化瀏覽器自動化框架，適合穩定的 UI 腳本、測試與網頁互動。'),
    supportedProviderIds: ['any'],
    installDifficulty: 'Moderate',
    utilityScore: 89,
    compatibilityScore: 87,
    reliabilityScore: 92,
    docsScore: 90,
    adoptionScore: 93,
    safetyMaintenanceScore: 84,
    overallScore: 89,
    bestUseCases: ['coding', 'agent-automation', 'research'],
    deployment: 'hybrid',
    installMethod: 'npm',
    supportedHosts: ['Node.js', 'Python', 'CI'],
    capabilities: ['browser control', 'scraping', 'testing', 'page automation'],
    auth: { type: 'none' },
    permissionProfile: { level: 'medium', notes: 'Browser automation can access authenticated sessions and web content.' },
    worksWith: ['Browserbase', 'LangGraph', 'web agents'],
    tags: ['browser', 'automation', 'testing'],
    strengths: [t('Very dependable browser automation baseline.', '瀏覽器自動化基線非常可靠。'), t('Widely understood and well documented.', '普及度高、文件也成熟。')],
    caveats: [t('Running browsers at scale still adds operational overhead.', '大規模跑瀏覽器仍然有營運成本。'), t('Not a hosted browser service on its own.', '本身不是 hosted browser 服務。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Playwright', {
      officialUrl: 'https://playwright.dev/',
      docsUrl: 'https://playwright.dev/docs/intro',
      repoUrl: 'https://github.com/microsoft/playwright',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts'],
    }),
  }),
  defineSkill({
    slug: 'browserbase',
    name: 'Browserbase',
    providerId: 'any',
    categoryId: 'browser-web',
    subCategory: 'Hosted browser infrastructure',
    skillType: 'browser',
    officialUrl: 'https://www.browserbase.com/',
    docsUrl: 'https://docs.browserbase.com/',
    preferredSourceUrl: 'https://docs.browserbase.com/',
    officialSourceLabel: 'Browserbase docs',
    description: t('Hosted browser infrastructure for running browser automation and web agents in the cloud.', '託管式瀏覽器基礎設施，可在雲端執行瀏覽器自動化與 web agents。'),
    supportedProviderIds: ['any'],
    installDifficulty: 'Easy',
    utilityScore: 87,
    compatibilityScore: 84,
    reliabilityScore: 88,
    docsScore: 86,
    adoptionScore: 82,
    safetyMaintenanceScore: 84,
    overallScore: 85,
    bestUseCases: ['agent-automation', 'research'],
    deployment: 'hosted',
    installMethod: 'npm',
    supportedHosts: ['cloud', 'Node.js'],
    capabilities: ['hosted browsers', 'session replay', 'browser agents', 'remote execution'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'medium', notes: 'Hosted browser sessions can access external websites and credentials.' },
    worksWith: ['Playwright', 'web agents', 'automation workflows'],
    tags: ['browser', 'hosted', 'infra'],
    strengths: [t('Removes a lot of browser ops pain.', '能移除不少瀏覽器維運痛點。'), t('Useful for teams moving browser automation into production.', '很適合把瀏覽器自動化推進 production 的團隊。')],
    caveats: [t('Adds a vendor dependency for browser runtime.', '會增加瀏覽器 runtime 的供應商依賴。'), t('Sensitive workflows still need session and secret hygiene.', '敏感流程仍要注意 session 與 secret 管理。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Browserbase', {
      officialUrl: 'https://www.browserbase.com/',
      docsUrl: 'https://docs.browserbase.com/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'firecrawl',
    name: 'Firecrawl',
    providerId: 'any',
    categoryId: 'research-retrieval',
    subCategory: 'Web crawling and extraction',
    skillType: 'extraction',
    officialUrl: 'https://www.firecrawl.dev/',
    docsUrl: 'https://docs.firecrawl.dev/',
    repoUrl: 'https://github.com/mendableai/firecrawl',
    preferredSourceUrl: 'https://docs.firecrawl.dev/',
    officialSourceLabel: 'Firecrawl docs',
    description: t('A web crawling and extraction layer designed to turn sites into clean content for AI pipelines.', '專為 AI pipeline 把網站轉成乾淨內容的 web crawling 與 extraction 層。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 89,
    compatibilityScore: 88,
    reliabilityScore: 84,
    docsScore: 85,
    adoptionScore: 86,
    safetyMaintenanceScore: 80,
    overallScore: 86,
    bestUseCases: ['research', 'agent-automation'],
    deployment: 'hybrid',
    installMethod: 'npm',
    supportedHosts: ['cloud', 'Node.js', 'Python'],
    capabilities: ['crawling', 'markdown extraction', 'scraping APIs', 'site ingestion'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'medium', notes: 'Interacts with third-party websites and external content.' },
    worksWith: ['LangChain', 'LangGraph', 'vector stores'],
    tags: ['crawl', 'extract', 'rag'],
    strengths: [t('Great fit for content ingestion and RAG prep.', '很適合內容擷取與 RAG 前處理。'), t('Canonical crawling API helps reduce custom scraper work.', '統一的 crawling API 可以減少客製 scraper 工作。')],
    caveats: [t('Website variability always creates some extraction edge cases.', '網站差異永遠會帶來一些擷取 edge case。'), t('Still needs legal and rate-limit awareness.', '仍要注意法務與 rate limit。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Firecrawl', {
      officialUrl: 'https://www.firecrawl.dev/',
      docsUrl: 'https://docs.firecrawl.dev/',
      repoUrl: 'https://github.com/mendableai/firecrawl',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'tavily',
    name: 'Tavily',
    providerId: 'any',
    categoryId: 'research-retrieval',
    subCategory: 'Search API',
    skillType: 'search',
    officialUrl: 'https://tavily.com/',
    docsUrl: 'https://docs.tavily.com/',
    preferredSourceUrl: 'https://docs.tavily.com/',
    officialSourceLabel: 'Tavily docs',
    description: t('A search API built for LLMs and agents that need live web results and research context.', '為 LLM 與 agents 設計的搜尋 API，可提供即時網頁結果與研究上下文。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 87,
    compatibilityScore: 89,
    reliabilityScore: 84,
    docsScore: 86,
    adoptionScore: 84,
    safetyMaintenanceScore: 81,
    overallScore: 85,
    bestUseCases: ['research', 'agent-automation'],
    deployment: 'hosted',
    installMethod: 'api',
    supportedHosts: ['cloud', 'Python', 'JavaScript'],
    capabilities: ['web search', 'LLM-friendly results', 'research context', 'SERP access'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'low' },
    worksWith: ['LangChain', 'LangGraph', 'research agents'],
    tags: ['search', 'research', 'api'],
    strengths: [t('Simple way to add live web context to agents.', '能很簡單地替 agent 加上即時網頁上下文。'), t('Designed for LLM consumption rather than raw search UI.', '設計重點是給 LLM 消費，而不是傳統搜尋 UI。')],
    caveats: [t('Search quality still depends on query strategy.', '搜尋品質仍取決於 query 策略。'), t('Not a full crawling or browser stack.', '不是完整 crawling 或 browser stack。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Tavily', {
      officialUrl: 'https://tavily.com/',
      docsUrl: 'https://docs.tavily.com/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'exa',
    name: 'Exa',
    providerId: 'any',
    categoryId: 'research-retrieval',
    subCategory: 'Web search and data API',
    skillType: 'search',
    officialUrl: 'https://exa.ai/',
    docsUrl: 'https://docs.exa.ai/',
    preferredSourceUrl: 'https://docs.exa.ai/',
    officialSourceLabel: 'Exa docs',
    description: t('A search and web data API for retrieval, company research, and agent discovery tasks.', '用於檢索、公司研究與 agent 發現任務的搜尋與 web data API。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 86,
    compatibilityScore: 88,
    reliabilityScore: 84,
    docsScore: 85,
    adoptionScore: 82,
    safetyMaintenanceScore: 81,
    overallScore: 84,
    bestUseCases: ['research'],
    deployment: 'hosted',
    installMethod: 'api',
    supportedHosts: ['cloud', 'Python', 'JavaScript'],
    capabilities: ['search API', 'web data retrieval', 'entity research', 'content discovery'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'low' },
    worksWith: ['research agents', 'LangChain', 'CRM enrichment'],
    tags: ['search', 'data', 'research'],
    strengths: [t('Strong fit for structured research and company discovery.', '很適合結構化研究與公司探索。'), t('Useful when search needs to feed downstream systems, not just chat.', '當搜尋結果要餵給下游系統，而不只是聊天時會很好用。')],
    caveats: [t('Narrower than full browser automation.', '範圍比完整瀏覽器自動化更窄。'), t('Teams still need their own ranking and evaluation logic.', '團隊仍需自建排序與評估邏輯。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Exa', {
      officialUrl: 'https://exa.ai/',
      docsUrl: 'https://docs.exa.ai/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'serpapi',
    name: 'SerpApi',
    providerId: 'any',
    categoryId: 'research-retrieval',
    subCategory: 'SERP API',
    skillType: 'search',
    officialUrl: 'https://serpapi.com/',
    docsUrl: 'https://serpapi.com/search-api',
    preferredSourceUrl: 'https://serpapi.com/search-api',
    officialSourceLabel: 'SerpApi docs',
    description: t('An API layer for search engine result pages across major engines and verticals.', '可取得主要搜尋引擎與垂直場景結果頁的 API 層。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 82,
    compatibilityScore: 88,
    reliabilityScore: 86,
    docsScore: 84,
    adoptionScore: 86,
    safetyMaintenanceScore: 82,
    overallScore: 83,
    bestUseCases: ['research'],
    deployment: 'hosted',
    installMethod: 'api',
    supportedHosts: ['cloud', 'Python', 'JavaScript'],
    capabilities: ['SERP APIs', 'shopping results', 'maps results', 'news results'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'low' },
    worksWith: ['research agents', 'market intelligence', 'SEO tooling'],
    tags: ['search', 'serp', 'api'],
    strengths: [t('Wide search-engine coverage.', '搜尋引擎覆蓋面廣。'), t('Useful for structured data collection from SERPs.', '適合從 SERP 收集結構化資料。')],
    caveats: [t('Less opinionated for LLM-native workflows than some newer APIs.', '對 LLM-native workflow 的意見性較弱。'), t('Often needs extra post-processing before model use.', '模型使用前常需要額外後處理。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('SerpApi', {
      officialUrl: 'https://serpapi.com/',
      docsUrl: 'https://serpapi.com/search-api',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'openai-whisper',
    name: 'OpenAI Whisper',
    providerId: 'openai',
    categoryId: 'data-extraction',
    subCategory: 'Speech transcription',
    skillType: 'extraction',
    officialUrl: 'https://github.com/openai/whisper',
    docsUrl: 'https://github.com/openai/whisper',
    repoUrl: 'https://github.com/openai/whisper',
    preferredSourceUrl: 'https://github.com/openai/whisper',
    officialSourceLabel: 'OpenAI repo',
    description: t('OpenAI’s open-source speech recognition model and CLI for local transcription.', 'OpenAI 開源的語音辨識模型與 CLI，可做本地轉錄。'),
    supportedProviderIds: ['local'],
    installDifficulty: 'Moderate',
    utilityScore: 85,
    compatibilityScore: 75,
    reliabilityScore: 86,
    docsScore: 82,
    adoptionScore: 92,
    safetyMaintenanceScore: 85,
    overallScore: 84,
    bestUseCases: ['research'],
    deployment: 'local',
    installMethod: 'pip',
    supportedHosts: ['macOS', 'Linux', 'Windows'],
    capabilities: ['speech-to-text', 'local transcription', 'multilingual recognition'],
    auth: { type: 'none' },
    permissionProfile: { level: 'low' },
    worksWith: ['media pipelines', 'meeting transcription', 'podcast ingestion'],
    tags: ['audio', 'transcription', 'local'],
    strengths: [t('Local transcription avoids sending audio to an API.', '本地轉錄不必把音訊送到 API。'), t('Still one of the best-known open transcription baselines.', '仍是最知名的開源轉錄基線之一。')],
    caveats: [t('Local performance depends heavily on available hardware.', '本地效能很依賴硬體。'), t('Not a full managed speech platform.', '不是完整託管語音平台。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('OpenAI Whisper', {
      officialUrl: 'https://github.com/openai/whisper',
      docsUrl: 'https://github.com/openai/whisper',
      repoUrl: 'https://github.com/openai/whisper',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts'],
    }),
  }),
  defineSkill({
    slug: '1password-cli',
    name: '1Password CLI',
    providerId: 'any',
    categoryId: 'security-secrets',
    subCategory: 'Secrets management',
    skillType: 'security',
    officialUrl: 'https://1password.com/',
    docsUrl: 'https://developer.1password.com/docs/cli/',
    preferredSourceUrl: 'https://developer.1password.com/docs/cli/',
    officialSourceLabel: '1Password docs',
    description: t('A secrets-management CLI for injecting, reading, and operating on credentials in workflows.', '可在工作流中注入、讀取與操作憑證的 secrets-management CLI。'),
    supportedProviderIds: ['any'],
    installDifficulty: 'Easy',
    utilityScore: 88,
    compatibilityScore: 86,
    reliabilityScore: 91,
    docsScore: 89,
    adoptionScore: 87,
    safetyMaintenanceScore: 94,
    overallScore: 89,
    bestUseCases: ['coding', 'agent-automation'],
    deployment: 'local',
    installMethod: 'manual',
    supportedHosts: ['CLI', 'macOS', 'Linux', 'Windows'],
    capabilities: ['secret injection', 'vault access', 'credential automation', 'service-account support'],
    auth: { type: 'local-config', notes: 'Requires 1Password account/session.' },
    permissionProfile: { level: 'high', notes: 'Touches sensitive credentials and secret material.' },
    worksWith: ['CI/CD', 'local dev', 'agent workflows'],
    tags: ['secrets', 'security', 'cli'],
    strengths: [t('Strong fit for practical secret hygiene.', '非常適合實務上的 secret hygiene。'), t('Good bridge between developer workflows and safer credential handling.', '能把開發者工作流和更安全的憑證管理接起來。')],
    caveats: [t('Secrets tooling deserves extra operational review.', 'secret 工具本來就值得額外審查。'), t('Account setup and session handling add onboarding steps.', '帳號設定與 session 管理會增加上手步驟。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('1Password CLI', {
      officialUrl: 'https://1password.com/',
      docsUrl: 'https://developer.1password.com/docs/cli/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'weaviate',
    name: 'Weaviate',
    providerId: 'any',
    categoryId: 'memory-knowledge',
    subCategory: 'Vector database',
    skillType: 'memory',
    officialUrl: 'https://weaviate.io/',
    docsUrl: 'https://docs.weaviate.io/',
    repoUrl: 'https://github.com/weaviate/weaviate',
    preferredSourceUrl: 'https://docs.weaviate.io/',
    officialSourceLabel: 'Weaviate docs',
    description: t('A vector database and knowledge layer for retrieval, semantic search, and memory-heavy AI systems.', '用於檢索、語義搜尋與記憶密集 AI 系統的向量資料庫與知識層。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'local', 'any'],
    installDifficulty: 'Advanced',
    utilityScore: 87,
    compatibilityScore: 88,
    reliabilityScore: 86,
    docsScore: 85,
    adoptionScore: 86,
    safetyMaintenanceScore: 83,
    overallScore: 85,
    bestUseCases: ['research', 'agent-automation'],
    deployment: 'hybrid',
    installMethod: 'manual',
    supportedHosts: ['self-hosted', 'cloud', 'Kubernetes'],
    capabilities: ['vector search', 'knowledge storage', 'retrieval', 'hybrid search'],
    auth: { type: 'api-key', notes: 'Varies by deployment mode.' },
    permissionProfile: { level: 'medium', notes: 'Stores knowledge and embeddings that may be sensitive.' },
    worksWith: ['LangChain', 'LangGraph', 'Firecrawl'],
    tags: ['vector-db', 'memory', 'retrieval'],
    strengths: [t('Good fit for structured knowledge layers.', '很適合作為結構化知識層。'), t('Supports more serious retrieval architectures than a quick demo stack.', '比起 demo stack，更能支撐正式的檢索架構。')],
    caveats: [t('Database operations add maintenance burden.', '資料庫維運會增加負擔。'), t('Not necessary for every small assistant.', '不是每個小型助理都需要。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Weaviate', {
      officialUrl: 'https://weaviate.io/',
      docsUrl: 'https://docs.weaviate.io/',
      repoUrl: 'https://github.com/weaviate/weaviate',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth'],
    }),
  }),
  defineSkill({
    slug: 'mem0',
    name: 'Mem0',
    providerId: 'any',
    categoryId: 'memory-knowledge',
    subCategory: 'Memory layer',
    skillType: 'memory',
    officialUrl: 'https://mem0.ai/',
    docsUrl: 'https://docs.mem0.ai/',
    repoUrl: 'https://github.com/mem0ai/mem0',
    preferredSourceUrl: 'https://docs.mem0.ai/',
    officialSourceLabel: 'Mem0 docs',
    description: t('A memory layer for capturing, storing, and retrieving useful user or agent context over time.', '用來長期捕捉、儲存與取回使用者或 agent 上下文的記憶層。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 84,
    compatibilityScore: 86,
    reliabilityScore: 82,
    docsScore: 83,
    adoptionScore: 80,
    safetyMaintenanceScore: 79,
    overallScore: 82,
    bestUseCases: ['agent-automation'],
    deployment: 'hybrid',
    installMethod: 'pip',
    supportedHosts: ['Python', 'JavaScript', 'cloud'],
    capabilities: ['memory capture', 'context retrieval', 'user profiling', 'agent memory'],
    auth: { type: 'api-key', notes: 'Depends on deployment and storage backend.' },
    permissionProfile: { level: 'medium', notes: 'Memory systems can accumulate sensitive long-lived context.' },
    worksWith: ['LangGraph', 'LangChain', 'agent assistants'],
    tags: ['memory', 'context', 'agents'],
    strengths: [t('Explicit memory layer helps move beyond stateless chat.', '明確的記憶層有助於走出 stateless chat。'), t('Useful for personalization and continuity.', '對個人化與連續性很有幫助。')],
    caveats: [t('Memory quality and privacy policy matter as much as tooling.', '記憶品質與隱私政策和工具本身一樣重要。'), t('Poor memory hygiene can become a trust problem quickly.', '記憶 hygiene 不好，很快就會變成信任問題。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Mem0', {
      officialUrl: 'https://mem0.ai/',
      docsUrl: 'https://docs.mem0.ai/',
      repoUrl: 'https://github.com/mem0ai/mem0',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'github-mcp-server',
    name: 'GitHub MCP Server',
    providerId: 'any',
    categoryId: 'coding-devtools',
    subCategory: 'GitHub integration',
    skillType: 'mcp',
    officialUrl: 'https://github.com/github/github-mcp-server',
    docsUrl: 'https://github.com/github/github-mcp-server',
    repoUrl: 'https://github.com/github/github-mcp-server',
    preferredSourceUrl: 'https://github.com/github/github-mcp-server',
    officialSourceLabel: 'GitHub repo',
    description: t('An official GitHub MCP server for repository, issue, PR, and code-context operations.', '官方 GitHub MCP server，可處理 repository、issue、PR 與程式碼上下文操作。'),
    supportedProviderIds: ['openai', 'anthropic', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 87,
    compatibilityScore: 84,
    reliabilityScore: 85,
    docsScore: 82,
    adoptionScore: 81,
    safetyMaintenanceScore: 80,
    overallScore: 84,
    bestUseCases: ['coding', 'agent-automation'],
    deployment: 'hybrid',
    installMethod: 'npm',
    supportedHosts: ['MCP clients', 'CLI agents'],
    capabilities: ['repo access', 'issues', 'PRs', 'code context'],
    auth: { type: 'oauth', notes: 'GitHub auth / token scope required.' },
    permissionProfile: { level: 'high', notes: 'Can access and potentially modify repository data depending on granted scopes.' },
    worksWith: ['Claude Code', 'Codex CLI', 'MCP clients'],
    tags: ['mcp', 'github', 'coding'],
    strengths: [t('Very relevant for coding agents working inside GitHub workflows.', '對 GitHub 工作流中的 coding agent 非常 relevant。'), t('Official source helps reduce ambiguity about the canonical server.', '官方來源降低了 canonical server 的模糊性。')],
    caveats: [t('Permissions should be scoped tightly.', '權限應盡量縮小。'), t('Still depends on the MCP host’s maturity and UX.', '仍取決於 MCP host 本身的成熟度與 UX。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('GitHub MCP Server', {
      officialUrl: 'https://github.com/github/github-mcp-server',
      docsUrl: 'https://github.com/github/github-mcp-server',
      repoUrl: 'https://github.com/github/github-mcp-server',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'supabase-mcp-server',
    name: 'Supabase MCP Server',
    providerId: 'any',
    categoryId: 'memory-knowledge',
    subCategory: 'Database integration',
    skillType: 'mcp',
    officialUrl: 'https://supabase.com/',
    docsUrl: 'https://supabase.com/docs/guides/getting-started/mcp',
    preferredSourceUrl: 'https://supabase.com/docs/guides/getting-started/mcp',
    officialSourceLabel: 'Supabase docs',
    description: t('Supabase’s MCP integration layer for connecting agents to database-backed product context.', 'Supabase 的 MCP 整合層，可讓 agents 連到資料庫驅動的產品上下文。'),
    supportedProviderIds: ['openai', 'anthropic', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 84,
    compatibilityScore: 82,
    reliabilityScore: 84,
    docsScore: 83,
    adoptionScore: 78,
    safetyMaintenanceScore: 80,
    overallScore: 82,
    bestUseCases: ['agent-automation', 'coding'],
    deployment: 'hybrid',
    installMethod: 'manual',
    supportedHosts: ['MCP clients', 'Supabase projects'],
    capabilities: ['database access', 'product context', 'tool connectivity', 'MCP integration'],
    auth: { type: 'api-key', notes: 'Supabase project credentials and MCP host setup required.' },
    permissionProfile: { level: 'high', notes: 'Database-connected tools need careful read/write scoping.' },
    worksWith: ['Supabase', 'MCP clients', 'coding agents'],
    tags: ['mcp', 'database', 'supabase'],
    strengths: [t('Useful where product context lives in Supabase.', '當產品上下文本來就在 Supabase 裡時很有價值。'), t('Helps bridge application data into agent workflows.', '能把應用資料橋接進 agent workflow。')],
    caveats: [t('Database permissions need especially careful review.', '資料庫權限尤其需要小心審查。'), t('More relevant for Supabase-centered stacks than general teams.', '對以 Supabase 為中心的 stack 才特別 relevant。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Supabase MCP Server', {
      officialUrl: 'https://supabase.com/',
      docsUrl: 'https://supabase.com/docs/guides/getting-started/mcp',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'mcp-toolbox',
    name: 'Gen AI Toolbox for Databases',
    providerId: 'google',
    categoryId: 'agent-frameworks',
    subCategory: 'Database tool layer',
    skillType: 'mcp',
    officialUrl: 'https://github.com/googleapis/genai-toolbox',
    docsUrl: 'https://github.com/googleapis/genai-toolbox',
    repoUrl: 'https://github.com/googleapis/genai-toolbox',
    preferredSourceUrl: 'https://github.com/googleapis/genai-toolbox',
    officialSourceLabel: 'Google repo',
    description: t('Google’s open-source toolbox for exposing database tools to GenAI systems and MCP-capable clients.', 'Google 開源的 toolbox，可把資料庫工具暴露給 GenAI 系統與支援 MCP 的 client。'),
    supportedProviderIds: ['google', 'openai', 'anthropic', 'any'],
    installDifficulty: 'Advanced',
    utilityScore: 84,
    compatibilityScore: 82,
    reliabilityScore: 82,
    docsScore: 80,
    adoptionScore: 76,
    safetyMaintenanceScore: 79,
    overallScore: 81,
    bestUseCases: ['agent-automation', 'coding'],
    deployment: 'hybrid',
    installMethod: 'manual',
    supportedHosts: ['MCP clients', 'containerized deployments'],
    capabilities: ['database tools', 'tool serving', 'MCP compatibility', 'data access abstraction'],
    auth: { type: 'custom', notes: 'Depends on database and deployment configuration.' },
    permissionProfile: { level: 'high', notes: 'Database tool exposure needs explicit read/write policy control.' },
    worksWith: ['MCP clients', 'databases', 'Google AI workflows'],
    tags: ['mcp', 'databases', 'tooling'],
    strengths: [t('Interesting bridge between databases and agent tools.', '在資料庫與 agent 工具之間提供有趣的橋接層。'), t('Official Google stewardship helps signal canonical direction.', '由 Google 維護，有助於傳達 canonical direction。')],
    caveats: [t('Operational complexity is non-trivial.', '營運複雜度不低。'), t('Needs strong governance before exposing production data.', '在暴露正式資料前需要嚴格治理。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Gen AI Toolbox for Databases', {
      officialUrl: 'https://github.com/googleapis/genai-toolbox',
      docsUrl: 'https://github.com/googleapis/genai-toolbox',
      repoUrl: 'https://github.com/googleapis/genai-toolbox',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'e2b-sandbox',
    name: 'E2B Sandbox',
    providerId: 'any',
    categoryId: 'execution-sandboxes',
    subCategory: 'Hosted execution',
    skillType: 'connector',
    officialUrl: 'https://e2b.dev/',
    docsUrl: 'https://e2b.dev/docs',
    preferredSourceUrl: 'https://e2b.dev/docs',
    officialSourceLabel: 'E2B docs',
    description: t('A hosted execution sandbox for giving agents safer code-running environments.', '給 agents 使用、較安全的託管程式執行沙盒。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Moderate',
    utilityScore: 86,
    compatibilityScore: 84,
    reliabilityScore: 85,
    docsScore: 84,
    adoptionScore: 80,
    safetyMaintenanceScore: 87,
    overallScore: 84,
    bestUseCases: ['coding', 'agent-automation'],
    deployment: 'hosted',
    installMethod: 'npm',
    supportedHosts: ['cloud', 'Python', 'JavaScript'],
    capabilities: ['sandboxed execution', 'ephemeral environments', 'code running', 'tool isolation'],
    auth: { type: 'api-key' },
    permissionProfile: { level: 'medium', notes: 'Safer than local execution but still needs scope controls.' },
    worksWith: ['LangGraph', 'OpenAI Agents SDK', 'coding agents'],
    tags: ['sandbox', 'execution', 'agents'],
    strengths: [t('Helpful when local execution is too risky.', '當本地執行風險太高時很有幫助。'), t('Makes code-running agents more production-friendly.', '讓可執行程式的 agents 更接近 production。')],
    caveats: [t('Adds hosted execution cost and dependency.', '會增加 hosted execution 成本與依賴。'), t('Still requires policy boundaries for what agents may run.', '仍需要對 agent 可執行內容設邊界。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('E2B Sandbox', {
      officialUrl: 'https://e2b.dev/',
      docsUrl: 'https://e2b.dev/docs',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
  defineSkill({
    slug: 'zapier-ai-actions',
    name: 'Zapier AI Actions',
    providerId: 'any',
    categoryId: 'workflow-automation',
    subCategory: 'Hosted actions layer',
    skillType: 'connector',
    officialUrl: 'https://zapier.com/',
    docsUrl: 'https://actions.zapier.com/docs/platform/gpt/',
    preferredSourceUrl: 'https://actions.zapier.com/docs/platform/gpt/',
    officialSourceLabel: 'Zapier docs',
    description: t('Zapier’s action layer for letting AI systems trigger business tools and SaaS workflows.', '讓 AI 系統觸發商務工具與 SaaS workflow 的 Zapier action 層。'),
    supportedProviderIds: ['openai', 'anthropic', 'google', 'any'],
    installDifficulty: 'Easy',
    utilityScore: 84,
    compatibilityScore: 87,
    reliabilityScore: 86,
    docsScore: 83,
    adoptionScore: 89,
    safetyMaintenanceScore: 81,
    overallScore: 84,
    bestUseCases: ['agent-automation'],
    deployment: 'hosted',
    installMethod: 'hosted',
    supportedHosts: ['cloud'],
    capabilities: ['app actions', 'SaaS automation', 'business workflow triggers', 'tool access'],
    auth: { type: 'oauth', notes: 'Depends on connected apps.' },
    permissionProfile: { level: 'medium', notes: 'Can act across many connected business apps.' },
    worksWith: ['ChatGPT actions', 'business SaaS', 'workflow automation'],
    tags: ['automation', 'actions', 'saas'],
    strengths: [t('Huge app ecosystem makes it very practical.', '龐大 app 生態讓它很實用。'), t('Useful bridge from AI assistants into business systems.', '能把 AI 助理順利接進商務系統。')],
    caveats: [t('Action sprawl can become hard to govern.', 'action 過多時不容易治理。'), t('Hosted middleware may not fit every security posture.', '託管中介層未必符合所有安全姿態。')],
    updatedAt: VERIFIED_AT,
    sourceRefs: skillSources('Zapier AI Actions', {
      officialUrl: 'https://zapier.com/',
      docsUrl: 'https://actions.zapier.com/docs/platform/gpt/',
      coreFields: ['summary', 'description', 'installMethod', 'deployment', 'supportedHosts', 'auth', 'permissionProfile'],
    }),
  }),
];
